### ISSUE TITLE
Mismatching behavior between segment and section taper rates

### ISSUE THREAD

**Issue by eleftherioszisis** [BlueBrain/NeuroM#1004]
Segment taper rates calculate the absolute slope of the segment diameters:

https://github.com/BlueBrain/NeuroM/blob/a9e3020f242b3ff04cdc244e068afdfc7137dfcb/neurom/features/neurite.py#L230-L243

```
np.abs(diff[:, COLS.R])
```
whereas the section taper rates calculate the signed slope from the linear fit to the diameters:

https://github.com/BlueBrain/NeuroM/blob/a9e3020f242b3ff04cdc244e068afdfc7137dfcb/neurom/features/neurite.py#L247-L259

Is this to be expected? I would expect that in both cases the signed slope would be desired.

```python
from io import StringIO

import numpy as np
from numpy import testing as npt

from neurom.features import neurite
from neurom import load_morphology

neu = load_morphology(StringIO(u"""((CellBody) (0 0 0 2))
                                    ((Dendrite)
                                     (0 0 0 2)
                                     (1 0 0 1)
                                     (2 0 0 0))"""), reader='asc')


npt.assert_almost_equal(neurite.section_taper_rates(neu.neurites[0]), [-1])
npt.assert_almost_equal(neurite.segment_taper_rates(neu.neurites[0]), [-1., -1])

```
The second test fails with `[1, 1]`

@lidakanari @arnaudon @adrien-berchet

**Comment by arnaudon** [comment]
You're right, abs should not be. I think I added section taper rate for diameter synthesis a while ago, probably I didn't pay attention to the segment one, which is
