### ISSUE TITLE
Maximal direction extent

### ISSUE THREAD

**Issue by eleftherioszisis** [BlueBrain/NeuroM#1009]
@lidakanari , asked for a maximal direction extent feature in https://github.com/BlueBrain/NeuroM/pull/1008#issuecomment-1073704148

There are two ways to achieve this:

1. Add a new feature that will return the maximum of the principal direction extents.
2. Order the existing principal_direction_extent feature from max to min. The max extent would then be equal to `principal_direction_extent(direction=0)`

@arnaudon , @adrien-berchet, @mgeplf

**Comment by arnaudon** [comment]
I don't have strong opinion on that, maybe sorting the output of current feature would be enough. I'm not a user of that feature, so I'm not sure of its use cases and how its output is used down the line.

**Comment by lidakanari** [comment]
Sorting the output would be sufficient for me as well. This is used for validation purposes and by default the `axis=0` is outputed for the `morph_stats` app. So if the extents are sorted this will resolve the problem.
