### ISSUE TITLE
New feature: aspect ratio

### ISSUE THREAD

**Issue by lidakanari** [BlueBrain/NeuroM#1010]
This feature needs to be implemented on the 2D projection of a morphology and it will describe the minimum over the maximum dimension in the projected plane i.e. x-y. We will therefore need to compute this in all three projections at the morphology level. 

To extract the projection points from a morphology:

``` python 
def get_points_projection(neurite, projection1='X', projection2='Y'):
    proj1 = neurite.points[:, getattr(nm.COLS, projection1)]
    proj2 = neurite.points[:, getattr(nm.COLS, projection2)]
    return np.transpose([proj1, proj2])
```

Please find some sample code for this feature:

``` python 
def aspect_ratio(pts):
    """Computes min dimension / max dimension"""
    max_dim = np.max(nm.morphmath.principal_direction_extent(pts))
    min_dim = np.min(nm.morphmath.principal_direction_extent(pts))
    return min_dim / max_dim
```

**Comment by lidakanari** [comment]
For testing purposes here are a few shapes:

[TestData.zip](https://github.com/BlueBrain/NeuroM/files/8332749/TestData.zip)

The expected results for these shapes:
``` python
aspect_ratio(circle) == 0.9838348383830106
aspect_ratio(square) == 0.9799193845949096
aspect_ratio(rectangle) == 0.33658158126782983
aspect_ratio(oval) == 0.49083100011838016

```

**Comment by eleftherioszisis** [comment]
Using the convex hull points to avoid the point distribution to affect the principal directions, I get the following results:
```python
In [4]: aspect_ratio(circle)
Out[4]: 0.9975026440270615

In [5]: aspect_ratio(square)
Out[5]: 0.9829836870510568

In [6]: aspect_ratio(rectangle)
Out[6]: 0.4130280313071019

In [7]: aspect_ratio(oval)
Out[7]: 0.493502615108013
```
