### ISSUE TITLE
Is there a way to define optional arguments from morph_stats application?

### ISSUE THREAD

**Issue by lidakanari** [BlueBrain/NeuroM#1015]
I would like to use `extract_dataframe` from `morph_stats` with the shape features, such as `aspect_ratio`. 

This function works with a config as follows:

``` python
from neurom.apps import morph_stats
full_cfg = morph_stats.full_config()
df = morph_stats.extract_dataframe(neuron, config=full_cfg)
```
How can I select the options such as `projection_plane` from the input `config`? 

I am not sure if this is possible with the current code, if not would it be possible to add this?

**Comment by adrien-berchet** [comment]
For the records, I think you are speaking about this:
https://neurom.readthedocs.io/en/stable/morph_stats.html#kwargs-format-starting-version-3-0-0
