### ISSUE TITLE
Features should return consistent types

### ISSUE THREAD

**Issue by adrien-berchet** [BlueBrain/NeuroM#1062]
The `NeuroM.features.*` functions return inconsistent types. For example, `segment_taper_rates` returns a list of `floats` while `section_taper_rates` returns a list of `numpy.float32`. This can be annoying to process results (e.g. it's harder to dump the results to JSON strings or stuff like that).
I suggest we make all the types consistent, like casting all the results to built-in Python types.
WDYT @eleftherioszisis @mgeplf ? If you agree I can work on this.

**Comment by eleftherioszisis** [comment]
Yeah, makes sense to me to have consistent types.

**Comment by adrien-berchet** [comment]
Will be fixed in v4
