### ISSUE TITLE
Error loading h5 : Missing points or structure datasets, cannot load morphology without them

### ISSUE THREAD

**Issue by sruthi-hub** [BlueBrain/NeuroM#1066]
I am trying to use NeuroM for sholl analysis of skeletonized images generated from FIJI, or OpenCV (python). The black and white images are in the form of ndarray that I saved as an h5 file. When I try to load in the image, I get the following error regardless of if the images were generated by FIJI or Python. Could you help understand how I should save these h5 files differently? 

`h5f = h5py.File('y6_skeleton_threshold15.h5', 'w')`
`h5f.create_dataset('dataset', data=skel)`

`neuron = nm.load_morphology('/home/sruthi/projects/y6_skeleton_threshold15.h5')`

`OUTPUT:
---------------------------------------------------------------------------
RawDataError                              Traceback (most recent call last)
Cell In[2], line 2
      1 # Load a single morphology  
----> 2 neuron = nm.load_morphology('/home/sruthi/projects/y6_skeleton_threshold15.h5')

File ~/miniconda3/envs/morph_env/lib/python3.8/site-packages/neurom/io/utils.py:165, in load_morphology(morph, reader)
    162 if reader:
    163     return Morphology(_get_file(morph, reader))
--> 165 return Morphology(morph, Path(morph).name)

File ~/miniconda3/envs/morph_env/lib/python3.8/site-packages/neurom/core/morphology.py:435, in Morphology.__init__(self, filename, name)
    428 def __init__(self, filename, name=None):
    429     """Morphology constructor.
    430 
    431     Args:
    432         filename (str|Path): a filename
    433         name (str): a option morphology name
    434     """
--> 435     super().__init__(filename)
    436     self.name = name if name else 'Morphology'
    437     self.morphio_soma = super().soma

RawDataError: Missing points or structure datasets, cannot load morphology without them`

**Comment by jdcourcol** [comment]
@sruthi-hub would it be possible for you to share the "y6_skeleton_threshold15.h5" for us to reproduce the issue ?

**Comment by arnaudon** [comment]
Hello, this software is not meant to load images, but morphologies in a specific format (ascii, swc, or specific h5, as described in https://morphology-documentation.readthedocs.io/en/latest/h5v1.html).

**Comment by sruthi-hub** [comment]
Thanks for your quick response, @jdcourcol and @arnaudon. Here is the h5 file attached.
@arnaudon, thanks for sharing that morphology h5 files are different from regular h5 files. Could you point me to resources/tools that can be used to generate morphology h5 files from skeletonized images (numpy ndarray)?
[y6_skeleton_threshold15.h5.zip](https://github.com/BlueBrain/NeuroM/files/10449293/y6_skeleton_threshold15.h5.zip)

**Comment by eleftherioszisis** [comment]
@sruthi-hub HDF5 is a file format and any data can be written into it using tools such as [`h5py`](https://github.com/h5py/h5py).

The morphology specification is a specific layout to write the morphology skeleton data into the hdf5 format. MorphIO consumes this layout, along with the ascii and swc specifications that are written in plain text files, and NeuroM performs the analysis.

Therefore, we do not handle the generation of these formats. Unfortunately, I am not aware of tools that construct the skeleton from voxelized data.

Maybe @marwan-abdellah would have some input concerning this conversion.

**Comment by marwan-abdellah** [comment]
@eleftherioszisis @sruthi-hub The file is only a single table of size 1024x1024 elements (0s and 256s). The structure does not comply with the specifiecations as refered by @arnaudon.

**Comment by arnaudon** [comment]
from an image, I think there are several tools available. Here, we use neuroluscida (https://www.mbfbioscience.com/products/neurolucida), which is not open source and is quite expansive as it works with microscopes directly. Just a simple googling show me this one for example: https://www.reading.ac.uk/neuromantic/body_index.php

 If you don't find a tool that you like, you can always try 'by hand' and create for example the simpler tabular file format swc http://www.neuronland.org/NLMorphologyConverter/MorphologyFormats/SWC/Spec.html. 

Good luck with your research!

**Comment by sruthi-hub** [comment]
I really appreciate all your help @eleftherioszisis @marwan-abdellah @arnaudon since I am new to the image analysis world.
I'll explore some of the open source tools like neuromantic. Ultimately, I am trying to automate sholl analysis for a lot of images. I wonder if this specific step of manually encoding the structure will become a bottleneck for the automated pipeline. Any thoughts/suggestions on this is welcome! Thanks again!

**Comment by adrien-berchet** [comment]
Maybe you can use a different tool like https://imagej.net/plugins/sholl-analysis so you can directly work with 2d images?

**Comment by sruthi-hub** [comment]
@adrien-berchet This is exactly where I started. There may be some unavoidable manual steps like thresholding, and specifying the center of interest. It would be perfect if I am able to find a way to get most (if not all) analysis steps run automatically. I'll give that a try and reach out if I am stuck. Thanks a lot!

**Comment by arnaudon** [comment]
as you noticed, @adrien-berchet is the best! Have fun!
