### ISSUE TITLE
axon-carrying-dendrite where a dendrite ends on axonal fork

### ISSUE THREAD

**Issue by eleftherioszisis** [BlueBrain/NeuroM#1125]
NeuroM defines an axon-carrying-dendrite as a dendritic tree that at some point has one branch resulting in an axonal subtree.

However, in the SEU data @ssssarah encountered the following case where the dendrite's both children become axons.

![image](https://github.com/BlueBrain/NeuroM/assets/15011025/d476bc7c-6482-46c3-95df-3c58aa1c2746)

Would it be correct also to consider the neurite type as an axon-carrying dendrite? @lidakanari

**Comment by lidakanari** [comment]
I think the most reasonable action is to consider these as ACD. Thanks, @ssssarah @eleftherioszisis for investigating this!

**Comment by eleftherioszisis** [comment]
Fork AcDs are now detected as `NeuriteType.axon_carrying_dendrite` (#1127 ) for `neurom>=4.0.1`.
