### ISSUE TITLE
Decide on the parameters that should be saved for a uniform distribution.

### ISSUE THREAD

**Issue by lidakanari** [BlueBrain/NeuroM#113]
In the example of synthesis_json the (min, max) boundaries are overwritten by the fitted parameters when the optimal distribution is uniform. 

This should not be the case, so we have to define a clear representation.

**Comment by lidakanari** [comment]
So in the current instance (Mon 19/10/15) of synthesis_json example the parameters of the uniform fit are overwritten by the user's choice for (min, max). Is this the optimal solution?

**Comment by juanchopanza** [comment]
No, that isn't the desired behaviour. But I can't see that in the code. Do you have a simple code sample that would reproduce this behaviour?

**Comment by lidakanari** [comment]
Sorry, my bad. Currently, the uniform is extracted from the fit (since the uniform distribution is returned before the min, max check of the user). So, the min, max of the user are ignored in the case of uniform distribution.
