### ISSUE TITLE
Disable h5py loading when instantiating swc morphology ?

### ISSUE THREAD

**Issue by wvangeit** [BlueBrain/NeuroM#130]
Would it be possible to only load h5py when loading .h5 morphologies ? 
I was trying to load an swc morphology, but I got as error that h5py is not installed. I guess h5py is not necessary in code that only uses swc morphologies ?

h5py is also not set as dependency for pip, so it generated an error after installing NeuroM using pip.

**Comment by juanchopanza** [comment]
Fixed by #171
