### ISSUE TITLE
Loading of Allen Brain swc fails

### ISSUE THREAD

**Issue by wvangeit** [BlueBrain/NeuroM#131]
When trying to load a morphology available on the Allen Brain website, I get an error.
The cell is:
http://celltypes.brain-map.org/mouse/experiment/morphology/313861608
direct download:
http://celltypes.brain-map.org/api/v2/well_known_file_download/464113244

    import neurom.ezy                                                                   
    morph = neurom.ezy.Neuron('Pvalb-IRES-Cre_Ai14_IVSCC_-165874.04.02.01_464113242_m.swc')

generates:

Traceback (most recent call last):
  File "test.py", line 3, in <module>
    morph = neurom.ezy.Neuron('Pvalb-IRES-Cre_Ai14_IVSCC_-165874.04.02.01_464113242_m.swc')
  File "/Users/werner/src/NeuroM/neurom/ezy/neuron.py", line 108, in __init__
    super(Neuron, self).__init__(neuron.soma, neuron.neurites, neuron.name)
AttributeError: 'str' object has no attribute 'soma'

Result of morph_check on that cell (having no apical dendrite should be no reason for failure, this is an interneuron):

INFO: ========================================
INFO: Check file Pvalb-IRES-Cre_Ai14_IVSCC_-165874.04.02.01_464113242_m.swc...
INFO:                     Has valid soma? PASS
INFO:                           Has Axon? PASS
ERROR:                Has Apical Dendrite? FAIL
INFO:                 Has Basal Dendrite? PASS
INFO:  All neurites have non-zero radius? PASS
INFO:  All segments have non-zero length? PASS
INFO:  All sections have non-zero length? PASS
ERROR:                       Check result: FAIL
INFO: ========================================

**Comment by juanchopanza** [comment]
The loading of ezy neurons has changed:

    from neurom import ezy
    morph = ezy.load_neuron('Pvalb-IRES-Cre_Ai14_IVSCC_-165874.04.02.01_464113242_m.swc')

Using that, the morphology looks OK (soma, 8 neurites). Please let me know if there is anything in the documentation that uses the old-style loading.

**Comment by juanchopanza** [comment]
See fix to README.rst in pull request #132.

**Comment by wvangeit** [comment]
Yes, indeed, got the example from the front page README :-)

**Comment by wvangeit** [comment]
Tried with load_neuron, the error is gone now. Thanks.

**Comment by juanchopanza** [comment]
OK, I'd say that was a documentation bug, now fixed.
