### ISSUE TITLE
ipython notebook doesn't load

### ISSUE THREAD

**Issue by juanchopanza** [BlueBrain/NeuroM#149]
The ipython notebook has merge conflicts, and so is broken and fails to load. See [the raw file](https://raw.githubusercontent.com/BlueBrain/NeuroM/master/ipynb/neurom.ipynb), and search for `<<<<<<<`.

**Comment by juanchopanza** [comment]
@eleftherioszisis could you have a look at this?

**Comment by eleftherioszisis** [comment]
Hmm this is peculiar. When I uploaded it it was working fine and the preview on github was working as well. I tried to run it now but it fails to load as you said. Any ideas how/why it became corrupted?

**Comment by juanchopanza** [comment]
No idea. As far as I can see, the only commits are yours. It looks like it should be easy to fix though.

**Comment by eleftherioszisis** [comment]
ok I fixed the merge conflicts in the notebook. (It's the last commit in the monotonic check pull request)

**Comment by juanchopanza** [comment]
This has been fixed by @eleftherioszisis
