### ISSUE TITLE
Tree comparison assumes node contents

### ISSUE THREAD

**Issue by mgeplf** [BlueBrain/NeuroM#156]
The comparison here:
https://github.com/BlueBrain/NeuroM/blob/master/neurom/core/tree.py#L282

Assumes that the node is slice-able, which isn't always the case.

**Comment by eleftherioszisis** [comment]
The loop is iterating over the values of the nodes, which are sliceable, aren't they?

**Comment by mgeplf** [comment]
Not necessarily, it's a generic tree, so the value could be anything: an int, another class, a dictionary, etc.  Also, assuming 4 elements isn't always the truth.

For example, in test_tree.py, 
doing 'REF_TREE == REF_TREE' will fail:
*** TypeError: 'int' object has no attribute '__getitem__'

**Comment by juanchopanza** [comment]
I agree with @mgeplf. The tree type makes no assumptions about the types of the nodes. These assumptions are made in other modules, such as `analysis.morphtree`. So I think this comparison could be moved out to a different module, and not set as "equality" for a tree. Better allow different ways of comparing trees.

**Comment by eleftherioszisis** [comment]
Indeed, I made that assumption when I created it and now I see why it does not belong there. Should I move it to morphtree?

**Comment by juanchopanza** [comment]
Yes, I think so, and remove the `__eq__` and call the comparison function explicitly where needed. That will be much clearer.

**Comment by juanchopanza** [comment]
@mgeplf The comparison has been moved out of the `Tree` class, and its `__eq__` operator removed. Does this look OK now?
