### ISSUE TITLE
NeuroM documentation link on front page

### ISSUE THREAD

**Issue by wvangeit** [BlueBrain/NeuroM#159]
NeuroM has a very nice documentation on readthedocs.org. It would be useful to put a link to this documentation on the github front page (readme). (I couldn't find a link on the main page)

**Comment by juanchopanza** [comment]
It is there. Click on the "docs | latest" badge.

**Comment by wvangeit** [comment]
Ok. But might still be useful to mention it in a header, I didn't see this (even after actively looking for it). I'm not sure a general user will look at all these badges.

**Comment by eleftherioszisis** [comment]
It never occurred to me that docs badge is a button! I think that Werner is right on this one. At first glance it appears as a colorful way to display the status of the tests, codecov and the state of documentation.

**Comment by juanchopanza** [comment]
I thought that was quite standard. I'll add something more verbose.
