### ISSUE TITLE
Soma.center as a class property

### ISSUE THREAD

**Issue by eleftherioszisis** [BlueBrain/NeuroM#161]
Currently, the center of the soma is set when the soma is created and its value is reflected in the list of the soma points. If its value is changed, the respective point in the point list is not changed as well which leads into having to take into account both the points and the soma center for rotations, translations.

Wouldn't it be more convenient if center was a soma property (using @property decorator) and not a variable which is set upon initialisation? This way any changes in the soma points will affect the soma.center as well.

Moreover, the soma center is a tuple while everything are numpy arrays which forces me to explicitly check for a tuple type for the transformations.

**Comment by juanchopanza** [comment]
Yes, that makes sense. So the center would be obtained on the fly from the points, and affine transformations would be bone on the points, right?

**Comment by eleftherioszisis** [comment]
Exactly.

**Comment by juanchopanza** [comment]
Do you want to make the changes or shall I?

**Comment by eleftherioszisis** [comment]
I can do it. Not sure though if I will do it before Tuesday.
I wish I could run the tests from my laptop. (The import h5py error still persists...)

**Comment by juanchopanza** [comment]
See pull request #162. However, thinking of it, this shouldn't be necessary to transform a soma. The transformed soma could and probably should be build from a set of transformed points from the original.

**Comment by eleftherioszisis** [comment]
Yes it is possible to use make_soma to create the new soma, but I wanted it to be clear and not create an extra copy of the points, transform it and the make the new soma which would require to put building code in the transform.py.

**Comment by juanchopanza** [comment]
Implemented in pull request #162
