### ISSUE TITLE
Is ezy module necessary ?

### ISSUE THREAD

**Issue by wvangeit** [BlueBrain/NeuroM#164]
I don't completely understand the rationale behind the 'ezy' module. Is it really necessary ? It creates some overhead when creating neurom scripts (and I try to avoid 'from ... import ...' statements to avoid namespace pollution)
It's also a pity it's not automatically imported together with neurom.

I know that I could
from neurom import ezy as neurom
but that's quite hacky

**Comment by juanchopanza** [comment]
The rationale is that it is where we put very specific and _limited_ stuff. It is supposed to be for people who don't want to use iterators and transformations, and it greatly limits what you can do. I don't like it much, and I don't want to pollute the top level `neurom` module with it. I would rather spend time working on making the iterators and transformation functions easier to use. Let's say it was a bad compromise.

**Comment by wvangeit** [comment]
Ok, makes sense. As long as the final implementation ends up in the top level, it's ok. (The only unfortunate thing is that it will probably require a lot of script-rewriting from the users once the top level stuff becomes more powerful)
