### ISSUE TITLE
Dendrogram example remarks

### ISSUE THREAD

**Issue by wvangeit** [BlueBrain/NeuroM#165]
I have a couple of remarks regarding the dendrogram example.
(https://github.com/BlueBrain/NeuroM/blob/master/examples/dendrogram.py)
I've attached an example output.

- The triangles near the soma need to be fixed in some way
- The diameter have to show up much thicker. Ideally different scaling on x- and y-axes should be used (with an option to enable/disable it?).
- Will this function become part of NeuroM api ? At the moment it's a bit difficult to use because I have to manually download the dendrogram.py file. Would be nice if it was a function of the NeuroM Neuron class.

Some details:
- Maybe only show the colors that are actually used in the legend ?
- Try to use a white instead of a grey figure background in matplotlib, looks much better
- We need units on the y-axis (maybe we don't even need an axis if we would have x/y scale bars)
- After calling 'dendrogram()' the figure window closes immediately if I don't put a pylab.show(). Maybe you can add an option as argument that enables/disables pylab.show() ?

![screen shot 2015-11-20 at 15 32 57](https://cloud.githubusercontent.com/assets/3098670/11335511/00e6a2c0-91dd-11e5-9a0b-784b04e3a407.png)

**Comment by eleftherioszisis** [comment]
The dendrogram is now inside NeuroM. You can use it on both trees and neurons. In case of neurons the soma representation appears as well as in the example dendrogram. On the contrary, the trees are now generated separately and joined together when plotted, thus the ugly triangles are now gone.

from neurom.ezy import load_neuron
from neurom.view import view

n = load_neuron(path)
view.dendrogram(n, show_diameters=True)

Please feel free to give more feedback in order to improve it!

**Comment by juanchopanza** [comment]
@wvangeit is there anything left to discuss in this issue? If not, I will close it.

**Comment by wvangeit** [comment]
Hi, 
The main points are solved. But still:
- We need units on the y-axis (maybe we don't even need an axis if we would have x/y scale bars)
- After calling 'dendrogram()' the figure window closes immediately if I don't put a pylab.show(). Maybe you can add an option as argument that enables/disables pylab.show() ?
(And a white background would also be nice, but I leave that up to you)

**Comment by juanchopanza** [comment]
Thanks for the information. Could you make separate issues for those two points?

**Comment by wvangeit** [comment]
Done
