### ISSUE TITLE
View of tree fails if tree has only one point if diameter = True option is selected

### ISSUE THREAD

**Issue by lidakanari** [BlueBrain/NeuroM#166]
This can be fixed with a try-except statement in the tree viewer.

**Comment by juanchopanza** [comment]
Note we will need a test morphology that shows this problem in order to test the solution. It can probably be built in place, but there has to be a test that would fail before a fix is applied.

**Comment by lidakanari** [comment]
Yes, I can generate a trivial morphology for this test. Ok, I have in mind a relevant test that fails now.
