### ISSUE TITLE
morph_check fails if no config file is provided.

### ISSUE THREAD

**Issue by jdcourcol** [BlueBrain/NeuroM#168]
As per the documentation:
```
morph_check some/data/path/morph_file.swc
```
when you do that, morph_check will fail at https://github.com/BlueBrain/NeuroM/blob/master/apps/morph_check#L144

because the config dict does not contain a 'neuron_checks' key.

may be there should be a default config when the file is not provided.

**Comment by juanchopanza** [comment]
Yes, there should have been a documented default. @eleftherioszisis can you look at this?

**Comment by eleftherioszisis** [comment]
Sure, I initialized it to an empty list. Is there a default set of tests that I should put instead?

**Comment by juanchopanza** [comment]
Whatever was being tested before you added the config file would be a reasonable starting point. We can re-evaluate it later.

**Comment by lidakanari** [comment]
Yes, I think a reasonable starting point for the set of default checks is:

Does the cell have a soma?
Does it have basals?
Does it have axons?
Does it have apicals?
Does it contain zero length sections?
Does it contain zero length segments?
Does it contain zero diameter segments? (or points instead?)

**Comment by eleftherioszisis** [comment]
So, if no config is provided, then the above will always be checked. Is that ok with everyone?

**Comment by juanchopanza** [comment]
Sounds fine to me.
