### ISSUE TITLE
duplicate point removal isn't really optional

### ISSUE THREAD

**Issue by juanchopanza** [BlueBrain/NeuroM#177]
The removal of duplicate points in HDF5 files is only optional deep inside the implementation code. It should be optional at high level. It isn't obvious how to implement this, but we could give the neuron loading functions some optional keyword arguments that are passed on to the readers.

See related issue #178:  point removal should be applicable to all file types, not just HDF5.

**Comment by lidakanari** [comment]
There is a conceptual problem here that has to do with the construction of the two formats. This is not a removal of zero length segments that would check if two consecutive points are the same and remove one of them (I think that's what you are referring to) . This function only checks the beginning of a section! Here is why this is a problem:

1) swc assumes that the points are actual points, so everything that is there and has an id is an independent point. 
2) h5 assumes (by construction) that points have to be duplicated in each section. In h5 the main objects are section not points.

**Comment by juanchopanza** [comment]
OK, so a first step would be to rename `remove_duplicates` to something more specific. But maybe it is OK to leave the functionality as is, with the option only used for testing and debugging purposes.

**Comment by lidakanari** [comment]
Agreed. The name is not very informative and is actually a bit misleading. I'm waiting for a better proposal :)

**Comment by juanchopanza** [comment]
Closing this as it comes from a misunderstanding.
