### ISSUE TITLE
Names remove_duplicates and H5.remove_duplicate_points are misleading

### ISSUE THREAD

**Issue by juanchopanza** [BlueBrain/NeuroM#179]
The names  `remove_duplicates` and `H5.remove_duplicate_points` suggest all duplicate points are removed. However the action taken is to remove identical consecutive points that are on adjacent section boundaries. We need names that reflect that. Suggestions:
- `no_section_boundary_duplicates` and `H5.remove_section_boundary_duplicates`

**Comment by lidakanari** [comment]
Do we still need to rename this one?

**Comment by juanchopanza** [comment]
I'm not sure, because the section tree doesn't need this kind of duplicate removal. So I think we can ignore this one, and when the point representation is finally removed, we can close it.

**Comment by lidakanari** [comment]
OK, thanks!
