### ISSUE TITLE
document check.morphology

### ISSUE THREAD

**Issue by jdcourcol** [BlueBrain/NeuroM#185]
Currently there is no documentation about these checks in: http://neurom.readthedocs.org/en/stable/definitions.html nor in latest

that would be appreciated.

**Comment by juanchopanza** [comment]
Agreed. I'll start a section on the documentation, then we can gradually add pieces.

**Comment by mgeplf** [comment]
There now exists:
http://neurom.readthedocs.io/en/stable/_neurom_build/neurom.check.neuron_checks.html#module-neurom.check.neuron_checks
and
http://neurom.readthedocs.io/en/stable/_neurom_build/neurom.check.structural_checks.html#module-neurom.check.structural_checks
