### ISSUE TITLE
Non consecutive IDs 

### ISSUE THREAD

**Issue by a1eko** [BlueBrain/NeuroM#191]
I get an error "Non consecutive IDs found in raw data" for SWC files created by Pneumatk software. The files are correct. SWC standard requires only increasing IDs, ie ID_parent < ID_child, but NeuroM raises exception if there is a gap between the parent ID and all its children. For example, in the file

    1 1 0.0 0.0 0.0 1.0 -1 
    3 3 1.0 0.0 0.0 0.1 1 
    4 3 2.0 0.0 0.0 0.1 3

NeuroM wants the dendrite to start with ID=2, not 3.

**Comment by juanchopanza** [comment]
We followed [this specification](http://research.mssm.edu/cnic/swc.html). In it, here is this:

    n T x y z R P
    n is an integer label that identifies the current point and increments by one
    from one line to the next.

Do you know of a different SWC "standard"? If so, a reference would be good.

**Comment by lidakanari** [comment]
Which *generally* agrees with the second swc format description I could find :)

http://www.neuronland.org/NLMorphologyConverter/MorphologyFormats/SWC/Spec.html

"integer value, *generally* continuous, ..."

**Comment by juanchopanza** [comment]
@lidakanari Do you think we should look into lift this restriction?

**Comment by lidakanari** [comment]
If the rest of the structure is well defined, we don't really need this constraint.

**Comment by a1eko** [comment]
I refer to neuromorpho.org (http://neuromorpho.org/myfaq.jsp, "What is SWC format?"): "The index for parent compartments are always less than child compartments." This follows original definition by Cannon et al, 1998 ( http://www.sciencedirect.com/science/article/pii/S0165027098000910). Thus the continuity requirement seems to be excessive. 
In fact, it is sufficient for IDs to be unique and define a tree. They don't need to be placed in increasing or any other order; they even don't need to be integers, actually.

**Comment by juanchopanza** [comment]
It required some changes to the code, but  hopefully pull request #192 fixes this.

**Comment by berthelm** [comment]
Hi Alexander:

I have taken this definition to be the one that specifies swc

http://research.mssm.edu/cnic/swc.html

and here the first one (or more) is the soma and has id 1, so the first child must have parent id 1 and given that ids have to increment by 1 it gives the restriction that ids must be consecutive integers.

This may mean there are competing definitions of “swc format”.

Julian





On 18 Dec 2015, at 17:30, Alexander Kozlov <notifications@github.com<mailto:notifications@github.com>> wrote:


I refer to neuromorpho.org<http://neuromorpho.org> (http://neuromorpho.org/myfaq.jsp, "What is SWC format?"): "The index for parent compartments are always less than child compartments." This follows original definition by Cannon et al, 1998 ( http://www.sciencedirect.com/science/article/pii/S0165027098000910). Thus the continuity requirement seems to be excessive.
In fact, it is sufficient for IDs to be unique and define a tree. They don't need to be placed in increasing or any other order; they even don't need to be integers, actually.
