### ISSUE TITLE
Access the individual neurites of a specific tree type (ex. basal dendrite)

### ISSUE THREAD

**Issue by chalimou** [BlueBrain/NeuroM#202]
Hi, 
for the validation of the basal ganglia I  have the following case: I need to examine a feature for each neurite depending on the TreeType. According to the results I keep a subset of the neurites for further analysis. I would like an easy way to access the basal trees one by one to analyse them separately.

Example:
Eleftherios did what I wanted the following way, but it seems too much for my python knowledge. Can this be done more easily?
```
def f(n):
    yield n

subset = nrn.neurite_loop(f, neurite_type=TreeType.basal_dendrite)
```

**Comment by eleftherioszisis** [comment]
For example it would be nice if it was possible to do:
```
subset = nrn.neurites(TreeType.basal_dendrite)
```
and obtain the subset of the neurites of choice for further analysis by the user.

**Comment by juanchopanza** [comment]
You can get a list with basal dendrites like this:

    basals = [b for b in nrn.neurites if b.type == TreeType.basal_dendrite]

It is a basic python pattern that is worth learning. For an iterable `x` (for example, a list), get the elements satisfying a condition:

    x = [1,2,3,4,5,6]
    y = [i for i in x if i < 4]

Here, `y` will contain `[1, 2, 3]`.

**Comment by eleftherioszisis** [comment]
I have to admit that this is much simpler :P

**Comment by mgeplf** [comment]
Just FYI, it's generally preferable style to use the list comprehensions, unless you have a predicate function already made, or you will be reusing the same predicate function.

I think this sums it up well:
http://stackoverflow.com/a/33610283

**Comment by chalimou** [comment]
Thank you very much for your fast help guys!! I'm happy with the suggestions :) Maybe a small neuroM course for dummies would be a good idea. We could invite people from the lab, too. I'll bring it to discussion when you come back from London. Nancy

**Comment by juanchopanza** [comment]
Sure, we could do that. I am in the process of simplifying the iterations over neurites, so I would wait until that is done before doing a course or tutorial.
