### ISSUE TITLE
Compute histogram of dendrite/axon density

### ISSUE THREAD

**Issue by lidakanari** [BlueBrain/NeuroM#203]
Dan reports that the user needs a function to get the density (length or volume) of a tree along a selected axis (given by a user-defined vector). The correct fraction of each segment should be represented in each bin. This requires a function to locate each segment in space, so that we can compute intersections between a segment and a plane.

**Comment by mgeplf** [comment]
I don't fully understand which density we are talking about.  Is there some literature that defines or explains the required feature?

**Comment by lidakanari** [comment]
I have a function for this implementation (and the short documentation for it). I will add an example in the corresponding folder asap (I just need to adjust the code to the new changes and I didn't have the time to do this). @mgeplf you can assign this to me.

**Comment by mgeplf** [comment]
Cool, thanks.  No rush, I'm just trying to cleanup up the issue list.

**Comment by asanin-epfl** [comment]
@lidakanari please feedback on the topic otherwise I will close the issue.
