### ISSUE TITLE
Adopt unified feature calculation output format (numpy arrays)

### ISSUE THREAD

**Issue by eleftherioszisis** [BlueBrain/NeuroM#206]
In order to avoid complex handling of the results of the feature functions I would like to suggest that we adopt a "duck" format for the output of the latter even for functions such as "get_n_segments".

For example, if all the outputs were numpy arrays (bonus if the are flattened as well) then a special handling would not be necessary and the stat extraction would apply the same for any feature function.

Do you guys think that this would cause any kind of conflict?

**Comment by lidakanari** [comment]
I think this is a reasonable suggestion. @juanchopanza @mgeplf any objections - alternative suggestions?

**Comment by juanchopanza** [comment]
I'm not sure I follow. Could you be more specific about which outputs you mean? Maybe if you add an example of something that would have to change it would be clearer.

**Comment by lidakanari** [comment]
I am not aware of anything that needs to change for the moment. This refers to the outputs of functions such as neuron.get_section_lengths(), neuron.get_...() as they are in ezy module. If those functions will become accessible through a different module this decision should be followed there as well.  
I guess this proposal refers to the following problem that might occur: when we extract multiple features and we need to handle them uniformly (for plots, statistics, etc) we need to have a uniform format for the output of those feature extraction functions. 

Example of where this will fail if we don't use a uniform format:
``` python
test_list = [0,1,2,3]
test_arr = np.array(test_list)

test_arr.min()
Out[15]: 0

 test_list.min()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-16-42e1cdc8fab9> in <module>()
----> 1 test.min()

AttributeError: 'list' object has no attribute 'min'
```

**Comment by eleftherioszisis** [comment]
On top of that some feature funcitons produce integers. e.g.:
```python
nrn.get_n_segments()
```
produces the result:
```
15
```
Instead it would be convenient if it produced the result
```
np.array([15])
```
In order to process all the feature results in the same way and not perform complex handling.

**Comment by juanchopanza** [comment]
I would propose that we map features to arbitrary feature extraction code, and use the mappings where applicable. So the problem of creating numpy arrays or a given dimension would be fixed in the feature extraction code. For example,

```python
features = { 'number_of_segments': lambda nrn: numpy.array([nrn.get_n_segments]), ...}
```

Or, even better,

```python
# works for neuron, neurom population, or collection of trees
features = { 'number_of_segments': lambda x: numpy.array([segments.count(x)]), ...}
```

**Comment by lidakanari** [comment]
Ok, I will optimize the code for the feature extraction once we get back :)
