### ISSUE TITLE
Units in dendrogram plots

### ISSUE THREAD

**Issue by wvangeit** [BlueBrain/NeuroM#209]
The dendrogram functionality of NeuroM should generate plots with units on the axes (or scale bars)

**Comment by eleftherioszisis** [comment]
Added the labels of the units which were in micrometers. You can also put custom labels or a title for example by passing as kwargs a dict with the following:

```python
kwargs['title'] = 'title'
kwargs['xlabel'] = 'favorite xlabel'
kwargs['ylabel'] = 'favorite ylabel'
```
