### ISSUE TITLE
Viewing dendrogram requires pylab.show() call

### ISSUE THREAD

**Issue by wvangeit** [BlueBrain/NeuroM#210]
After calling 'dendrogram()' the figure window closes immediately if I don't put a pylab.show(). Maybe you can add an option as argument that enables/disables pylab.show() ? (And a white background would also be nice, but I leave that up to you)

**Comment by lidakanari** [comment]
OK, I will fix this in the next commit.

**Comment by lidakanari** [comment]
About the background color, it can be chosen while you save the image. If white is what you need, just choose the option transparent=False (default is True and probably that's why it is not white :)
About the pylab.show, that is chosen by default now. To disable chose show_plot=False.

**Comment by juanchopanza** [comment]
Fixed by #219.
