### ISSUE TITLE
Give soma types meaningful names.

### ISSUE THREAD

**Issue by juanchopanza** [BlueBrain/NeuroM#234]
As suggested in #231. For example,

* `SomaA` -> `SomaSinglePoint`
* `SomaB` -> `SomaThreePoint`
* `SomaC` -> `SomaContour`

**Comment by mgeplf** [comment]
I think this is a good suggestion.

**Comment by mgeplf** [comment]
Did it here #236

**Comment by juanchopanza** [comment]
If you say "fixed by #236" this gets closed automatically.
