### ISSUE TITLE
get_features function

### ISSUE THREAD

**Issue by orena1** [BlueBrain/NeuroM#249]
Hi
In pneumatk there was a function named get_features, which:
```
Extract features from set of morphologies represented by PopulationSet and
output results inside .csv file.

The feature set can be set with the parameter 'featurefile',
otherwise it will be the default list of features described here.
```

It is possible to add this function to NeuroM (If it is already exist, I did not manage to find it)

Thanks.

**Comment by juanchopanza** [comment]
We can probably provide similar functionality with an application, but first the functionality has to be better defined. The description above is too vague. We would need to know, for example, what features are of interest and how these should be represented (summary stats, full distributions, anything else?)

**Comment by orena1** [comment]
I assume the default option of this function will be to extract all available features, of course one can define a list of features and then only those features will  be extracted.

> 
We would need to know, for example, what features are of interest and how these should be represented (summary stats, full distributions, anything else?)

I am not sure I understand the question correctly, in pneumatk you would get something like this:

```

#Neuron-Name	All Bif Mean Branch Length	All Density	All HV ratio	All Horizontal Range	All Max Branch Order	All Max Degree	All Max Local Bif Angle	All Max Path Length	All Max Radial Distance	All Max Remote Bif Angle	All Mean Local Bif Angle	All Mean Remote Bif Angle	All Mean Trunk Diameter	All Moment 1 (x)	All Moment 1 (y)	All Moment 1 (z)	All Moment 2 (x)	All Moment 2 (y)	All Moment 2 (z)	All Number	All Number Fragments	All Term Mean Branch Length	All Term Min Path Distance	All Tortuosity	All Total Branch	All Total Length	All Total Surface Area	All Total Volume	All Vertical Range	Apical Bif Mean Branch Length	Apical Density	Apical Direction	Apical HV ratio	Apical Horizontal Range	Apical Max Branch Order	Apical Max Degree	Apical Max Local Bif Angle	Apical Max Path Length	Apical Max Radial Distance	Apical Max Remote Bif Angle	Apical Mean Local Bif Angle	Apical Mean Remote Bif Angle	Apical Mean Trunk Diameter	Apical Moment 1 (x)	Apical Moment 1 (y)	Apical Moment 1 (z)	Apical Moment 2 (x)	Apical Moment 2 (y)	Apical Moment 2 (z)	Apical Number	Apical Number Fragments	Apical Point Dist To Soma	Apical Term Mean Branch Length	Apical Term Min Path Distance	Apical Tortuosity	Apical Total Branch	Apical Total Length	Apical Total Surface Area	Apical Tuft X length	Apical Tuft Y length	Apical Tuft Z length	Apical Vertical Range	Apical total Volume	Axon Bif Mean Branch Length	Axon Density	Axon HV ratio	Axon Horizontal Range	Axon Max Branch Order	Axon Max Degree	Axon Max Local Bif Angle	Axon Max Path Length	Axon Max Radial Distance	Axon Max Remote Bif Angle	Axon Mean Local Bif Angle	Axon Mean Remote Bif Angle	Axon Mean Trunk Diameter	Axon Moment 1 (x)	Axon Moment 1 (y)	Axon Moment 1 (z)	Axon Moment 2 (x)	Axon Moment 2 (y)	Axon Moment 2 (z)	Axon Number Fragments	Axon Term Mean Branch Length	Axon Term Min Path Distance	Axon Tortuosity	Axon Total Branch	Axon Total Length	Axon Total Surface Area	Axon Total Volume	Axon Vertical Range	Basal Bif Mean Branch Length	Basal Density	Basal HV ratio	Basal Horizontal Range	Basal Max Branch Order	Basal Max Degree	Basal Max Local Bif Angle	Basal Max Path Length	Basal Max Radial Distance	Basal Max Remote Bif Angle	Basal Mean Local Bif Angle	Basal Mean Remote Bif Angle	Basal Mean Trunk Diameter	Basal Moment 1 (x)	Basal Moment 1 (y)	Basal Moment 1 (z)	Basal Moment 2 (x)	Basal Moment 2 (y)	Basal Moment 2 (z)	Basal Number	Basal Number Fragments	Basal Term Mean Branch Length	Basal Term Min Path Distance	Basal Tortuosity	Basal Total Branch	Basal Total Length	Basal Total Surface Area	Basal Total Volume	Basal Vertical Range	Layer	Soma CSA	Type
C050600B1	28.544824737	7.87776949941811E-06	1.4071887419	1261.8430175781	25	509	175.9683173239	862.5485964912	673.2080336557	168.0317449609	45.4897427323	56.6457167326	1.7000000051	21.186052178	35.9116171153	-26.603623342	136.5801715747	123.1671927436	40.5145185082	7	5661	49.8814669604	28.1156426047	1.07518303	563	21070.8837275005	21652.8435821285	2411.8280812753	896.7119903564	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	28.1830440259	3.63560169502666E-06	1.4561586533	1261.8430175781	25	509	175.9683173239	862.5485964912	673.2080336557	168.0317449609	46.1280689688	57.2672945136	0.5500000119	26.6350753886	36.1204328814	-28.9600543521	150.0127419755	128.200469202	41.1141172619	4560	45.8352961377	139.780272165	1.077425237	509	17915.6356513183	15433.9060018339	1075.6303105291	866.5559997559	32.3736705966	7.44033091846879E-05	0.5418202769	254.1985015869	7	17	166.1161798921	317.9679740603	295.3431511905	142.9439959563	38.7341233952	50.0673518836	1.8916666706	-1.3821093483	35.0467670755	-16.8440180686	45.581468736	99.6451266055	36.3382148696	6	1101	83.840400651	28.1156426047	1.0528049247	54	3155.2480761822	6218.9375802946	1336.1977707462	469.1564941406	0	130.1473090843	0
C230300D1	52.9182231557	5.14173918314098E-06	1.1818852574	1077.0160064697	18	315	163.8886974963	875.4441647191	736.3963214179	157.9587124522	39.8321042542	54.5289928765	1.2112499997	95.7158201483	56.9725578566	19.3062747583	135.288358959	142.4340084725	56.4712179601	8	7869	80.822103562	110.1571767874	1.0591877959	344	22618.0454691785	21673.2681860085	2235.6526294189	911.2695159912	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	52.8869283003	2.74969737047476E-06	1.1818852574	1077.0160064697	18	315	163.8886974963	875.4441647191	736.3963214179	157.9587124522	41.0274261518	55.1890322065	0.8299999833	108.2281680219	58.325733673	23.7711894775	135.1791500511	146.8257236384	54.9709279343	6966	72.3789157638	181.5782052913	1.0599448732	315	19259.0965615316	15600.978315713	1078.4635258425	911.2695159912	53.3648860915	1.13407732227144E-05	1.0009843456	514.5575027466	4	13	38.0098594757	442.9034325211	350.111580588	100.9094656279	22.7716008069	45.10843153	1.2657142878	-0.8080063056	46.533772987	-15.1373530757	89.4774369171	101.8063765699	56.02357775	7	903	153.9963978133	110.1571767874	1.0503552279	29	3358.9489076469	6072.2898702956	1157.1891035764	514.0514984131	0	103.9842154323	0
C250500A-I4	42.9569919272	1.20515793272944E-05	0.5099220211	533.9339904785	13	159	172.2329714561	910.2678405932	856.8820372397	149.6945673977	45.5509308601	58.7975159433	1.6311111185	13.6165091261	-82.193365948	3.3792921348	73.0813189413	204.1479010789	32.3876138235	9	4454	72.3344702693	57.2575549331	1.0645580564	231	13323.5162985196	16040.8729890125	2272.709380926	1047.0894927979	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	49.782403198	3.27073238280067E-06	0.5221787069	533.9339904785	13	159	148.1531628077	910.2678405932	856.8820372397	149.6945673977	43.3857612637	63.2333195493	1.1100000143	20.2810573912	-111.0733710479	4.5296347218	81.7233888593	242.2695800492	37.3060142867	2889	64.6961149321	95.8277525653	1.0683693362	159	9122.1040530377	7750.5233134907	568.1963421899	1022.5119934082	26.1067578524	5.78041326292933E-05	0.8487828712	373.6859970093	5	27	172.2329714561	238.8274688515	223.0897157068	126.8815524097	50.8961933013	47.8466257909	1.6962500066	1.3137104436	-28.8806919969	1.2557523687	51.3602887502	76.6731882048	20.2294111277	8	1565	87.2292631768	57.2575549331	1.0560229368	72	4201.4122454819	8290.3496755219	1704.5130387361	440.2610015869	0	172.7683280304	0
C281199A-IN	28.6285291872	1.37016931271923E-05	0.6544837158	619.0575027466	16	219	174.2306044272	771.5083837262	764.2054638796	153.8095568653	42.3302910664	53.7167131945	1.4187499806	13.9607222995	-72.0178548796	-14.583525834	84.3321676548	144.6786321795	35.5610665889	8	2464	68.0617534149	70.4493166311	1.0644336255	286	13602.3998403672	15671.1701699795	2278.4697103841	945.8715133667	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	32.363239851	8.05146420612956E-06	0.7106414027	619.0575027466	16	219	174.2306044272	771.5083837262	764.2054638796	153.8095568653	44.1622601941	52.6180433954	1.1100000143	34.1962791074	-103.6458520634	-15.4083230354	100.9452904466	180.826141799	30.758057074	1350	52.7166775463	124.0391990199	1.0670741786	219	9097.8349639038	8198.0420632952	608.5809293276	871.1250152588	15.0590804421	5.15148296510065E-05	0.8837944171	317.6145019531	8	31	78.2665603218	233.414362473	220.3724482532	109.1070413074	35.674136569	57.7085467978	1.4628571187	-10.5617208699	-33.6894920445	-13.5839960119	47.7935366186	63.1802952841	40.6051472793	7	1114	109.5349314378	70.4493166311	1.0552545601	67	4504.5648764634	7473.1281066843	1669.8887810565	359.3759994507	0	235.7129232891	0

```

![image](https://cloud.githubusercontent.com/assets/8983713/12743319/dd84d392-c995-11e5-9819-0619856e2a18.png)


So for each neuron you get a single value for each feature (which can be mean, median, max.. depending in the feature)

This get feature function is very good for neuronal classification.

Thanks.

**Comment by juanchopanza** [comment]
> I am not sure I understand the question correctly, in pneumatk you would get something like this:

In general, you should not assume knowledge of `pneumatk` (not everyone knows that package), but rather concentrate on what the required features are. From the sample you provided, I can see some features we already implemented, and we routinely obtain those stats from populations of cells, so it wouldn't be too hard to provide them in CSV format.

> I assume the default option of this function will be to extract all available features, of course one can define a list of features and then only those features will be extracted.

"all available features" is a moving target, and some features don't make sense biologically, which is why I wouldn't provide something that writes "all features". But we can provide something that produces a set of features from a user defined list (with a reasonable default.) The assumption has to be that the user knows what they want, and that they don't want "all features" regardless of what they are.

**Comment by orena1** [comment]
> In general, you should not assume knowledge of pneumatk (not everyone knows that package)

I did not know that... 

> so it wouldn't be too hard to provide them in CSV format.

Great thanks!

> "all available features" is a moving target, and some features don't make sense biologically, which is why I wouldn't provide something that writes "all features"

What exactly do you mean in not making sense biologically, can you please give me an example? 

> But we can provide something that produces a set of features from a user defined list (with a reasonable default.) 

Sounds good, is there a place where I can see all the features that can be extracted? some kind of an available feature list, I did not mange to find one.

Thank you.

**Comment by eleftherioszisis** [comment]
You can access the available features of a Neuron via three ways. You can load a neuron:
```python
from neurom.ezy import load_neuron
n = load_neuron('path_to_neuron')
```
And then write a dot after n and tab completion to find all the possible functions on the object.

You can load the ezyNeuron object
```python
from neurom.ezy import Neuron
```
and then do Neuron. and tab completion to see the available functions.

Or finally you can check the code for ezy.Neuron where will you find all the available functions. In the following block you can see the available features in NeuroM for a neuron object:
```
get_section_path_distances
get_section_radial_distances
get_local_bifurcation_angles
get_segment_lengths
get_soma_radius
get_n_sections
get_soma_surface_area
get_n_sections_per_neurite
get_trunk_origin_radii
get_remote_bifurcation_angles
get_trunk_section_lengths
get_section_lengths
```

Can you please provide us with information concerning features that are important/standard for classification and that which they aren't currently implemented in NeuroM. This is a useful test case in order to expand NeuroM's features.

As far as the features extraction is concerned, there is the morph_stats application in the app folder in NeuroM which takes a directory as an input, loads the neurons, extracts basic stats (e.g. mean, median, std etc.) for all the available features and stores them in a json file. The features value extraction is applied on all the vailable neurite types (e.g. axon, basals, all together, etc.).

here's an example:

```
{
  "../test_data/valid_set/Neuron_2_branch_h5v1.h5":{
    "n_sections":{
      "axon":{
        "std":0.0,
        "max":21.0,
        "mean":21.0,
        "min":21.0
      },
      "all":{
        "std":0.0,
        "max":42.0,
        "mean":42.0,
        "min":42.0
      },
      "apical_dendrite":{
        "std":0.0,
        "max":0.0,
        "mean":0.0,
        "min":0.0
      },
      "basal_dendrite":{
        "std":0.0,
        "max":21.0,
        "mean":21.0,
        "min":21.0
      }
    },
    "n_sections_per_neurite":{
      "axon":{
        "std":0.0,
        "max":21.0,
        "mean":21.0,
        "min":21.0
      },
      "all":{
        "std":0.0,
        "max":21.0,
        "mean":21.0,
        "min":21.0
      },
      "apical_dendrite":{
        "std":0.0,
        "max":0.0,
        "mean":0.0,
        "median":0.0,
        "min":0.0
      },
      "basal_dendrite":{
        "std":0.0,
        "max":21.0,
        "mean":21.0,
        "min":21.0
      }
    },
    "n_neurites":{
      "axon":{
        "std":0.0,
        "max":1.0,
        "mean":1.0,
        "min":1.0
      },
      "all":{
        "std":0.0,
        "max":2.0,
        "mean":2.0,
        "min":2.0
      },
      "apical_dendrite":{
        "std":0.0,
        "max":0.0,
        "mean":0.0,
        "min":0.0
      },
      "basal_dendrite":{
        "std":0.0,
        "max":1.0,
        "mean":1.0,
        "min":1.0
      }
    },
    "section_lengths":{
      "axon":{
        "std":0.62964512578652809,
        "max":11.018460736176685,
        "mean":9.8957563531242734,
        "min":8.8606876664279284
      },
      "all":{
        "std":0.83094033536808998,
        "max":11.652508126101711,
        "mean":9.972243912384263,
        "min":7.8783088999327271
      },
      "apical_dendrite":{
        "std":0.0,
        "max":0.0,
        "mean":0.0,
        "median":0.0,
        "min":0.0
      },
      "basal_dendrite":{
        "std":0.98629103413416164,
        "max":11.652508126101711,
        "mean":10.048731471644253,
        "min":7.8783088999327271
      }
    },
    "remote_bifurcation_angles":{
      "axon":{
        "std":0.17403669351006709,
        "max":0.76361110419449474,
        "mean":0.49679320315916548,
        "min":0.1563263442516595
      },
      "all":{
        "std":0.18284044348284723,
        "max":0.76361110419449474,
        "mean":0.4054642958992874,
        "min":0.11609206923117805
      },
      "apical_dendrite":{
        "std":0.0,
        "max":0.0,
        "mean":0.0,
        "median":0.0,
        "min":0.0
      },
      "basal_dendrite":{
        "std":0.1410338479072476,
        "max":0.5809279378858544,
        "mean":0.31413538863940926,
        "min":0.11609206923117805
      }
    },
    "soma_surface_area":{
      "std":0.0,
      "max":0.12522988830410486,
      "mean":0.12522988830410486,
      "min":0.12522988830410486
    },
    "segment_lengths":{
      "axon":{
        "std":0.30243337609555004,
        "max":1.6540238959202642,
        "mean":0.99431044696463999,
        "min":0.29348590089725773
      },
      "all":{
        "std":0.30269031189512985,
        "max":1.6540238959202642,
        "mean":0.99960440171870912,
        "min":0.2012461179749811
      },
      "apical_dendrite":{
        "std":0.0,
        "max":0.0,
        "mean":0.0,
        "median":0.0,
        "min":0.0
      },
      "basal_dendrite":{
        "std":0.30285394219669853,
        "max":1.5630621606629709,
        "mean":1.0048731471644254,
        "min":0.2012461179749811
      }
    },
    "soma_radius":{
      "std":0.0,
      "max":0.099827240136257947,
      "mean":0.099827240136257947,
      "min":0.099827240136257947
    },
    "local_bifurcation_angles":{
      "axon":{
        "std":2.3229752363035459e-11,
        "max":2.094395102427058,
        "mean":2.0943951024045013,
        "min":2.0943951023404543
      },
      "all":{
        "std":2.1568688661970897e-11,
        "max":2.0943951024407186,
        "mean":2.0943951024045449,
        "min":2.0943951023404543
      },
      "apical_dendrite":{
        "std":0.0,
        "max":0.0,
        "mean":0.0,
        "median":0.0,
        "min":0.0
      },
      "basal_dendrite":{
        "std":1.9768447793667075e-11,
        "max":2.0943951024407186,
        "mean":2.0943951024045875,
        "min":2.094395102358753
      }
    }
  },...}
```
Is this what are you looking for?

**Comment by lidakanari** [comment]
I think that what is currently missing from the feature list that was provided in Pneumatk are spatial features, such as densities (horizontal, vertical, see issue  #203 ), sholl analysis (see  #180) and apical point definition, with all the features that can be derived from this. Please @orena1 add anything that I've missed.

**Comment by lidakanari** [comment]
Also, I think this list:

```
get_section_path_distances
get_section_radial_distances
get_local_bifurcation_angles
get_segment_lengths
get_soma_radius
get_n_sections
get_soma_surface_area
get_n_sections_per_neurite
get_trunk_origin_radii
get_remote_bifurcation_angles
get_trunk_section_lengths
get_section_lengths
```

is not exclusive, since it does not summarize all the features that can be extracted. For example, section branch orders or partition are not in the list, but can be computed using lower level functionality.

**Comment by orena1** [comment]
Thank you for the support!

> As far as the features extraction is concerned, there is the morph_stats application in the app folder in NeuroM which takes a directory as an input, loads the neurons, ...

That is great,.

> Can you please provide us with information concerning features that are important/standard for classification and that which they aren't currently implemented in NeuroM. This is a useful test case in order to expand NeuroM's features.


I talked with some of my lab members, and they said the most useful features for classification are: 

Total length of basal tree 
Total volume/ surface are of basal tree
number of basal/apical trees.
diameter of basal/apical trees.

Spacial point distribution and density projected on all 3 axes 
General orientation 
Sholl analysis 

The first chunk are already implemented right? the second chunk is the same as what @lidakanari mention.

Maybe something in the flavor of this:
http://bluebrain.github.io/eFEL/eFeatures.html
http://bluebrain.github.io/eFEL/efeature-documentation.pdf

can be useful.

Thanks.

**Comment by eleftherioszisis** [comment]
FYI there is now the features module which can be used to extract all the available features in NeuroM.

Example:
```python
from neurom.ezy import load_neuron
from neurom.core.types import TreeType
n = load_neuron('test_data/valid_set/Neuron.swc')

from neurom.features import NEURITEFEATURES, NEURONFEATURES

section_lengths = NEURITEFEATURES['section_lengths'](n, neurite_type=TreeType.all)
```

This two dictionaries provide an easy access to the neurite and neuron feature functions that reside in the same directory. You can check all the available features by calling the keys function:
```python
print NEURITEFEATURES.keys()
print NEURONFEATURES.keys()
```
Neurite features can be applied to neurites, a neuron or a population of neurons, while the neuron features only to a neuron or a population of neurons (they need more info from the neuron than just its neurites)

**Comment by juanchopanza** [comment]
@orena1 FYI, the documentation has [been updated to show all the available features](http://neurom.readthedocs.io/en/latest/_neurom_build/neurom.get.html#neurom.get). See also [some examples of usage](http://neurom.readthedocs.io/en/latest/_neurom_build/neurom.html). Note that this is from a snapshot of the git repository.  These latest changes will be released in version 0.1.1

**Comment by juanchopanza** [comment]
@orena1 The latest release of NeuroM has a [morph_stats](http://neurom.readthedocs.io/en/stable/morph_stats.html) application that allows you to extract various morphometrics into a JSON file. It is highly configurable and I think it could be a good substitute for the `get_features` function you mentioned. Please let me know if it is useful to you.

**Comment by juanchopanza** [comment]
@orena1  FYI, since #514 the `morph_stats` application can produce its output in CSV format.

**Comment by orena1** [comment]
Thanks, I will check the new function and tell you my impression.

**Comment by juanchopanza** [comment]
I will close this in the absence of any feedback. I think if anything is missing in `morph_stats`, it would make more sense to open a new issue specifically for that. Note that this can be re-opened if other maintainers deem it necessary.

**Comment by lidakanari** [comment]
Sure, I think it makes more sense to open specific issues for missing features, since the csv output is already implemented.
