### ISSUE TITLE
Yet Another Organization Discussion

### ISSUE THREAD

**Issue by eleftherioszisis** [BlueBrain/NeuroM#251]
Hello all,

once more I would like to propose a couple of stuff for the organization of NeuroM in a more intuitive way. I will just write down my ideas and we can discuss it over time. I would appreciate it if we can have a fruitful discussion upon these ideas.

First of all, I think it would be easier and tidier if we had a dedicated module for features where we can develop the latter without having to modify the neuron/population ezy objects. Regardless of the design of the model I think it would be better to have the minimum possible amount of code inside the core objects --the way it is right now-- and then remove entirely the ezy module. This way it will be clear for the user what are the main structures in the software and what are they for.

The connection between that module and the neuron/population objects can vary. It can be in an object oriented way, i.e. Neuron.features which set as an attribute upon initialization:

```python
class Neuron:
    def __init__(self,...):
        self.features = NeuronFeatures(self)

segment_lengths = nrn.features.segment_lengths(*args, **kwargs)
```
 in semi-functional way (maybe it is considered object-oriented, dunno):
```python
fs = NeuronFeatures(nrn)
fs.section_lengths(*args, **kwargs)
```
which can be alternatively implemented in a more general way and create feature objects regardless of the abstraction level through a factory class:
```python
fs = Features(object_with_features)
```
or in a completely functional way:
```python
fs = features(object_with_features, Features.segment_lengths)
```
It is important to stress here that in the last block of code in the features function one will not pass the function itself i.e. segments.foo, but an Enum for the feature. This is mainly the interface for the users in order to be able to see all the available features in a consistent way and not have to search for the specific function in the low or high levels of the code to extract what they need. 

What do you think?

**Comment by juanchopanza** [comment]
I agree with the de-coupling of the data types and the "features" functionality (it is what I have been trying to say from the beginning :-) ). The last proposal looks good to me. I had thought of a similar one with a string, but the enum has the advantage of failing early if the enum value name is miss-spelt, and of being listable and tab-completable in some interpreters. Still, I think most users will interact with an even higher level entry point, where they provide a list of features and get back a JSON, CSV, or whatever. But that can be built on top of this.

**Comment by lidakanari** [comment]
Totally in favor of the proposed decoupling and getting rid of the ezy confusion! I think the proposal to have a module for features (a pure analysis module) where the neuron object is passed on and the features are given by an enum is a very tidy way to collect all this functionality together. This will also make it easier for a user to access all the available features and write scripts to call them in a unified way without having to go through the implementation details.

**Comment by eleftherioszisis** [comment]
Ok, I think the features module is now populated and ready to be used.

There is only a small issue: ```functools.wraps``` decorator does propagate the docstring but not the function signature which leads in a generic signature ```func(obj, *args, **kwargs)``` which does reflect the function's signature.

The easiest way that I am aware of to fix this is to use the decorator module. May I add it in neurom's requirements? I am also open to other suggestions.

**Comment by juanchopanza** [comment]
I think `decorator` is fine. Any opinion on that @mgeplf ?

**Comment by mgeplf** [comment]
I haven't really been following this.

Decorator seems fine.

WRT enum: is the enum automatically generated from the function names or how does that work?  I'm not wild about having to look the enum up, and then have to look up the function to know what it does, but it's really up to you guys.

**Comment by juanchopanza** [comment]
Hi Mike,

I think we're dropping the enum because it turned out to be not very useful.

**Comment by juanchopanza** [comment]
@eleftherioszisis So, in conclusion, you can use the `decorator` module in future development.

**Comment by eleftherioszisis** [comment]
ok, thanks!

**Comment by mgeplf** [comment]
Good to know about the enum, I think that's a good decision.

**Comment by juanchopanza** [comment]
Is it OK to close this?

**Comment by eleftherioszisis** [comment]
Sure, the only reason I was leaving it open, was to suggest the cleaning of neurom after m30, but we don't need an issue for that. :P
