### ISSUE TITLE
Application for the validation of a neuron against a population

### ISSUE THREAD

**Issue by lidakanari** [BlueBrain/NeuroM#256]
We need an application similar to morph_check for the automatic validation of a morphology. An example use-case is:
```
morph_validate neuron1 population
```
which should result in:
```
Section lengths (test:ks-test, threshold:10%) : PASS
Section path distances (test:ks-test, threshold:10%) : FAIL
ALL: FAIL
```

**Comment by eleftherioszisis** [comment]
Maybe having also as an optional input the yaml configuration file with the selected features?

**Comment by lidakanari** [comment]
Of course! The idea is to reproduce morph_check but with a different type of tests that will represent actual validations.
