### ISSUE TITLE
no __version__ in neurom

### ISSUE THREAD

**Issue by orena1** [BlueBrain/NeuroM#268]
Hi,
there is no ```__version__``` in neurom
```python
In [30]: import neurom

In [31]: neurom.__version__
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-31-0c91c2a03994> in <module>()
----> 1 neurom.__version__

AttributeError: 'module' object has no attribute '__version__'```

**Comment by lidakanari** [comment]
Hi Oren. Are you running NeuroM from a virtual environment? Could you try the instructions from here: http://neurom.readthedocs.org/en/stable/install.html and let me know if it works for a virtual environment installation?

**Comment by orena1** [comment]
Hi Lida,
I am not using virtualenv, I tried to install virtualenv but it did not work
```python
oren.amsalem@bream ~ $ virtualenv --system-site-packages nrm 
New python executable in /home/ls/users/oren.amsalem/nrm/bin/python
ERROR: The executable /home/ls/users/oren.amsalem/nrm/bin/python is not functioning
ERROR: It thinks sys.prefix is u'/usr' (should be u'/home/ls/users/oren.amsalem/nrm')
ERROR: virtualenv is not compatible with this system or executable
```
So I can not test if it  ```neurom.__version__``` works in virtual environment

**Comment by lidakanari** [comment]
Ok, I think that what you want is equivalent to:

from neurom import version

But since I'm not an expert on the versioning issues I will let @juanchopanza take a look at this.

**Comment by juanchopanza** [comment]
`neurom` doesn't have a `__version__` attribute. You can check `neurom.version.VERSION`. I will add `neurom.__version__` for the next release.

**Comment by juanchopanza** [comment]
@orena1 FYI,[ `NeuroM 0.0.15`](https://pypi.python.org/pypi/neurom/0.0.15) has been released. It includes this change.

**Comment by orena1** [comment]
Great, 
Thanks.
