### ISSUE TITLE
Find apical point in a tree

### ISSUE THREAD

**Issue by lidakanari** [BlueBrain/NeuroM#271]
This property is needed for many tasks (synthesizer, morphology release, classification of neurons, validation). The best approximation so far is the function available in Pneumatk, but it still does not give 100% correct results. Could we include this functionality in NeuroM?

**Comment by eleftherioszisis** [comment]
Yes, I think that would be important to be included in NeuroM. If this algorithm is the best we can do to estimate this point by taking into account only the morphometrics of a cell (i.e. without electrical behavior), then we should use it.

**Comment by juanchopanza** [comment]
Do we have a clear description of an algorithm to do this, and that it means for results to be "correct" or not?

**Comment by lidakanari** [comment]
I could write up a scheme of the current algorithm that is used to find the apical point. The problem is we don't have a clear description of the definition of the apical point (from biology). So your second point is practically what we are missing.

**Comment by chalimou** [comment]
It is crucial for the validation of the apical dendrites of the pyramidal cells to be able to extract the morphometrics of the apical tuft and the obliques separately, like section lengths, bifurcation angles, path distances etc.

**Comment by mgeplf** [comment]
I have an example in this pull request:
https://github.com/BlueBrain/NeuroM/pull/636

Let me know if that helps.

**Comment by asanin-epfl** [comment]
Closing as the issue have been resolved via #636. See https://github.com/BlueBrain/morph-tool/blob/master/morph_tool/apical_point.py for details.
