### ISSUE TITLE
z-jump check

### ISSUE THREAD

**Issue by eleftherioszisis** [BlueBrain/NeuroM#272]
Another check that is important for morphologies, is the z-jump check.

In neurolucida, the reconstruction is of course in 3 dimensions but the user can only see in his/her screen a 2D slice of the 3D space. In order to navigate in the z-axis he/she has to roll the mouse scroll button. The z-jump takes place when the reconstructor thinks that he/she is at the correct height while tracking the neurite, but in reality he/she has gone deeper. Here's an example:
![z_jump](https://cloud.githubusercontent.com/assets/15011025/13175580/9a320190-d70b-11e5-95bd-a0b837b742d9.png)
This usually manifests on bifurcations where the spatial transition from parent to children might be tricky, but it can also happen on other places as it can be seen in the image. 

Currently, there is an algorithm in the repair tool to detect the z-jumps, thus we can either check this one first and either modify it to our needs or create another one which will be suitable for our data structures.

**Comment by juanchopanza** [comment]
@eleftherioszisis Does #461 cover this?

**Comment by juanchopanza** [comment]
I will assume it is covered.
