### ISSUE TITLE
mapping of sections/segments to neurom segments

### ISSUE THREAD

**Issue by dkeller9** [BlueBrain/NeuroM#276]
We need a mapping from our traditional BBP representation of sections and segments to NeuroM segments.

Traditionally, we have represented the neuron as sections and segments, and all the synapses in the column use this standard and reference section and segment. I would like to use NeuroM to extract synapse positions, but cannot because there is no mapping.

**Comment by lidakanari** [comment]
We have the notion of sections - segments in NeuroM. The main issue is that the sections are not sorted. That means that the same neuron represented with a different order of sections in the morphology file will result in two different objects in NeuroM. As a result, if you want to extract the ID of a section globally, there is no way to ensure that this will be consistent. The solution would be to apply some type of sorting on the sections before we generate the tree structure. This is a very important feature for comparison and the definition of the apical point!

**Comment by juanchopanza** [comment]
Wouldn't it be easier to do everything in terms of an indexing of points or segments, ignoring sections? It is easy to transform a (section_id, segment_id) pair into a unique segment_id, than build a section_id system in NeuroM.

**Comment by juanchopanza** [comment]
The new section tree representation could be better suited to this. However, before going forward, what is the "traditional BPP representation" and where is it specified? I am not sure what it would mean to "map" NeuroM sections and segments to that "representation".

**Comment by juanchopanza** [comment]
@dkeller9 I put this on hold until there is more clarity on the requirements. However, here is an example that lets you get sections and segments by ID, according to a mapping that matches what I understand to be the implied mapping used in some BBP tools. Note that this mapping is not yet specified.
See [examples/section_ids.py](https://github.com/BlueBrain/NeuroM/blob/master/examples/section_ids.py) added in #397.

**Comment by lidakanari** [comment]
That's still helpful as a first example. Thanks!

**Comment by mgeplf** [comment]
From what I can tell, the example code is still correct for the h5 files.
@dkeller9 can I close this?
