### ISSUE TITLE
NeuroM in ipython notebook with 'matplotlib inline' enabled

### ISSUE THREAD

**Issue by wvangeit** [BlueBrain/NeuroM#280]
It looks like the NeuroM morphology viewer function doesn't work well (unless it's intentional) in an ipython notebook when '%matplotlib inline' magic is used instead of '%matplotlib notebook'.
I have attached a screenshot of this notebook 
https://github.com/BlueBrain/BluePyOpt/blob/master/examples/l5pc/L5PC.ipynb
when it's run with 'matplotlib inline'

<img width="398" alt="screen shot 2016-03-09 at 16 00 19" src="https://cloud.githubusercontent.com/assets/3098670/13639274/621dfb06-e610-11e5-8593-12ac4e98e55a.png">

**Comment by eleftherioszisis** [comment]
I can confirm this bug and no, it is not intentional. However, I do not know what triggers it...

**Comment by wvangeit** [comment]
Do you know when this might be fixed ? We need this for a demo on March 30, and need to know in advance if we can use NeuroM. Otherwise we might have to switch to another tool for this visualization.
Thanks.

**Comment by berthelm** [comment]
Hi Werner,
I'll discuss it tomorrow when Juan is back,
CIao,

Julian

**Comment by juanchopanza** [comment]
If somebody who understands the problem, knows the desired behaviour, and understands the viewing code can provide a fix, I can make a release so that it can be used for M30.

**Comment by juanchopanza** [comment]
FYI, this fix is included in the newly released NeuroM 0.0.16

**Comment by wvangeit** [comment]
Thx !
