### ISSUE TITLE
Feature tortuosity in NeuroM

### ISSUE THREAD

**Issue by chalimou** [BlueBrain/NeuroM#281]
Tortuosity is defined as the ratio of the section path to the section radial distance and reflects the "curvature" of the neurite. It is an essential feature for the synthesis process and its validation, as well as the general evaluation of synthesised cells. I think it is useful to have it as a feature in order to avoid user errors.
The tortuosity can be computed since the features involved (section path and radial distances) already exist in NeuroM. But if and only if their values are in an one-to-one correspondence. Are they?

**Comment by juanchopanza** [comment]
Could you specify what you mean by "section path"? You can edit your post to add more information.

**Comment by chalimou** [comment]
The section path distance is the neurite length from soma to the end of the section. It is measured by the feature section_path_distances in NeuroM. The section radial distance is the euclidean distance from the soma to the end of the section given by section_radial_distances in NeuroM. If I can be sure that for a given cell the elements of the section_path_distances and section_radial_distances correspond one-to-one, that is for example, the 23rd element of the two lists refer to the same section, I can compute the ratios section_path_distances/section_radial_distances by element. This is the tortuosity by definition.

**Comment by juanchopanza** [comment]
Yes, the iteration order for section functions is the same, so you can take the ratio.

**Comment by chalimou** [comment]
great, thanks, the confirmation was what I needed.
nancy
