### ISSUE TITLE
Distance from all node to all nodes

### ISSUE THREAD

**Issue by boazmohar** [BlueBrain/NeuroM#282]
Hi,
I am a new user of the toolkit, and I want to get the distance matrix from all nodes to all nodes.
A Breadth-first search implementation would help or a way to change the tree root.
Do you know of another way?

Thanks,
Boaz

**Comment by juanchopanza** [comment]
Hi, 

I'm not sure I fully understand. Do you mean the euclidean distance between each point in a neuron? Also, how would the breadth first traversal and tree root changing help with this?

**Comment by boazmohar** [comment]
Hi,

Sorry for not being clear.
I want the minimal **path **distance between all nodes in the tree.
If I will do a BFS from each node I could build that matrix.
You have a function to get all the distances to the root, so if I will change the root, I could also build that matrix.

Boaz

**Comment by lidakanari** [comment]
Hi Boaz,

I am assuming that what you need is the shortest path distance within the paths defined by the tree structure. For a rooted tree, the minimal path distance is defined using the property of the root (so it would not be very efficient to modify it). The fastest way I can think of is to take the path towards the root for a pair of nodes and find the branching point at which they merge. From this you can extract the "shortest path distance".

Please let me know if this makes sense.

Lida

**Comment by juanchopanza** [comment]
Hi Boaz,

I'm not sure we will implement this functionality in `NeuroM`, but we may implement functionality that helps you achieve that end. But we'd need to know how exactly you define the distance between two arbitrary nodes in a neurite tree or cell (and also, are you talking about cells, or neurites?)

**Comment by boazmohar** [comment]
Hi,

I am talking about neurites, and defining the shortest path you could make by following point along the tree.
I implemented this by loading an swc file using NeuroM, creating a pandas DataFrame with three series: 
       1. Start node of each segment
       2. End node of each segment
       3. Segment length (weight)

I loaded it up with networkX that has this algorithm.
Here is the code for doing that (only for bifurcation points).

``` python
from neurom.core.tree import isection, val_iter
from neurom.io.utils import load_neuron
from neurom.analysis.morphmath import segment_length
import networkx as nx

nrn = load_neuron('cell1.swc')

SegIter = nrn.i_neurites(isection)
Start = pd.Series()
End = pd.Series()
for i, seg in enumerate(SegIter):
    Start.set_value(i, seg[0].value[6].astype(int)) # first point of the segment
    End.set_value(i, seg[-1].value[6].astype(int)) # last point of the segment

SegIter = nrn.i_neurites(isection)
Length = pd.Series()
for i, seg in enumerate(val_iter(SegIter)):
    Length.set_value(i, np.sum(segment_length(seg))) # segment length

Graph = pd.DataFrame({  'Start': Start,
                        'End':   End,
                        'weight': Length})

G=nx.from_pandas_dataframe(Graph, 'Start', 'End', ['weight'])

pathLen = nx.shortest_path_length(G,weight='weight')

 # length from cell body
pathLen[1.0]
out: {1.0: 0,
 3.0: 5.0251467640259015,
 4.0: 9.5986137202856803,
 5.0: 14.041686980991598,
 7.0: 21.520430190916645,
 11.0: 26.466570099977055,
...
 # length from another point on the tree:
pathLen[11.0]
out: {1.0: 26.466570099977051,
 3.0: 21.44142333595115,
 4.0: 16.867956379691371,
 5.0: 12.424883118985456,
 7.0: 4.9461399090604088,
 11.0: 0,
 12.0: 5.0195716948759701,
 14.0: 10.025588075192742,
...
```
