### ISSUE TITLE
Feature to extract coordinates of all segments of a neurite

### ISSUE THREAD

**Issue by lidakanari** [BlueBrain/NeuroM#288]
This feature is needed for the density plots and to simplify the computation of more complex measurements. It should be something like:

NEURITEFEATURES["segment_x_coordinates"] should return a list of all the x coordinates of a structure as the mean (x_parent + x_child)/2 of each segment in this structure

**Comment by eleftherioszisis** [comment]
In case you are interested, you can use something similar to the func below:

```python 
def segment_center(seg, projections):
    if projections in (0, 1, 2):
         return (seg[0][projections] + seg[1][projections]) / 2.
    else:
        s = slice(min(projections), max(projections) + 1)
        return (seg[0][s] + seg[1][s]) / 2
```

and then call it:

```
segment_center(seg, COLS.X)
segment_center(seg, (COLS.X, COLS.Y, COLS.Z))
etc
```

I just leave it here. :P

**Comment by lidakanari** [comment]
Maybe this is optimal for the intermediate steps but I would like to avoid complications at the feature exposed to the user. So in the NEURITEFEATURES I would prefer to have the simplest implementation. In any case I'll let @juanchopanza decide which way is best.
