### ISSUE TITLE
Bug in Branch order definition

### ISSUE THREAD

**Issue by lidakanari** [BlueBrain/NeuroM#295]
I found a reference to the definition of branch order : http://www.sciencedirect.com/science/article/pii/0165027086901160

![screenshot from 2016-04-13 11 52 45](https://cloud.githubusercontent.com/assets/14071443/14489654/b87e1fde-016e-11e6-8b86-d10771520c25.png)

According to this paper, which is used as reference in Neurolucida as well, branch order starts from 0. In our implementation, branch order starts from -1 at the root. Example:

```python
n = ezy.load_neuron('./NeuroM/test_data/swc/Neuron.swc')

nf['section_branch_orders'](n)

Out[4]: array([-1.,  0.,  0.,  1.,  1.,  2.,  2.,  3.,  3.,  4.,  4.,  5.,  5.,
        6.,  6.,  7.,  7.,  8.,  8.,  9.,  9., -1.,  0.,  0.,  1.,  1.,
        2.,  2.,  3.,  3.,  4.,  4.,  5.,  5.,  6.,  6.,  7.,  7.,  8.,
        8.,  9.,  9., -1.,  0.,  0.,  1.,  1.,  2.,  2.,  3.,  3.,  4.,
        4.,  5.,  5.,  6.,  6.,  7.,  7.,  8.,  8.,  9.,  9., -1.,  0.,
        0.,  1.,  1.,  2.,  2.,  3.,  3.,  4.,  4.,  5.,  5.,  6.,  6.,
        7.,  7.,  8.,  8.,  9.,  9.])
```
It will be better to be consistent with this definition and to add the reference to the implementation of the code.

**Comment by juanchopanza** [comment]
@lidakanari Do you want to make the necessary changes, or shall I? I have time to do it right now.

**Comment by lidakanari** [comment]
Please go ahead cause I have a course now.
