### ISSUE TITLE
matplotlib get  function shadowing

### ISSUE THREAD

**Issue by eleftherioszisis** [BlueBrain/NeuroM#315]
I noticed that when ```ipython``` is loaded with ```--pylab``` flag, a function ```get``` exists in the global namespace from matplotlib:

```
 <function matplotlib.artist.getp>
```

Using get function from features replaces this one. I assume that this is an alias function for ```getp```, thus it is probably not called directly from matplotlib, but I think that we should have this in mind in case weird stuff start happening.

**Comment by juanchopanza** [comment]
That's not the only thing that will get shadowed. Basically, anyone using `--pylab` does it at their own risk.
