### ISSUE TITLE
Discrepancy between h5 and neurolicuda ASCII data

### ISSUE THREAD

**Issue by juanchopanza** [BlueBrain/NeuroM#324]
Related to #322. 

Two files supposedly representing the same neurons in different formats show small differences in some of the morphometrics obtained with `neurom`.

It is not clear whether this is a problem with the data or an artifact of `neurom`'s data readers, so it might require some detailed investigation of the data itself, and / or the production of `h5` and `neurolucida` samples that we can be completely sure are equivalent. 

This is an example highlighting the issue:

``` python
h5 number of sections: 562.0
nl number of sections: 563.0

h5 number of segments: 5659.0
nl number of segments: 6216.0

h5 total neurite surface area: 22321.4425649
nl total neurite surface area: 22186.5760705

h5 total neurite volume: 2533.15174575
nl total neurite volume: 2423.22948318

h5 total neurite length: 21075.2318211
nl total neurite length: 21077.0057435
```

This is the code I used:

``` python
import numpy as np
from neurom import ezy

nrn_h5 = ezy.load_neuron('C050600B1.h5')
nrn_asc = ezy.load_neuron('C050600B1.asc')

print 'h5 number of sections: %s' % ezy.get('number_of_sections', nrn_h5)[0]
print 'nl number of sections: %s\n' % ezy.get('number_of_sections', nrn_asc)[0]
print 'h5 number of segments: %s' % ezy.get('number_of_segments', nrn_h5)[0]
print 'nl number of segments: %s\n' % ezy.get('number_of_segments', nrn_asc)[0]
print 'h5 total neurite surface area: %s' % np.sum(ezy.get('section_areas', nrn_h5))
print 'nl total neurite surface area: %s\n' % np.sum(ezy.get('section_areas', nrn_asc))
print 'h5 total neurite volume: %s' % np.sum(ezy.get('section_volumes', nrn_h5))
print 'nl total neurite volume: %s\n' % np.sum(ezy.get('section_volumes', nrn_asc))
print 'h5 total neurite length: %s' % np.sum(ezy.get('section_lengths', nrn_h5))
print 'nl total neurite length: %s\n' % np.sum(ezy.get('section_lengths', nrn_asc))
```

The sample files can be found [here](https://github.com/BlueBrain/NeuroM/files/248269/Morphs.zip)

**Comment by mgeplf** [comment]
are non calculated values the same? segment/section count, etc?

**Comment by mgeplf** [comment]
Looks like the precision is stored differently:
* in asc: it looks like %0.2f
* in h5, that's expanded to much longer floats

**Comment by juanchopanza** [comment]
@mgeplf Good catches. See my edit re. counts. The numbers of both sections and segments are incompatible.

**Comment by mgeplf** [comment]
That's pretty suspicious too.

It looks like the .h5 version was recentered, so that might also impact things.  However, the mismatch between counts is the most likely cause, imo.

**Comment by mgeplf** [comment]
Can you say which type has the extra segment/sections?

**Comment by lidakanari** [comment]
The precision issue has to do with the conversion. I noticed before that Brion is adding some more decimal numbers after the initial value!

**Comment by mgeplf** [comment]
The asc -> h5 conversion is handled by NEURON + hoc code.

It looks like offsets by: 
`all points will be corrected by off=(-8.3035714 , -5.915 , -6.8699999 )`

**Comment by mgeplf** [comment]
It's weird that the number of section is larger in asc than in h5.  I can't think of a place where the asc reader would be adding sections.

**Comment by juanchopanza** [comment]
@mgeplf about the types (removing types with zero segments):

```
Neurite Type: NeuriteType.axon

h5 number of sections: 508.0
nl number of sections: 509.0
h5 number of segments: 4557.0
nl number of segments: 5066.0

Neurite Type: NeuriteType.basal_dendrite

h5 number of sections: 54.0
nl number of sections: 54.0
h5 number of segments: 1102.0
nl number of segments: 1150.0

Neurite Type: NeuriteType.all

h5 number of sections: 562.0
nl number of sections: 563.0
h5 number of segments: 5659.0
nl number of segments: 6216.0
```

**Comment by mgeplf** [comment]
(5066 - 4557) = 509, so it looks like the `nl` has one extra segment per section, and one extra section on the axon.

1150 - 1102 = 48.  Are there, by any chance, 6 basal dendrites?

**Comment by lidakanari** [comment]
Could it be that you are not removing the duplicate points at the beginning of each section?

**Comment by juanchopanza** [comment]
@mgeplf One axon, 6 basal dendrites.

```
for n in nrn_h5.neurites:
    print n.type
```

@lidakanari That seems to be at least part of the problem. Switching duplicate removal in h5, I get very similar numbers between h5 and NL. There is still one extra axon section.

**Comment by juanchopanza** [comment]
See #325, where I added duplicate removal. The agreement is much better, although there is still an extra axon segment and section.

```
h5 number of sections: 562.0
nl number of sections: 563.0

h5 number of segments: 5659.0
nl number of segments: 5660.0

h5 total neurite surface area: 22321.4425649
nl total neurite surface area: 22323.0028735

h5 total neurite volume: 2533.15174575
nl total neurite volume: 2533.26097061

h5 total neurite length: 21075.2318211
nl total neurite length: 21077.0057435
```

**Comment by juanchopanza** [comment]
See related PR: #360.

**Comment by mgeplf** [comment]
It appears that what is happening is that the an extra point is added to a section to connect it to its parent at:
https://github.com/BlueBrain/NeuroM/blob/master/neurom/io/datawrapper.py#L145

I will have to look at the best way to fix that, because it's not necessary for the ASCII reader.

**Comment by juanchopanza** [comment]
The best solution would be to extract the sections directly in the NL reader, instead of using `_extract_sections`.

**Comment by mgeplf** [comment]
I will have to look into that, thanks for the suggestion.

**Comment by juanchopanza** [comment]
@mgeplf Wait, it isn't clear at all that SWC files come with the duplicate point at the beginning of (non-trunk) sections. We used to think yes, then we looked at files from neuromorpho.org and the conclusion was no. BBP files coming from out tool chains may have these. But these are an internal subset of NL .asc files.

**Comment by lidakanari** [comment]
I agree with @juanchopanza : the SWC files do not have duplicate points by definition. The same is True for most of the  NL saved ascii files. The duplicate points are included in BBP internal files. However, this should not influence the results if the removal of duplicate points is performed correctly.

**Comment by juanchopanza** [comment]
@lidakanari From what I saw, the BBP tools introduces "duplicate" points with a different radius (following some unspecified algorithm of course :-) ), so adding them / removing them adds / removes information.

**Comment by lidakanari** [comment]
Aw, I see... Sure, if there is a change in the diameters, that will have a significant effect on the extracted measurements. Also, from my observations there are numerical errors introduced during conversion with Brion. The coordinates given with a few decimal places in the original file are converted into coordinates of 16 decimal places, with randomly larger absolute values. So we end up with consistently different values for the affected features (which are just numerically different of course). For the following example the effect might not be that obvious, but if the initial data are represented with only 2-4 decimal places the effect is much larger...

```
Original:
0.552924677558             -0.75349234549              0.903518151208
Modified:
0.5529246926307678	-0.7534923553466797	0.9035181403160095
```

**Comment by mgeplf** [comment]
That's because `0.552924677558` can't be represented exactly in a float32, and the 'modified' one is what is actually stored internally.  It's not a random number, as it's (depending on the library) the closest float32 to the original number.

That's a separate issue from duplicate points having different radii, which I will have to track down an example of to know why it's being generated.

**Comment by juanchopanza** [comment]
Sorry if I caused confusion, but I meant "NL .asc" when I said "SWC" earlier.

**Comment by asanin-epfl** [comment]
Closing as the issue was solved. Additionally in NeuroM v2, the reading is on MorphIO.
