### ISSUE TITLE
Minor Issue with Soma Type

### ISSUE THREAD

**Issue by eleftherioszisis** [BlueBrain/NeuroM#338]
In the ```SingleSomaContour``` in ```neurom/core/neuron.py``` there is a small inconsistency where the center is returned as a list, while in the other types as an array. Armando discovered this while trying to load cells of different soma types.

``` python
return list(np.mean(points[:, :COLS.R], axis=0))
```
@juanchopanza Can you change this into a numpy array in a next commit? Thanks!

**Comment by juanchopanza** [comment]
Specifically what code had an issue with this? Could you post a self contained, minimal example that reproduces this "issue" (that should be standard when reporting this type of issues.)

**Comment by eleftherioszisis** [comment]
I think it is evident that in one case the center will be returned as a list and in the other as a numpy array.

You can try loading the hippocampal neurons that have a contour-like soma and one from test_data.

**Comment by juanchopanza** [comment]
No, you need to provide a working example showing this is an issue.

**Comment by eleftherioszisis** [comment]
I don't understand. You have the same member variable (center) returned as a different type of data structure depending on the type of the neuron soma during the loading.

If you want for example to take the mean of the somata positions and some of the neurons represent them as lists while others as numpy arrays, then this will fail.

**Comment by juanchopanza** [comment]
You're reporting an issue, so you need to provide the example that shows there is a issue. I can't assume that returning different types is an issue without proof, and there is nothing in the documentation that specifies that the center is represented as a numpy array anyway.

**Comment by eleftherioszisis** [comment]
The example is the code itself. You have the ```BaseSoma``` that returns the center as a numpy array, the ```SomaSinglePoint``` and the ```SomaThreePoint``` that inherit from it and thus return numpy arrays as well.

Then you have the ```SomaSimpleContour``` that inherits from ```BaseSoma```, overrides the center method and returns a list instead (which can just be removed as it converts the numpy array that is returned from the np.mean to a list).

**Comment by juanchopanza** [comment]
Yes, but you have failed to show why that is a problem. If you don't have a test that fails because of this, then there is no issue.

**Comment by eleftherioszisis** [comment]
Nevermind. Apparently it's not as trivial as I thought.

I will fix this and provide with the respective "proof" when I have the time. There is no point behind further arguing about this.

**Comment by juanchopanza** [comment]
That's fine. Bear in mind that if there really is code out there that relies in these things being numpy arrays instead of lists, we have to decide if this is to be guaranteed by the soma classes, and add tests that check that this is the case. Currently, there is no such promise.

**Comment by eleftherioszisis** [comment]
Agreed. In any case, however, I think it would be better if these soma type classes returned one type (either arrays or lists, not depending on the type of the soma).

**Comment by juanchopanza** [comment]
Probably "fixed" in #398, if there was a problem to fix.
