### ISSUE TITLE
Unused/missing optional parameters docstrings of neurom.view funtions

### ISSUE THREAD

**Issue by eleftherioszisis** [BlueBrain/NeuroM#339]
The options that are documented in the docstring of functions in the view module (e.g. ```view.neuron```, ```view.neuron3d``` etc) need to be updated in order to reflect the actual options that are used in ```view.common.plot_style```.

More specifically, in ```view.neuron``` it is mentioned that ```limits``` key argument should be used to specify the limits of the plot, while in reality ```xlim```, ```ylim```, ```zlim``` options are used (these options propagate into ```view.common.plot_style```).

**Comment by juanchopanza** [comment]
Could you be more specific? There's no `view.plot_style` in `neurom`. If you mean `neurom.view.common.plot_style`, which part of the docstring are you referring to?

In general, we need more precision when reporting issues, no matter how minor.

**Comment by eleftherioszisis** [comment]
Yes, sorry for the shortness of the issue.

Basically, the docstring in ```view.neuron``` says that one has to use the ```limits``` key argument to pass the limits of the axes. This key argument should propagate through ```view.neuron``` to ```view.common.plot_style```. This is not happening because ```plot_style``` uses the key arguments ```xlim```, ```ylim``` and ```zlim``` for the respective limits and not ```limits``` option itself.

In other words, the ```view.neuron``` docstring needs updating in order to reflect the actual options that can be passed in the function (i.e. that ```xlim```, ```ylim```, ```zlim``` are used to limit the axes, not the option ```limits```).

**Comment by juanchopanza** [comment]
OK, thanks for clarifying. Do you think you can edit the initial issue description so that people landing here can immediately see what it is about?

Maybe @lidakanari can have a look at this? It is all too complicated for me.

**Comment by lidakanari** [comment]
Yes, it's just a matter of documentation, since it has not been updated to the new version (updated options). I can take care of this, if it's not urgent!

**Comment by eleftherioszisis** [comment]
Edited the initial issue for clarity.

**Comment by juanchopanza** [comment]
A bigger issue is, do we really need all of that plotting code? It seems over-complicated considering the limited plotting needs or `neurom` . I can understand that we may want some dedicated code to plot neurons, dendrograms and eventually scholl diagrams, but do we need all the code that is in `neurom.view` for that?

**Comment by juanchopanza** [comment]
Could somebody take care of this, or provide me with the required doc strings so I can put it in? It already caused me some confusion today!

**Comment by juanchopanza** [comment]
As a related note, could we remove the `no_xlim` etc. fields? I don't see a technical need for them and they make the interface confusing.

**Comment by lidakanari** [comment]
This issue is about the documentation. As I said I am planning to fix the plotting issue (along with some other ones) after the 1rst of July. I don't think you should start removing functionality if you are not one of the main users of the plotting. The set of options was formed after months of discussions and it took me a while to satisfy different peoples needs. So, changing those options arbitrarily (if they are not breaking something) would not be optimal, as they would break many user's code.

**Comment by juanchopanza** [comment]
Just a suggestion for the doc strings: if all the `plot_style` parameters are valid for all plotting functions that call `plot_style`, it might be easier to define a string for those parameters, and append it to the doc strings of `plot_style` as well its clients in `neurom.view.view`.

```
# neuron/view/common.py
PLOT_STYLE_PARAMS = "....."
```

then
```
# neurom/view/view.py
neuron.__doc__ += common.PLOT_STYLE_PARAMS
```

and so on

**Comment by lidakanari** [comment]
Yes, that would certainly be a good idea and it will minimize the duplication!

**Comment by juanchopanza** [comment]
I clarified the issue title, which was quite vague.
