### ISSUE TITLE
Change definition of "number_of_sections"  of populations in get (of both ezy and fst modules)

### ISSUE THREAD

**Issue by lidakanari** [BlueBrain/NeuroM#364]
The "number_of_sections" should return a list of the total number of 
sections per *neuron*. Currently it adds up all the sections of the population. 
Here is an example:

```python
from neurom import fst
pop = fst.load_population('./test_data/valid_set/')
fst.get('number_of_sections', pop)

Out: array([336])
```

The number of neurons in the population is 5:
```python
len(pop.neurons)
Out: 5

```
So the correct result would be:

```python
Out: array([42],  [42],  [84],  [84], [84])
```

**Comment by juanchopanza** [comment]
That probably makes more sense. Whatever it does, it should be documented clearly. i.e. the behaviour here would be different for populations and single neurons. So we'd need to document what it does in either case.

**Comment by juanchopanza** [comment]
Maybe it would be better to specify clearly what each of the "feature" functions should return, both for single neurons and for populations.

**Comment by lidakanari** [comment]
Yes, sorry.. I though it was common sense!

The feature of "number_of_sections" should return:
- one number which is the number of all the sections of the neuron, if the input is a single neuron
- a list which contains one number **per** neuron, which is the number of all the sections of the neuron, if the input is a population

The same goes for the "total_length" or other total measurements. 
- one number which is the sum of all the section lengths of the neuron, if the input is a single neuron
- a list which contains one number **per** neuron, which is the sum of all the section lengths of the neuron, if the input is a population

Is this a little bit more clear?

**Comment by juanchopanza** [comment]
@lidakanari That is fine, thanks. @eleftherioszisis I think you implemented the "feture getters", right? If so, did you have a reason to implement the current functionality, or is it OK to change it?

**Comment by lidakanari** [comment]
@eleftherioszisis Also, I am not sure if it should be a list or a np.array (please confirm so that we make all the features consistent )!

**Comment by eleftherioszisis** [comment]
@juanchopanza Yes, indeed I implemented them. I didn't have any particular reasons for the total numbers due to not knowing what was needed. I believe that the per neuron numbers are much more useful for analysis, and in fact I needed per neuron total numbers as well for astrocytes, which I did manually. :P

All the features I implemented in the features module returned iterators that were converted into numpy arrays.

**Comment by juanchopanza** [comment]
OK, thanks for the information. I can start working on this next week.

**Comment by juanchopanza** [comment]
BTW, shouldn't the output be

```python
array([42,  42,  84,  84, 84])
```
I can't see a reason for the inner arrays.

**Comment by lidakanari** [comment]
Yes, you are right :) That's what I got from my quick (and dirty) implementation, so your proposal is the correct one.

**Comment by juanchopanza** [comment]
@lidakanari @eleftherioszisis I will take care of `fst`. But for that I need to know exactly what features this should apply to.

**Comment by juanchopanza** [comment]
`fst` was taken care of in #368. Someone else can do `ezy`.
