### ISSUE TITLE
Segment radii are inconsistnet between the 'fst' and the ezy modules.

### ISSUE THREAD

**Issue by lidakanari** [BlueBrain/NeuroM#366]
I noticed a peculiar inconsistency between radii of the fst module and the ezy module. However, since segment_radii is not available in the fst module, it is not possible to test it with the same function. Here is a (not so proper) example for this:

```python
from neurom import ezy
from neurom import fst
import numpy as np

n = ezy.load_neuron('./test_data/neurolucida/sample.asc')
n1 = fst.load_neuron('./test_data/neurolucida/sample.asc')

```

Note that those cells have only one axon. 

```python
for itr, tr in enumerate(n.neurites):
    print itr, tr.type
   ....:     
0 NeuriteType.axon
1 NeuriteType.basal_dendrite
2 NeuriteType.basal_dendrite
3 NeuriteType.apical_dendrite

for itr, tr in enumerate(n1.neurites):
    print itr, tr.type
   ....:     
0 NeuriteType.axon
1 NeuriteType.basal_dendrite
2 NeuriteType.basal_dendrite
3 NeuriteType.apical_dendrite


```

Then by computing the radii of the segments I cannot match the axon initial section:

```python
# Get the fst-neuron axon
tr1 = n1.neurites[0]
# Confirm that this is the axon once again
tr1.type
Out: <NeuriteType.axon: 3>

# Initial section of the fst-tree
np.transpose(tr1.value)[3] # hack to get the radii of the first section
Out: 
array([ 0.85351288,  0.72855526,  0.54222909,  0.15834133,  0.74971031,
        0.42103903,  0.18778701,  0.23702312,  0.64729631,  0.30823704,
        0.79074297])

# Initial section of the ezy-tree
ezy.get('segment_radii', n, neurite_type=ezy.NeuriteType.axon)[:11]
Out: 
array([ 0.79103407,  0.63539217,  0.35028521,  0.45402582,  0.58537467,
        0.30441302,  0.21240506,  0.44215972,  0.47776668,  0.54949001,
        0.80588855])
```

It seems like something is wrong, but it is not possible to track this down without the same functionality available for the two types of neurons.

**Comment by juanchopanza** [comment]
Sorry, this is too confusing. I can't figure out what problem you're reporting here. What quantity are you trying to compare?

**Comment by lidakanari** [comment]
Yes, sorry about this. I think once we have the segment_radii for the fst module it will be easier to compare them.

I want to extract the distribution of segment radii. In the ezy module it is easy, since I can extract them from the NEURITEFEATURES. In the fst module there is not trivila way to do so. If you can propose one I will run the same analysis to compare the radii in the ezy and fst representations. 

I will try to find an easier example to illustrate this issue.

**Comment by juanchopanza** [comment]
I think it is better to close this and open a new ticket where a single issue that is presented clearly and unambiguously.

**Comment by lidakanari** [comment]
OK. I am closing it and when I have time I will try to make this into a proper issue. It would help if we can have the segment_radii feature implemented in fst if it is possible.

**Comment by juanchopanza** [comment]
The main issue is that the new stuff isn't as flexible as the old. It is easy to add new segment features, but the implementation won't be very efficient. So I first want to see if I can improve that. In the mean time, I can post an inefficient example here.

**Comment by lidakanari** [comment]
Yes, that would do since I will only use it to test the results (so I don't really need efficiency).

**Comment by juanchopanza** [comment]
@lidakanari Done, see example.
