### ISSUE TITLE
New feature: tortuosity

### ISSUE THREAD

**Issue by lidakanari** [BlueBrain/NeuroM#375]
It would be useful for validations to add the section_tortuosity feature at the "get" level for the next release. 

Definition of tortuosity can be found here (http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3928584/):

"Also, the distance metric (DM) tortuosity (a dimensionless number) provides a ratio between the actual path length `(correction: this should be section length)` of a meandering curve (i.e. along segments) and the linear distance between endpoints (radial distance)"

Neuroanatomical Tract-Tracing: Molecules, Neurons, and Systems, by Laszlo Zaborszky, Floris G. Wouterlood, José Luis Lanciego

> The dendritic tortuosity gives a ratio between the actual length of a dendritic segment (our section) and the distance between its endpoints

**Comment by juanchopanza** [comment]
If this is simply the section path length divided by the end-to-end distance, then I can add if to `fst.get`. Will that suffice, or do we also need it in `ezy.get`?

**Comment by lidakanari** [comment]
Yes, it is the path distance of a section divided by the radial distance of the same section. I think it will be sufficient to be added to ```fst``` unless the ```ezy.get``` will not be deprecated any time soon.
