### ISSUE TITLE
Inconsistencies between ezy and fst

### ISSUE THREAD

**Issue by lidakanari** [BlueBrain/NeuroM#383]
Example of disordered data [test_data.zip](https://github.com/BlueBrain/NeuroM/files/318302/test_data.zip). The two files should be equivalent (the only difference is the order in which the points appear in the file):

```python
from neurom import ezy
from neurom import fst

n = ezy.load_neuron('sample.swc')
n1 = ezy.load_neuron('sample_disordered.swc')

ezy.get('number_of_sections_per_neurite', n)
Out: array([ 5.,  3.])

ezy.get('number_of_sections_per_neurite', n1)
Out: array([ 5.,  3.])

n0 = fst.load_neuron('sample.swc')
n01 = fst.load_neuron('sample_disordered.swc')

Out:
KeyError                                  Traceback (most recent call last)
/home/kanari/bitbucket/NeuronTopology/code/<ipython-input-7-567d250915ee> in <module>()
----> 1 n01 = fst.load_neuron('./neurontopology/test_data/sample_disordered.swc')

/home/kanari/github/Experimental_ready/NeuroM/neurom/fst/_io.pyc in load_neuron(filename)
    113     }
    114     ext = os.path.splitext(filename)[1][1:]
--> 115     rdw = _READERS[ext.lower()](filename)
    116     trees = make_trees(rdw, _NEURITE_ACTION[ext.lower()])
    117     soma = make_soma(rdw.soma_points())

/home/kanari/github/Experimental_ready/NeuroM/neurom/fst/_io.pyc in <lambda>(f)
    103     '''Build section trees from an h5 or swc file'''
    104     _READERS = {
--> 105         'swc': lambda f: SWC.read(f, wrapper=SecDataWrapper),
    106         'h5': lambda f: H5.read(f, remove_duplicates=False, wrapper=SecDataWrapper),
    107         'asc': lambda f: NeurolucidaASC.read(f, remove_duplicates=False, wrapper=SecDataWrapper)

/home/kanari/github/Experimental_ready/NeuroM/neurom/io/swc.pyc in read(filename, wrapper)
    110             data = np.reshape(data, (1, -1))
    111         data = data[:, [SWC.X, SWC.Y, SWC.Z, SWC.R, SWC.TYPE, SWC.ID, SWC.P]]
--> 112         return wrapper(data, 'SWC', None)

/home/kanari/github/Experimental_ready/NeuroM/neurom/fst/_io.pyc in __init__(self, data_block, fmt, sections)
     54         self.data_block = data_block
     55         self.fmt = fmt
---> 56         self.sections = sections if sections is not None else extract_sections(data_block)
     57 
     58     def neurite_trunks(self):

/home/kanari/github/Experimental_ready/NeuroM/neurom/fst/_io.pyc in extract_sections(data_block)
    170     for sec in _sections:
    171         if sec.ids:
--> 172             sec.pid = parent_section[sec.ids[0]]
    173 
    174     return [s for s in _sections if s.ids]

KeyError: 31

fst.get('number_of_sections_per_neurite', n0)
Out: array([5, 3])
```

The disordered file fails to load with the fst module!

**Comment by juanchopanza** [comment]
That doesn't look right! I'll have a look at it.

**Comment by juanchopanza** [comment]
I think I figured out what is going on. In the disordered sample, there is a section that is being interpreted as two because of the break in IDs. But the first one only has one child, and that confuses the section extraction algorithm. The SWC spec allows this data. The question is whether we need to support it. If yes, then I will need to re-implement the SWC section extraction algorithm.

**Comment by juanchopanza** [comment]
I should point out that I don't think this will not be trivial, so we need to be sure it is needed.

**Comment by lidakanari** [comment]
No, it is not trivial (and this is not urgent as far as I know). I confirmed with the viz-team that this not-order representation is possible and should be allowed. I know it messes up a lot of things but if we choose _not_ to support it we will have to document it clearly (since there is not such restriction in the original swc format, as far as I know). I have an algorithm for this that I am implementing for another tool, so in case we choose to fix this issue, maybe you could use the parts that are relevant to make sections out of the swc structure.

**Comment by juanchopanza** [comment]
Could you confirm with the viz team that "not-order" means non-consecutive IDs inside of single _sections_ in SWC? Because this kind of thing cannot happen in h5 or .asc, by design.

**Comment by juanchopanza** [comment]
Ignore my previous message. I just tried the Brion morphology converter with the disordered file, and it converter read it and converted to h5 v1 fine. So Brion is doing the right thing, and `neurom.fst` is assuming too much.

**Comment by lidakanari** [comment]
I think this is related to mixed tree ids rather than mixed IDs inside sections. For example we cannot have (this is my assumption according to the SWC specs, we will have to confirm this) decreasing IDs: 2, 5, 4 but we can have parent ids mixed (as in the file I attached as example).

**Comment by lidakanari** [comment]
Also, I will create an equivalent example for h5 format to check similar issues, if this is helpful. In this case, the sections of different trees will be shuffled, but the points within a section will be consecutive.

**Comment by juanchopanza** [comment]
I really don't think it has to do with moving things around trees. The SWC reading algorithm uses the number of children to find section end-points, and this file has a false section with one child only. But I can test your hypothesis with another file and get back to you.

**Comment by lidakanari** [comment]
How can this file have a "false" section since the SWC file does not contain section information? I think this is related with some assumption to form the sections, I am not sure though. Let me know if I can help identify the issue.

**Comment by juanchopanza** [comment]
I added [swc_ordering.zip](https://github.com/BlueBrain/NeuroM/files/318817/swc_ordering.zip), where `sample_mixed_tree_sections.swc` has sections not sorted by tree. The `fst` module parses this one fine. I will add these files to the test data.

**Comment by juanchopanza** [comment]
The fake section is due to the code that tries to extract sections from the flat SWC data. I will have to fix it.
