### ISSUE TITLE
neurom.check.morphtree.is_backtracking docstring insufficient

### ISSUE THREAD

**Issue by juanchopanza** [BlueBrain/NeuroM#401]
The `is_backtracking` function in [neurom.check.morphtree](https://github.com/BlueBrain/NeuroM/blob/master/neurom/check/morphtree.py) looks complex, but there is no explanation in the docstring about what it actually does. This should be explained better. From looking at the tests, I can see there are two or three specific but distinct behaviours it deals with. Those could form the basis of a docstring.

**Comment by eleftherioszisis** [comment]
Fair Enough. I will look into it on Monday (I have a meeting with Henry Monday morning, so I cannot look into it before then).

**Comment by eleftherioszisis** [comment]
@juanchopanza Is there a way to apply ```isection``` on ``Neurite``` objects?

**Comment by juanchopanza** [comment]
`isection` doesn't make sense in the new representation. You have `Neurite.iter_nodes()` which I think has the same functionality.

**Comment by eleftherioszisis** [comment]
Ah, ```iter_nodes``` returns sections, not nodes?

**Comment by juanchopanza** [comment]
I think it returns nodes.

**Comment by eleftherioszisis** [comment]
I see. It returns nodes that represent sections, and contain points that make the segments. Right?

**Comment by juanchopanza** [comment]
Yes, every node holds a 2D array with all the points forming a section.

**Comment by eleftherioszisis** [comment]
I am closing this!
