### ISSUE TITLE
Detect zero radius soma in morph_check

### ISSUE THREAD

**Issue by juanchopanza** [BlueBrain/NeuroM#402]
This applies to soma that are otherwise considered valid by NeuroM.

**Comment by lidakanari** [comment]
Is this about the _actual_ radius of the soma or the radii of the points of the soma? I think the zero radius of soma points are valid, but the actual radius is expected to be greater than zero, so we should check the second one!

**Comment by juanchopanza** [comment]
My interpretation is that it is about the radius of the soma, not the soma points (which for a single point soma is the same.)

**Comment by lidakanari** [comment]
OK, I agree with this (Yes, single point soma is equivalent).
