### ISSUE TITLE
New concept of section

### ISSUE THREAD

**Issue by juanchopanza** [BlueBrain/NeuroM#421]
NeuroM neurites rely on a very generic tree representation. This had great advantages (for example, using the same underlying code to represent section trees instead of point trees.) But it also makes reasoning about some algorithms complicated by requiring a conceptual separation between the tree structure and the contents. For example, some functions need to know the tree structure, others only care about the section's points. I think now that we have converged on a suitable representation for neurites (trees of sections) it may be possible to lose some of the generality by changing the concept of "section" from a collection of points, to a tree node holding a collection of points. So a "section" could be represented similarly to out `Tree` class. In json-style pseudocode:

```
section = { 
    id,
    parent,
    points,
    children
}
```

By making this representation clear, developers would know that a "section function" assumes that data representation, i.e. it has access to the collection of points via the `points` member, and the tree-like components via `parent` and `children`. This will remove the conceptual difference between "tree functions" (e.g. branch_order, path_length) and pure "section functions (i.e. functions that only care about the points in the section.) I think the loss of generality is worth it.

My proposal would be to keep a generic tree base class, and derive `Section` from it:

```
class BaseTree(object):
    def __init__(self):
        self.parent = None
        self.children = list()
    def add_child(self, child):
        child.parent = self
        self.children.append(child)
        return child
```

**Comment by eleftherioszisis** [comment]
I think this is a good idea. It would be interesting to see if there is a significant overhead by using objects to store the collection of points and extract them for operations memory-wise and time-wise.

**Comment by juanchopanza** [comment]
Currently, we access them indirectly anyway, via the `Tree.value` member. So there should be no change. The only difference is that the indirection will happen inside the section functions, instead of on the caller side.
