### ISSUE TITLE
SWC with only one neurite isn't parsed right 

### ISSUE THREAD

**Issue by mgeplf** [BlueBrain/NeuroM#463]
Have a test case here #462 

Looks like `_section_end_points` needs to be augmented to deal with it.

Something like:
`if row[COLS.TYPE] != data_block[int(row[COLS.P])][COLS.TYPE]:` would help, but need to make sure that data_block has row[COLS.P], so it's a bit more complicated

**Comment by mgeplf** [comment]
I will try and have a look at it when I have some time.

**Comment by juanchopanza** [comment]
The problem is that the sections are supposed to be defined topologically, not by type (a change of type should not signify that a new section.) But somas are different.

**Comment by juanchopanza** [comment]
See #464.
