### ISSUE TITLE
test_view unit test fails on mac osx

### ISSUE THREAD

**Issue by juanchopanza** [BlueBrain/NeuroM#466]
Running `make run_tests` results in

```
======================================================================
FAIL: test_view.test_soma
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/palacios/code/bbp/NeuroM/neurom_test_venv/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/palacios/code/bbp/NeuroM/neurom/view/tests/test_view.py", line 73, in test_soma
    nt.ok_(np.allclose(ax.get_ylim(), (0.0, 0.20)) )
AssertionError: None
```

**Comment by mgeplf** [comment]
on my setup (matplotlib==1.5.1), the values are '(0.0, 0.25)', fyi

**Comment by lidakanari** [comment]
If this test is platform dependent it is a very bad unit test...

**Comment by juanchopanza** [comment]
@lidakanari Where do these numbers `(0.0, 0.20)` come from?

**Comment by lidakanari** [comment]
This is the expected y-limits of this plot. They are computed from the tree boundaries, but they also depend on the "plotting" behavior of matplotlib.

**Comment by mgeplf** [comment]
For the soma call, I don't think they're set from the boundaries, so matplotlib calculate them itself, which is probably why it varies on different platforms.
