### ISSUE TITLE
Running neurom.view tests launches view GUI

### ISSUE THREAD

**Issue by juanchopanza** [BlueBrain/NeuroM#467]
Running the viewer tests launches the GUI. The tester then had to kill it, only for the next one to appear. This should not happen.

```
. neurom_test_venv/bin/activate
nosetests -s -v neurom/view/tests/test_view.py
```

**Comment by juanchopanza** [comment]
@lidakanari Any ideas about this? `show_plot` seems to do more than controlling whether a plot is shown.

**Comment by lidakanari** [comment]
@eleftherioszisis did this part in order to resolve Werner's issue. I will let him take a look at this once he is available.

**Comment by juanchopanza** [comment]
@lidakanari @eleftherioszisis I have disabled this plotting by default. This now requires the user to ask for the thing to be plotted:

```
viewer.draw(n, mode='dendrogram', final=True)
```

Which relates to #470. The `final` option isn't documented, nor intuitive.

**Comment by lidakanari** [comment]
@wvangeit FYI

**Comment by wvangeit** [comment]
Yeah sure, wasn't this option called show_plot in the original issue ?
For me show_plot can be disabled by default, that's up to you. The test could also disable it if it defaults to True.

**Comment by juanchopanza** [comment]
@wvangeit Unfortunately show_plot seems to do more than just controlling whether a plot is shown or not.

**Comment by wvangeit** [comment]
@juanchopanza ok, so that's the core issue then I guess ;-)

**Comment by juanchopanza** [comment]
@wvangeit  I wouldn't know. This stuff is too mysterious for me!
