### ISSUE TITLE
document view `final` option

### ISSUE THREAD

**Issue by juanchopanza** [BlueBrain/NeuroM#470]
There seems to be an option `final` which controls whether a plot is shown or not (??!!)
This is needs to be documented. It may also make sense to give it a more intuitive name.

@eleftherioszisis I am assigning you because I think you introduced this option. Apologies if I am mistaken!

**Comment by mgeplf** [comment]
Any update on this?

**Comment by wizmer** [comment]
The `final` option is no longer in the codebase
