### ISSUE TITLE
Add test to ensure no bifurcations occur in the soma

### ISSUE THREAD

**Issue by lidakanari** [BlueBrain/NeuroM#475]
The following example of a morphology file (swc) should fail to load since two soma points have the same soma parent:

+1 1 0 0 0 0.0 -1
+2 1 0 0 2 0.0 1
+3 1 0 0 3 0.0 2
+4 1 0 0 4 0.0 2
+5 1 0 0 5 0.0 4
+6 1 0 0 6 0.0 5

**Comment by juanchopanza** [comment]
Note that this invalidates most of our SWC test neurons, so it will involve many changes to the tests.

**Comment by lidakanari** [comment]
No, sorry if the title is misleading. The swc neuron somata _should not_ have any bifurcations! I am not referring to bifurcations from the soma to another tree type. I am referring to the example I gave before (look comment above):

---- soma ----| ----soma----
                     |
                  soma
                     |

This "within soma" bifurcation should not happen in any morphology, independent of the file format.

**Comment by juanchopanza** [comment]
Sure, I understand that. But most of our test SWC files fall foul of that. I am already fixing them.

**Comment by lidakanari** [comment]
Please give an example. The swc I created does not have this problem, and I even had a test to ensure this with the previous loaders. Maybe I am still writing something confusing.

**Comment by juanchopanza** [comment]
Here: https://github.com/BlueBrain/NeuroM/blob/master/test_data/swc/Neuron.swc#L35

Two soma points bifurcating from point 1. If this is supposed to be valid, then the description of this issue needs to be clarified.

**Comment by lidakanari** [comment]
No, you are right. This should not be accepted. Thanks for the clarification!

**Comment by juanchopanza** [comment]
OK, good! Fortunately those are easy to fix.
