### ISSUE TITLE
Read in glia data

### ISSUE THREAD

**Issue by juanchopanza** [BlueBrain/NeuroM#495]
Glia f5 files have an extra block of data. See if these can be loaded without compromising performance or maintainability.

[Example file](https://github.com/BlueBrain/NeuroM/files/457174/glia.zip)

**Comment by dkeller9** [comment]
The extra surface area information can be used to:

1) assign surface channels 
2) calibrate metabolic model
3) validate geometrical models
4) visualize the astrocytes

**Comment by juanchopanza** [comment]
This isn't very relevant to NeuroM. What is relevant is that you're interested in surface area. But how do you define it in terms of the new info?

**Comment by dkeller9** [comment]
It would be nice to have an easy way to access the data from NeuroM.

**Comment by asanin-epfl** [comment]
As of NeuroM v2 the reading is on MorphIO. Closing in favor of https://github.com/BlueBrain/MorphIO/pull/256.
