### ISSUE TITLE
Population section radial distance inconsistency

### ISSUE THREAD

**Issue by juanchopanza** [BlueBrain/NeuroM#501]
The section radial distance as calculated from a population seems inconsistent with that of individual neurons. This can be tested with a small sample of synthesized morphologies, where the soma positions of each cell differ:

```
import numpy as np
import neurom as nm
from neurom.io.utils import get_morph_files

DIR = 'path/to/some/morphologies'

pop = nm.load_neurons(DIR)
nrns = [nm.load_neuron(f) for f in get_morph_files(DIR)]

rad_dist_pop = nm.get('section_radial_distances', pop)

rad_dist_nrns = []
for nrn in nrns:
    rad_dist_nrns.extend( nm.get('section_radial_distances', nrn))

rad_dist_nrns = np.array(rad_dist_nrns)

print np.alltrue(rad_dist_pop == rad_dist_nrns)
```

Expected output: `True`, observed output: `False`.

**Comment by lidakanari** [comment]
The title should change to 'radial distance' instead of 'path distance'
