### ISSUE TITLE
dendrogram plot unreadable

### ISSUE THREAD

**Issue by jdcourcol** [BlueBrain/NeuroM#557]
The following dendrogram generated with the draw_dendrogram method is unreadable:
![image](https://cloud.githubusercontent.com/assets/5441880/20877752/0717b0a4-bacb-11e6-8e33-400ccd05c171.png)

I can provide the reconstrcution for test through private message but I will not put it online.

**Comment by mgeplf** [comment]
I believe this code was initially committed by @eleftherioszisis, so maybe he could have a look at it.

I believe he is quite busy at the moment, so if it's a high priority, I can devote some time to it.  Let me know.

**Comment by jdcourcol** [comment]
It is not high priority

**Comment by eleftherioszisis** [comment]
I think this is related to the aspect ratio of the axes.
By setting the aspect ratio to "auto" filled the space of the figure.

```python
fig, ax = viewer.draw_dendrogram(nrn)
ax.set_aspect('auto')
```

**Comment by jdcourcol** [comment]
it is definitely better. Is there a reason for this not being the default ?
![image](https://cloud.githubusercontent.com/assets/5441880/20883137/d46c8674-bae4-11e6-97fb-d4deba8ce74a.png)

**Comment by eleftherioszisis** [comment]
No there isn't. This was not happening in the past, so probably some part of the ```common``` was changed in the meantime, affecting the aspect ratio of the figures.

**Comment by lidakanari** [comment]
Actually there was a very long discussion about the preferred behavior of the aspect ratio... The default value for this feature changed recently as a result of this discussion: https://github.com/BlueBrain/NeuroM/issues/279. I think it would be preferable to  select a different default value in the viewer of the dendrogram, if you want to modify this for the dendrogram.

**Comment by mgeplf** [comment]
What is the final consensus on this?

**Comment by eleftherioszisis** [comment]
I suppose there should be added key argument in the ```common``` that will enable the manual change of the aspect ratio of the axes. No? @lidakanari

**Comment by lidakanari** [comment]
Yes, the option is in common, plot_style (check aspect_ratio). In case a specific value is needed for the dendrogram I suggest we change it in the specific code of the dendrogram to avoid contradictions with other functions (see view and the discussion I referenced before). To do this just set the 'aspect_ratio' to the desired value and then pass it into the common when you can plot_style as an argument!

**Comment by mgeplf** [comment]
I'm going to assign this to you guys, as you know best how the plotting should work.

**Comment by lidakanari** [comment]
Sure, no problem. I will modify the aspect_ration of the dendrogram to "auto".
