### ISSUE TITLE
make path_fraction_point consistent with points in segment

### ISSUE THREAD

**Issue by jdcourcol** [BlueBrain/NeuroM#559]
path_fraction_point returns a point. If I use this function with points coming from a section (section.points) I don't get the same kind of point because it doesn't have a radius. I would expect to get the interpolated radius too.

**Comment by mgeplf** [comment]
A code snippet would be helpful.

**Comment by asanin-epfl** [comment]
I don't see in the sources of `path_fraction_point` that it uses radius or diameter. Closing. Feel free to reopen with an example to demonstrate the problem.
