### ISSUE TITLE
Principal direction extents for a neuron as a whole

### ISSUE THREAD

**Issue by eleftherioszisis** [BlueBrain/NeuroM#567]
It would be useful to be able to calculate the principal direction extents for a whole neuron.

Right now the neurites are treated separately, calculating the principal components and the projection of points upon the eigenvectors of the covariance matrix of the points that constitute the neurite. 

However, sometimes one would like to calculate the extent of a neuron as a whole.

Thus, the feature could calculate the pcds for a neuron if a neuron is passed and for separete neurites if a set of neurites is passed.

**Comment by mgeplf** [comment]
At the developer API level, you can do this:
```
import neurom as nm
import neurom.morphmath as mm
from neurom.core.dataformat import COLS

foo = nm.load_neuron('foo.swc')
mm.principal_direction_extent(foo.points[:, XYZ])
```
Is that what you expect?  This includes the soma points, but I guess you may want this for the 'neuron as a whole'

**Comment by eleftherioszisis** [comment]
Yes, this is what I would expect. I just think that it would be useful to be able to differentiate between neurons and neurites from the feature getter level of this feature.

**Comment by asanin-epfl** [comment]
@eleftherioszisis Do you still need this? If yes then am I correct that you want to have a feature `principal_direction_extents` at neuron level? Currently there is `principal_direction_extents` in `neuritefunc` for neurites.

**Comment by arnaudon** [comment]
take a look around here: https://github.com/BlueBrain/morph-tool/blob/master/morph_tool/transform.py#L179
