### ISSUE TITLE
Python 3 compatability

### ISSUE THREAD

**Issue by boazmohar** [BlueBrain/NeuroM#580]
Hi,

Are there any planes to make NeuroM python 3 compatible?
Would you consider a pull request for that?

Thanks,
Boaz

**Comment by mgeplf** [comment]
I believe we've made progress in that department already.  Which functionality isn't working with python3?

**Comment by boazmohar** [comment]
I pip installed version 1.1.1
I get this error while importing neurom:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/groups/svoboda/home/moharb/anaconda3/lib/python3.5/site-packages/neurom/__init__.py", line 62, in <module>
    from .core import iter_neurites, iter_sections
  File "/groups/svoboda/home/moharb/anaconda3/lib/python3.5/site-packages/neurom/core/__init__.py", line 31, in <module>
    from itertools import ifilter, imap, chain
ImportError: cannot import name 'ifilter'
```

**Comment by juanchopanza** [comment]
@boazmohar It seems [version 1.2](https://github.com/BlueBrain/NeuroM/releases) didn't get deployed to pypi.python.org. That is the version that has some modifications for python3 support. I will open a separate issue.

**Comment by juanchopanza** [comment]
Opened #582.

**Comment by boazmohar** [comment]
Thanks! I will wait for the 1.2.1.

**Comment by mgeplf** [comment]
Ok, 1.2.1 should have been uploaded, so I'm hoping that fixes your problems.  Let me know if it works for you.

Py3 isn't currently the highest priority for support, so there may be gaps compared to the py2 support.  However, if you find problems, create issues or make pull requests.  All help is appreciated.

**Comment by mgeplf** [comment]
Any luck with the new version?

**Comment by boazmohar** [comment]
Yes just checked it, works great, Thanks!
