### ISSUE TITLE
Convex hull calculation used for density doesn't take into account the diameters

### ISSUE THREAD

**Issue by mgeplf** [BlueBrain/NeuroM#587]
For example, with SWC:
```
# SWC structure:
# index, type, x, y, z, radius, parent
#
#           (1, 5)
# (-5, 5)----- ------ (6, 5)
#             |
#             |
#             |
#             | Type = 3
#             |
#             o origin

# note all the diameters are 4

 1 1  0  0 0 1. -1
 2 3  0  0 0 4.  1
 3 3  0  5 1 4.  2
 4 3 -5  5 0 4.  3
 5 3  6  5 0 4.  3
```

The test case:
```
import neurom as nm
n = nm.load_neuron('bad_convex_density.swc')
nm.get('neurite_volume_density', a.neurites[0])
```
returns `89.27`, which is not a valid density.

This was originally pointed out by @lidakanari

**Comment by asanin-epfl** [comment]
What is the valid density? I don't have enough context to solve this. Any advice @lidakanari ?

**Comment by arnaudon** [comment]
Well it could be, in fact I wanted to do that to check how much space neurons take place in a circuit at some point.

**Comment by eleftherioszisis** [comment]
@arnaudon , is this issue still relevant? Does considering the radii make a big difference. given the extent of the morphology?
