### ISSUE TITLE
use cleaner way of using matplotlib so that the 'Agg' background doesn't need to be set 

### ISSUE THREAD

**Issue by mgeplf** [BlueBrain/NeuroM#590]
Currently if someone import matplotlib.pyplot before neurom is used, and the DISPLAY variable isn't set, it tries to set the 'Agg' background, so that figures aren't rendered to the current user.  Instead, it should create figures without pyplot, so that does happen.

**Comment by QuLogic** [comment]
Why not just remove it? This part is a library, not an application, so it doesn't _need_ a specific backend. The choice of backend should be left to the user.

**Comment by mgeplf** [comment]
Going to fold this into #607 
Thanks for the feedback
