### ISSUE TITLE
plotting is slow

### ISSUE THREAD

**Issue by jdcourcol** [BlueBrain/NeuroM#604]
It took on my laptop 28min to plot 120 figures (~14s per plot) with the following code:

```
  nrn = load_neuron(morph_name, release_path)
  bb = geom.bounding_box(nrn)
  max_projection = np.max(np.abs(list(bb[0][:2]) + list(bb[1][:2])))
  center = nrn.soma.center[:2]
  view.neuron(nrn, output_path=output_path, output_name=morph_name,
                    xlim=[center[0] - max_projection, center[0] + max_projection],
                    ylim=[center[1] - max_projection, center[1] + max_projection],
                    dpi=275)
```
I think it is way too slow.

**Comment by jdcourcol** [comment]
FWIW, I noticed the following warning:
'''
venv/lib/python2.7/site-packages/matplotlib/pyplot.py:524: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
'''

**Comment by mgeplf** [comment]
Yeah, this falls under the general cleanup of how figures are handled, specifically when more control over figure creation and closing.  Add it to the pile of stuff to do.

**Comment by mgeplf** [comment]
I think I'm going to need more information:
1. What version of neurom are you using?
1. what does your `nrn = load_neuron(morph_name, release_path)` reference, as load_neuron only takes 1
2. What type of morphology are you loading?
3. If you close the figure after you've written them, does that make things faster?
```
import matplotlib.pyplot as plt
...
fig, ax = view.neuron(...)
plt.close(fig)
```

**Comment by jdcourcol** [comment]
> What version of neurom are you using?
1.2.1
 
> what does your nrn = load_neuron(morph_name, release_path) reference, as load_neuron only takes 1
my bad, I copy pasted old code. I am actually calling load_neuron(f) and it has only one parameter

> What type of morphology are you loading?
h5v1 morphologies of type L5_TPC
> If you close the figure after you've written them, does that make things faster?
I get that error:
    plot_one_neuron(nrn, 'fig', morph)
  File "/Users/courcol/DEV/plot_nrn.py", line 41, in plot_one_neuron
    plt.close(fig)
  File "/Users/courcol/DEV/venv/lib/python2.7/site-packages/matplotlib/pyplot.py", line 664, in close
    raise TypeError('Unrecognized argument type %s to close' % type(arg))
TypeError: Unrecognized argument type <class 'matplotlib.axes._subplots.AxesSubplot'> to close

**Comment by lidakanari** [comment]
You can either define the figure when you create it (see @mgeplf code above) or alternatively use:
```
plt.close()
```
which closes the last figure that was created if you have not saved your figure.

**Comment by jdcourcol** [comment]
I tried with plt.close()
I don't get the warning I mentioned in my second comment anymore, but it takes the same time.

**Comment by mgeplf** [comment]
Ok, I have found the problem: the plot_style is called per neurite, and this saves the figure, each time, so often the figure is saved 8 or more times.

I will fix this in the view refactoring, because it is inefficient, but in the mean time, you can speed things up by saving things yourself:
```
    fig, _ = view.neuron(nrn,
                                    xlim=[center[0] - max_projection, center[0] + max_projection],
                                    ylim=[center[1] - max_projection, center[1] + max_projection])
    fig.savefig(os.path.join(output_path, morph_name + '.png'), dpi=275)
    plt.close(fig)
```

Does that make it faster?

**Comment by jdcourcol** [comment]
yes, it speeds up the thing. With that, it takes 4min33s instead of more than 28min.

**Comment by mgeplf** [comment]
That's the kind of speeds ups I like.

I hope to refactor some of the viewing code shortly, and I will add this to the list.

**Comment by mgeplf** [comment]
I'm going to fold this into #590 and the refactoring required for that
