### ISSUE TITLE
Check Neuron.h5 in test_data (v1 and v2)

### ISSUE THREAD

**Issue by lidakanari** [BlueBrain/NeuroM#606]
I am not sure if this is an error according to the accepted h5 format but the Neuron.h5 in the test_data has two soma sections:
0	1	-1
1	1	0

@eleftherioszisis Could you please add a comment about this?

**Comment by mgeplf** [comment]
yeah, something is wrong there, I have a ticket to fix that up #600.  However, it will take time to also update all the tests.
