### ISSUE TITLE
Bifurcating Soma Error

### ISSUE THREAD

**Issue by eleftherioszisis** [BlueBrain/NeuroM#613]
Curated morphologies that are available in Neuromorpho are not loaded in NeuroM due to their bifurcating soma which raised a ```SomaError```.

Does this check rise from how NEURON assumes the file format? If curated data is present with bifurcating soma, I think this check should be relaxed and be present for example in morph_check. This way users that are not concerned about the validity of the soma will still be able to analyse their morphology.

Morphology:
http://neuromorpho.org/dableFiles/acsady/CNG%20version/VPM_1.CNG.swc

**Comment by mgeplf** [comment]
related to #614
