### ISSUE TITLE
First soma point error

### ISSUE THREAD

**Issue by eleftherioszisis** [BlueBrain/NeuroM#614]
Second attempt to load a cell... The swc structure seems reasonable to me but I receive the following error:

```python
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-7-6a742e834617> in <module>()
      1 path_to_neuron = '../morphologies/april11s1cell-1.CNG.swc'
----> 2 neuron = nm.load_neuron(path_to_neuron)

/home/hbpschool2016/local/pythonenv/local/lib/python2.7/site-packages/neurom/io/utils.pyc in load_neuron(filename)
    101     rdw = load_data(filename)
    102     name = os.path.splitext(os.path.basename(filename))[0]
--> 103     return FstNeuron(rdw, name)
    104 
    105 

/home/hbpschool2016/local/pythonenv/local/lib/python2.7/site-packages/neurom/fst/_core.pyc in __init__(self, data_wrapper, name)
     44         neurites, sections = make_neurites(self._data)
     45         soma_check, soma_class = _SOMA_CONFIG[self._data.fmt]
---> 46         soma = make_soma(self._data.soma_points(), soma_check, soma_class)
     47         super(FstNeuron, self).__init__(soma, neurites, sections)
     48         self.name = name

/home/hbpschool2016/local/pythonenv/local/lib/python2.7/site-packages/neurom/core/_soma.pyc in make_soma(points, soma_check, soma_class)
    273         raise SomaError('Invalid soma points')
    274 
--> 275     return stype(points)

/home/hbpschool2016/local/pythonenv/local/lib/python2.7/site-packages/neurom/core/_soma.pyc in __init__(self, points)
    148             'All radii must be the same'
    149         assert np.isclose(points[0, COLS.Y] - points[1, COLS.Y], points[0, COLS.R]), \
--> 150             'The first point must be one radius below 0 on the y-plane'
    151         assert np.isclose(points[0, COLS.Y] - points[2, COLS.Y], -points[0, COLS.R]), \
    152             'The second point must be one radius above 0 on the y-plane'

AssertionError: The first point must be one radius below 0 on the y-plane
```
where the soma points are:

```
1 1 0.0 0.0 0.0 6.75281 -1
2 1 -2.29 6.34 0.0 6.75281 1
3 1 2.29 -6.34 0.0 6.75281 1
```

Morphology:
http://neuromorpho.org/dableFiles/brumberg/CNG%20version/april11s1cell-1.CNG.swc
http://neuromorpho.org/dableFiles/brumberg/CNG%20version/inv-4-24-08-s2-cell-1.CNG.swc

**Comment by juanchopanza** [comment]
The code is trying to implement the absurd 3-point soma format defined in neuromorpho.org and quoted here: https://github.com/BlueBrain/NeuroM/blob/master/neurom/core/_soma.py#L124. I think this soma doesn't satisfy the criteria.

**Comment by eleftherioszisis** [comment]
This is peculiar because Markram cells seem to not satisfy these criteria as well. And on top of that the cells I posted have a three point soma.

Example from Hay, Markram from Neuromoprho:
http://neuromorpho.org/dableFiles/hay/CNG%20version/cell21.CNG.swc

**Comment by lidakanari** [comment]
According to: http://neuromorpho.org/SomaFormat.html the three point soma should be represented as:
```
1 1 xs ys zs rs -1
2 1 xs (ys-rs) zs rs 1
3 1 xs (ys+rs) zs rs 1
```
As a result the _first point_ should not be a radius below zero, but the _second_ should be a radius below the center's _y-coordinate_. I am not sure that the comment you get represents the actual reason the cell is rejected as from checking "http://neuromorpho.org/dableFiles/brumberg/CNG%20version/april11s1cell-1.CNG.swc" I noticed that the second and third points are not radius-distance away from the soma on the y-axis.

**Comment by lidakanari** [comment]
The problem is that those restrictions forbid the loading of any neuromorpho.org morphology even though they were added to only allow neuromorpho.org curated morphologies.

**Comment by juanchopanza** [comment]
My three cents: 1) relax the restrictions on morphology loading 2) figure out if there is a way to interpret the "non-conforming" somata 3) Fix the diagnostic message and verify whether the check assumes the root point has z = 0.

**Comment by lidakanari** [comment]
@juanchopanza I agree with all your suggestions!

**Comment by mgeplf** [comment]
The problem comes down to distinguishing a soma containing 3 points, which should be allowable, and dealing with the 'revised' format that NeuroMorpho generates (but doesn't follow? Maybe the L-Measure version they were using doesn't conform to the standard, I will see what I can figure out).

The description Lida is accurate. 

I can change the checks into just producing warnings.  People should know, however, that when this type of soma is loaded in NEURON, it won't be interpreted correctly.

**Comment by lidakanari** [comment]
If the description of the error is accurate then the check is not correct: the second point should be below the center by r-distance on the y-axis and not the first one below zero. Am I missing something? 

Also is the +- r variation on the y-axis -in practice-? I noticed that all the data that are attached to this issue seem to have this variation on the z-axis instead...

**Comment by eleftherioszisis** [comment]
Is it possible for this to be fixed and a new version released today?
The tutorial is for tomorrow and I fail to load any morphologies apart from the test ones.

**Comment by mgeplf** [comment]
@lidakanari: yeah, I was thinking in 0-based, so 1st is misleading.  The *second* point should be below y, and the *third* above y.

I think I'm missing the `z` portion of the concern.

@eleftherioszisis, I can turn off the warnings for now, and release the a new version, but there are some plotting differences that I was hoping people would have a chance to run into before creating a new release.

**Comment by lidakanari** [comment]
@mgeplf OK, that makes sense! 

Sorry, the z-comment was confusing. By observation on the limited data that are attached here I recite the somata representations:
```
1 1 0.0 0.0 0.0 6.75281 -1
2 1 -2.29 6.34 0.0 6.75281 1
3 1 2.29 -6.34 0.0 6.75281 1

1 1 0.0 0.0 0.0 14.4522 -1
2 1 -0.37 -14.43 -0.45 14.4522 1
3 1 0.37 14.43 0.45 14.4522 1

1 1 0.0 0.0 0.0 10.809 -1
2 1 -0.05 -10.8 -0.22 10.809 1
3 1 0.05 10.8 0.22 10.809 1
```
This seems to contradict the described scheme as both x and z coordinates are represented by a +- x / z as opposed to having the preserving the same x or z coordinates for all three soma points. Does this mean that the data do not follow the scheme as it is described? If that is the case maybe we should relax the loading restrictions? I have no idea if those morphologies will be loaded correctly in Neuron. @wvangeit any comments?

**Comment by wvangeit** [comment]
@lidakanari, not much to comment really. It only shows that the neuromorpho.org is not normalising their morphologies to the format they have defined themselves, but that's something we already knew ... 
As long as they don't do that, I think the only thing we can do is to find a middle way between all the tools that load morphologies. From my point of view the most important is to make sure that a morphology looks the same in NeuroM and Neuron.

**Comment by lidakanari** [comment]
Yes, I was asking about your expertise in Neuron (if you happen to know if this format is accepted or not), since it seems like this format is common in neuromorpho.org. It would be helpful to be aware of how Neuron is handling those data, before we change NeuroM...

**Comment by wvangeit** [comment]
I tried one of the morphos above. It kind of accepts it, but it gives a warning that it is ignoring the second and third point. So it makes a soma at 0,0,0 with the correct diameter (assuming that the diameter field of first line is filled in correctly)

**Comment by lidakanari** [comment]
@wvangeit OK, thanks a lot for the information!

**Comment by wvangeit** [comment]
It's kind of a detail, but it could mess up statistics (or testing between outputs of different tools):
Want to warn about e.g:
1 1 0.0 0.0 0.0 6.75281 -1
2 1 -2.29 6.34 0.0 6.75281 1
3 1 2.29 -6.34 0.0 6.75281 1

so half of the length of the soma == math.sqrt(pow(-2.29,2) + pow(6.34,2)) == 6.740897566348268
so the radius of 6.75281 in the SWC is not exactly the same, creating an ellipsoid/cylinder.
