### ISSUE TITLE
Direct indexing for sections and segments

### ISSUE THREAD

**Issue by arsenius7** [BlueBrain/NeuroM#616]
As far as I understand, NeuroM main focus is working with _separate_ morphologies (thus access with tree-traversal iterators).

In the context of a full circuit, however, often what we want is a table-like access to segment / sections properties (for example, to find the volume of the neurites of particular type within given region).

Should it be also a responsibility of NeuroM to provide efficient data access for scenario like this?
Or should it be a library relying on NeuroM? A completely separate thing?

**Comment by mgeplf** [comment]
Good question.  The current focus is certainly separate morphologies 'floating' in space, with no interactions between them, and no awareness of the space around them.

Expanding the missions statement is possible, but if anything, I think it would be more useful to reduce the scope of this library, and have extensions for different purposes.  Being spatially aware, and providing efficient access would be one of the extensions, in my view.

Maybe we could start that way (ie: separate library) and add whatever is necessary in NeuroM to achieve that, and consider folding it into the main library at some point if we decide to go that direction.

**Comment by lidakanari** [comment]
Is this issue related to #276? I think this is a very good point and it would be convenient to provide a global system that will be able to provide section and segment information (even if that is outside NeuroM).

**Comment by eleftherioszisis** [comment]
I would like to mention at this point that Adrien (HPC) has developed Morpho-Tool and they are working on a python interface.
Apart from the usual tree data structure (c++) for the morphologies (which can be editable) it provides spatial indexing with Boost RTree.
You might be interested in integrating it with NeuroM.
