### ISSUE TITLE
suppress an warning

### ISSUE THREAD

**Issue by clupascu** [BlueBrain/NeuroM#619]
Hi,

I  would like to suppress a warning I get when I load an asc morphology using nm.load_neuron
The warning I get is 

WARNING:neurom.io.neurolucida:This is an experimental reader. There are no guarantees regarding ability to parse Neurolucida .asc files or correctness of output.

I tried with

import warnings
warnings.filterwarnings("ignore")

but it is not working.

Any suggestion?

Thanks.

**Comment by mgeplf** [comment]
The string `WARNING:neurom.io.neurolucida:...` makes me think it's python's logging mechanism that is producing this.

Is there a chance you can solve it with: https://docs.python.org/2/library/logging.html#logging.captureWarnings

**Comment by clupascu** [comment]
import logging
logging.captureWarnings(True)

in the Jupyter Notebook
does not solve the issue.

**Comment by mgeplf** [comment]
I didn't know you were in a jupyter notebook: for that you'll need to change the default logging handlers, which is described here: http://stackoverflow.com/questions/35326814/change-level-logged-to-ipython-jupyter-notebook/35327111#35327111

This is outside the scope of NeuroM, so I'm not sure this is the right place for support.
