### ISSUE TITLE
Request a method for loading neurons from a byte stream

### ISSUE THREAD

**Issue by genric** [BlueBrain/NeuroM#625]
Something similar like [load_data](https://github.com/BlueBrain/NeuroM/blob/master/neurom/io/utils.py#L136) from neurom.io but taking byte stream and a type would be nice to have.
Thanks.

**Comment by mgeplf** [comment]
Rather than `load_data`, I think having the semantics of `load_neuron` (ie: returns a Neuron-like class) would be more useful.  For the textual formats (SWC & ASC), it should be pretty easy.  For a binary stream, like h5, I think it might be more difficult.

**Comment by wizmer** [comment]
Done, `StringIO` can be now be used as an input of `load_data`.
It will save the input stream in a temp file and use it for loading the neuron.
