### ISSUE TITLE
Differences between bifurcations and multifurcationsv(forking_points)

### ISSUE THREAD

**Issue by RVeler** [BlueBrain/NeuroM#632]
Hi,
I am a Msc student in the faculty of neurobiology in Haufa University,
My research deals with the topic of PyN cluster analysis by morphologic parameters and SP, 
first of all, thank you for sharing this project, it's help me a lot with the study.
I have a question about the bi/multi furcation "get" features, I understood that multifurcation counts branches with 2 **or more** children and bi.... counts  barnching points with only 2 (tell me if I got this wrong).
When I running the code, I get sometimes the same result for the both features but sometimes I get bigger result for the forking points, so I want to clearly understand what actually the differences - when I have for instance 3 children the bi counts it as nothing and the multi as 1 or the bi as 1 and the multi as 2 ?
Thanks!!

**Comment by mgeplf** [comment]
Hello,

The bifurcation/forking point code is here:
https://github.com/BlueBrain/NeuroM/blob/master/neurom/core/tree.py#L50-L56

Forking points counts should always be greater or greater than the bifurcation points, as bifurcations points is a subset of Forking points.  If you find a case where this is wrong, please let us know, so we can fix it (this goes for any other bugs you run across as well.)  Does that answer your question?

Glad the project is helpful.

**Comment by lidakanari** [comment]
Hi,

We count the _number_ of bi (tri, multi) furcations, so in your example a tri-furcation will count as 0 in the bifurcations and as 1 in the multifurcations. So when bi=multi it means that your structure only has bifurcations, when bi<multi your structure includes multifurcations. 

I hope this explanation helps!
