### ISSUE TITLE
No handlers could be found for logger "neurom.core._soma"

### ISSUE THREAD

**Issue by michaelStettler** [BlueBrain/NeuroM#637]
Hi, 

I'm new in the community of this project. I have successfully install the neurom environment.

I have tried to do a small script where I import the library, load a neuron in (swc file) and try to display it, the code seems to launch and a window containing the neuron shortly appear before closing itself, then I got the following message:

No handlers could be found for logger "neurom.core._soma"

I'm using python 2.7 and I checked all the requirement libraries, all of them are in order. Being new with this library, I'm not sure if the error comes from the neuron I'm trying to open or if its a more general python issue. I have tried to look already on google but didn't figure it out. Any help on this issue will be welcome.

**Comment by mgeplf** [comment]
Hello,

To see what the error message is, it's probably best to turn on logging.  Something like this at the top of the script should work:
```
import logging
logging.basicConfig(level=logging.DEBUG)
```

Based on that, we'll see the error and go from there.

**Comment by michaelStettler** [comment]
Hi, 

thank you for your answer, I copy past your line, the behavior is the same but now the error is:

WARNING:neurom.core._soma:Using neuromorpho 3-Point soma

**Comment by mgeplf** [comment]
Ok, that should be fine.  I suspect that since a figure is popping up and disappearing, it might be how you're calling matplotlib.  If you're running a script (as opposed to using it interactively), if you do a `fig.show()`, the figure will pop up and disappear.  If you do a `plt.show()` it will stay on the screen.

If that doesn't fix the problem, it's probably best to paste the code you're running, so I can examine it.

**Comment by michaelStettler** [comment]
Indeed the issue was with matplotlib, I was actually not calling it, I have thus added the import line and a plt.show() at the end of the script as shown below. Everything is fine now, thank you!

import neurom as nm
from neurom import viewer
import matplotlib.pyplot as plt #added this line
import logging

logging.basicConfig(level=logging.DEBUG)

nrn = nm.load_neuron('../data/L23_PC/C031000B-P3.CNG.swc')
apical_seg_lengths = nm.get('segment_lengths', nrn, neurite_type=nm.APICAL_DENDRITE)
axon_sec_lengths = nm.get('section_lengths', nrn, neurite_type=nm.AXON)

fig, ax = viewer.draw(nrn)
fig.show()
fig, ax = viewer.draw(nrn, mode='3d') # valid modes '2d', '3d', 'dendrogram'
fig.show()

plt.show() #added this line

**Comment by mgeplf** [comment]
Glad it works
