### ISSUE TITLE
New Feature: fast and efficient loader for somata (without neurites)

### ISSUE THREAD

**Issue by eleftherioszisis** [BlueBrain/NeuroM#647]
Loading a whole morphology to get the soma features is a little bit of an overkill, especially in situations where thousands of morphologies are required to be loaded.

Would it be possible to create a loader that would load only the soma of the morphology in a fast and efficient way without loading the rest of the morphology and without generating the neurite structures etc. ?

An example:
``` python

from neurom import load_soma 

somata = [load_soma(filename) for filename in filenames]
radii = np.fromiter((soma.radius for soma in somata), dtype=np.float)
```

**Comment by asanin-epfl** [comment]
This is impossible to do as now NeuroM relies on MorphIO to read morphologies. On the bright side, MorphIO is C++ library that is expected to be fast. If necessary please reopen this issue at MorphIO repo.
