### ISSUE TITLE
Cannot rotate a synthesized neuron

### ISSUE THREAD

**Issue by chalimou** [BlueBrain/NeuroM#656]
I got the following synthesized neuron from a friend who is experimenting with NeuroM.
[GregNeuron_201708221333_1.swc.zip]

I can load and plot it with the following code:

plt.close()
fig = plt.figure()
fig = plt.figure(figsize = (8, 8))
ax = fig.add_subplot(1,1,1)
for i in elements:
    view.plot_neuron(ax, i, diameter_scale = None)
    ax.set_aspect('equal')
    ax.set(xlim=(-600,200))
    ax.set(ylim=(-1000,0))
plt.show()

My problem is that I cannot rotate it with the line:

 r = neurom.geom.rotate(i,(0,1,0), 2)

I think the problem is in this neuron and NOT NeuroM, because the above procedure works for the following reconstructed neuron (C031000B-P3.h5):

Nevertheless, I would be grateful for any hint why GregNeuron_201708221333_1.swc is loaded and plotted correctly but cannot be rotated.

(https://github.com/BlueBrain/NeuroM/files/1390983/GregNeuron_201708221333_1.swc.zip)
[C031000B-P3.h5.zip](https://github.com/BlueBrain/NeuroM/files/1390984/C031000B-P3.h5.zip)

**Comment by wizmer** [comment]
The rotated neuron is not in the correct field of view. Setting the axes to:
`ax.set(xlim=(400, 1000))`
`ax.set(ylim=(-900, -300))`
should solve the problem.

**Comment by chalimou** [comment]
thank you! Much easier than I supposed. They place the coordinates’ origin differently than at the soma, that is why it vanishes from the window. I was not used to that.

**Comment by chalimou** [comment]
the issue can be closed, thanks
