### ISSUE TITLE
Sholl analysis is performing a lot of unnecessary computations

### ISSUE THREAD

**Issue by lidakanari** [BlueBrain/NeuroM#663]
The results of Sholl analysis return of a lot of zeros. I _think_ this is because the bounding box encloses the whole neuron while it should enclose only the trees of a specific neurite_type on which the computation is actually performed. See the following line:

https://github.com/BlueBrain/NeuroM/blob/49dbaef7ed78c351d8adb3085843010716afa217/neurom/fst/_neuronfunc.py#L201

**Comment by wizmer** [comment]
#669 should fix it.

**Comment by mgeplf** [comment]
I don't think #669 fixes it, but it's probably something similar.
I think we'll have to make a fake neuron to test this on, so we can be assured that we're fixing the problem.
