### ISSUE TITLE
memoization behaviour prevents memory to be released.

### ISSUE THREAD

**Issue by jdcourcol** [BlueBrain/NeuroM#666]
memoization in NeuroM involves a class variable: https://github.com/BlueBrain/NeuroM/blob/master/neurom/utils.py#L44
When accessing properties on a lot of morphologies sequentially, even though we don't reference the morphology anymore, properties are still stored in that cache.
The consequence is that memory keeps growing even if we actually needs only 1 morphology at a time. This prevents analyzing large number of morphologies.
Please make that memoization optional or attach the cache to the morphology.

**Comment by jdcourcol** [comment]
@wizmer I think you can close it now ?

**Comment by wizmer** [comment]
Merged in #667
