### ISSUE TITLE
view.plot_neuron() doesn't work

### ISSUE THREAD

**Issue by elisabettai** [BlueBrain/NeuroM#673]
In the past I could use the view.plot_neuron function to draw a neuron on an existing axes.

If I do:
``import neurom``
``from neurom import viewer``
``import matplotlib.pyplot as plt``
``nrn = neurom.load_neuron('test_data/neurolucida/bio_neuron-000.asc')``
``viewer.draw(nrn)``
 ``plt.show()``

I obtain this figure:
![image](https://user-images.githubusercontent.com/18575092/36476009-df1effb4-16fc-11e8-8def-dc0756f5b3df.png)

However, if I do:
``from neurom import view``
``fig, ax =  plt.subplots()``
``view.plot_neuron(ax, nrn, plane = 'xy')``
``fig.show()``

I obtain this:
![image](https://user-images.githubusercontent.com/18575092/36476105-2cdd7924-16fd-11e8-9488-d4536d61de7f.png)

I would expect both functions to work. Am I doing something wrong? If yes, could you suggest an other way to plot on existing axes?

**Comment by mgeplf** [comment]
Yeah, the `view.*` routines are quite low-level.  In this case, the axis limits aren't being set, so you are *super* zoomed in.  You can use this helper to set them: https://github.com/BlueBrain/NeuroM/blob/master/neurom/view/common.py#L312

Or do something similar yourself, depending on how zoomed in/out you want to be.

That solve the problem?

**Comment by lidakanari** [comment]
I would propose to first find the boundaries of the neuron (with neurom) and set the limits accordingly using the common routine, as proposed by @mgeplf .

**Comment by elisabettai** [comment]
Yes, it solved the problem. Many thanks.
