### ISSUE TITLE
'morph_stats' json outputs: {soma feature's name: value} pairs not collected into a unique key

### ISSUE THREAD

**Issue by pedroernesto** [BlueBrain/NeuroM#678]
Currently, NeuroM 'morph_stats' module provides a 'json' output file, containing a dictionary where each 'soma feature's name' key appears  at the same level as other cell parts (e.g. apical dendrite or axon), instead at the level for feature names and their values. Can the user customize 'morph_stats' output to correct that problem or such functionality is not implemented yet?

Reading the content of such dictionary might be simpler if all {soma feature's name: value} pairs were collected into a unique 'soma' key as well. For now, I am needing to re-format 'morph-stats' output with something like this to re-group those soma-features values into a unique key:
```
for dict1 in output_dict.values():
            soma_features = dict()
            for key, val in dict1.items():
                if key.find('soma') == -1:
                    continue
                soma_features.update({key: val})
                del dict1[key]
                dict1.update({"soma": soma_features})
```

**Comment by asanin-epfl** [comment]
Closing by the same reason as #722 is closed. Outdated.
