### ISSUE TITLE
Section iterator strategies

### ISSUE THREAD

**Issue by pgetta** [BlueBrain/NeuroM#690]
Looks like right now there is no easy way to map section IDs between neuroM and NEURON, this makes integration of these packages in some cases too fragile or nearly impossible.
Not sure about other use cases, but in pair recording app neuroM is used to load morphologies, and NEURON - to run simulations on small subset of cells from a given circuit.

As I know neuroM sets IDs according to order of sections in morphology file, but NEURON - sets them according also to neurite type. In case order of sections in morphology file is not the same to how NEURON loads them (according to Arseniy, happens in morphologies coming from external sources, like  AIBS) - mapping sections by their IDs becomes impossible.

My proposal is to add section iterator with optional argument which will define strategy of iteration - like `depth_first`, `neuron`, etc. or something similar.

Could be I'm missing something. Does this looks like something reasonable?

**Comment by wizmer** [comment]
Defining a Neuron-like iterator in NeuroM looks reasonable.
Once we have this, we could also implement a `get_NEURON_id` that returns the ID in Neuron.

**Comment by wizmer** [comment]
Implemented in https://github.com/BlueBrain/NeuroM/pull/701
