### ISSUE TITLE
Pinned h5py version

### ISSUE THREAD

**Issue by wvangeit** [BlueBrain/NeuroM#694]
Can the h5py version at:
https://github.com/BlueBrain/NeuroM/blob/master/setup.py#L41
be set to 
h5py>=2.7.1
instead of pinning it to exactly 2.7.1

When installing neurom in a virtualenv together with all kinds of other software, I'm getting:
"neurom 1.4.7 has requirement h5py==2.7.1, but you'll have h5py 2.8.0 which is incompatible."

**Comment by mgeplf** [comment]
good catch, I'll have a look

**Comment by mgeplf** [comment]
fixed in #695, however, will need to do a release

**Comment by mgeplf** [comment]
k, 1.4.8 is deployed, w/ unpinned deps

**Comment by wvangeit** [comment]
That works, thanks.
