### ISSUE TITLE
Is there a way to make morph_stats extract all available features

### ISSUE THREAD

**Issue by orena1** [BlueBrain/NeuroM#702]
Hi,
I would like to extract all available features of a neuron. If I understand the documentation correctly I need to set a config file in order to extract all features. Do I need to manually write it? or is there a way to extract all features without writing a specific config.

Thanks

**Comment by orena1** [comment]
Hi, is there an update with this ticket? Is there an option to get all features in motph_extract without writing each feature. something like "get_all"

**Comment by wizmer** [comment]
@orena1 This has been released in v1.4.20. Feel free to check.
