### ISSUE TITLE
using a config file with tabs gives an error

### ISSUE THREAD

**Issue by orena1** [BlueBrain/NeuroM#703]
Hi,
When creating a config file for morph_stats I got this error:
```bash
amsalem@amsalem-Kubuntu-home:~/Downloads$ morph_stats morphology.swc -C config_file 
ERROR:__main__:Invalid yaml file: 
 while scanning for the next token
found character '\t' that cannot start any token
  in "config_file", line 10, column 1
```
This error was because I used a tab in the config file ([config_file.txt](https://github.com/BlueBrain/NeuroM/files/2207589/config_file.txt)). I think it will not be bad to add to the app the ability to read config files with tabs.

Thanks

**Comment by mgeplf** [comment]
Since it's yaml that dictates that it can't use tabs (http://yaml.org/faq.html), I don't think it's something that we can easily change.
