### ISSUE TITLE
Bifurcating soma

### ISSUE THREAD

**Issue by orena1** [BlueBrain/NeuroM#714]
Hello,
I am trying to load this neuron (Which loads well on NEURON) but I get this error:
```python
SomaError: Bifurcating soma
```

Any idea why?

[C51A_scaled_exp.swc.zip](https://github.com/BlueBrain/NeuroM/files/2352471/C51A_scaled_exp.swc.zip)

**Comment by wizmer** [comment]
Because there is a soma bifurcation  at ID 4. Children are ID 5 and ID 171 (which is probably not expected)

**Comment by wizmer** [comment]
Can I close this ?

**Comment by orena1** [comment]
I am trying to figure out a way to fix it. You can close it, but once I
will manage to find a solution I will post it here.

**Comment by wizmer** [comment]
My guess is that the bifurcation starting at ID 171 has an incorrect section type soma. You could change the type of each points of the branch to something else (axon or dendrite). You can find the mapping section type to their code here: http://www.neuronland.org/NLMorphologyConverter/MorphologyFormats/SWC/Spec.html
