### ISSUE TITLE
Use publication for official interface

### ISSUE THREAD

**Issue by mgeplf** [BlueBrain/NeuroM#716]
Use:
https://pypi.org/project/publication/0.0.2/

Instead of relying on people reading documentation to show what is officially part of the API.

**Comment by wizmer** [comment]
That looks interesting. Have you ever used it ?
That will be a breaking chance for users already using private functions (even though they should not) so this should probably wait for NeuroM 2.0 as well.

**Comment by mgeplf** [comment]
Nope, it's really new, but I like the idea of it.
Waiting for 2 sounds fine w/ me.

**Comment by asanin-epfl** [comment]
I am not sure how actual is this. In NeuroM v2 API have been simplified. All private modules are deleted or made public. Autodoc plugin generates API documentation for all sources. Closing. Feel free to reopen if needed.
