### ISSUE TITLE
Documentation for neurom.core.point.Point probably outdated

### ISSUE THREAD

**Issue by alex4200** [BlueBrain/NeuroM#739]
The documentation for neurom.core.point.Point seems to be inconsistent with the example. In the example you have a piece of code that gets all the points:

```
for s in nm.iter_sections(nrn):
        print(s.points[0])
```

But when printing out these points you always get 7 values, and not 5 like described in the documentation. Does here 'point' mean something different?

**Comment by asanin-epfl** [comment]
Fixed in NeuroM v2 https://neurom.readthedocs.io/en/latest/_neurom_build/neurom.core.dataformat.html#neurom.core.dataformat.Point
