### ISSUE TITLE
Point Type documentation

### ISSUE THREAD

**Issue by alex4200** [BlueBrain/NeuroM#741]
In the definition of the point types :

`neurom.core.dataformat.POINT_TYPE`

no mapping seems to be given which maps the types to the numeric values given for each point. How do I know what type=2 means?

**Comment by mgeplf** [comment]
The `POINT_TYPE` is/was meant to be somewhat opaque, such that people don't rely on its numerical value.  That being said, I'm not sure how much it's used, and I thin it should probably be removed along wit the `Point` class to reduce confusion.  Thoughts @wizmer?

**Comment by wizmer** [comment]
Agreed, it's a pity that Python enums have to have an integer value. The value is irrelevant in this case. Also, neurom.core.dataformat.POINT_TYPE is a private enum, that's why it only appears in the developper API.

**Comment by asanin-epfl** [comment]
POINT_TYPE was deleted in NeuroM v2.
