### ISSUE TITLE
No core documentation available. 

### ISSUE THREAD

**Issue by alex4200** [BlueBrain/NeuroM#742]
Documentation seems to be missing for [core](https://neurom.readthedocs.io/en/latest/_neurom_build/neurom.core.html).

**Comment by mgeplf** [comment]
After investigations, it seems the default for the sphinx `autosummary` directive changed:
https://github.com/sphinx-doc/sphinx/commit/4ece70109361ed8f753063a9d924731285c1d2c8

Before it would document `import`s by default, and after that change it doesn't.  Sadly, the option to control this hasn't been released yet, it appears to be in tree though, and should be released in the 2.1 release:
http://www.sphinx-doc.org/en/master/usage/extensions/autosummary.html#confval-autosummary_imported_members

**Comment by mgeplf** [comment]
Docs being built now:
https://neurom.readthedocs.io/en/latest/_neurom_build/neurom.core.html
