### ISSUE TITLE
Plotting neuron if axon originates from dendrite

### ISSUE THREAD

**Issue by INF-Rene** [BlueBrain/NeuroM#768]
In the viewer, the neurites are colored by it's root section type, so in neurons with the axon originating at the dendrite, the code below plots the entire neuron:
```
fig=plt.figure()
ax=plt.gca()
nm.view.view.plot_neuron(ax, nrn, neurite_type=NeuriteType.basal_dendrite, color='red')
ax.autoscale()
```
and 
`nm.view.view.plot_neuron(ax, nrn, neurite_type=NeuriteType.axon, color='red')
` plots nothing but the soma

This is because the plotting method iterates over neurites, which types are determined by the root section. 
Would it be an idea to let the `nm.view.view.plot_neuron` method iterate over sections instead of neurites?

**Comment by wizmer** [comment]
Yes, that's something I have thought about for a while. I'll work on it this week.

**Comment by INF-Rene** [comment]
@wizmer , awesome, let me know if there is something I can do to help
