### ISSUE TITLE
unable to load swc with no soma

### ISSUE THREAD

**Issue by carshadi** [BlueBrain/NeuroM#773]
Hello, i am trying to load an swc which contains a root point and an axon but no annotated soma. I was unable to accomplish this using ```load_neuron()``` as it fails if there is no soma. I could not find any info on alternative ways to accomplish this.

Thanks,
Cameron

**Comment by mgeplf** [comment]
What do you mean by `root point`?

We've wondered on how best to approach this before, and have never come to a good conclusion on how to handle it - name how to signal to the user that a soma is missing and should be there, but to also allow morphologies without somata.  In the latter case, whether a 'virtual' soma should exist, etc.

I'm _considering_ adding a parameter to `load_neuron` that would allow passing a `virtual` soma, or something to say 'ignore the fact that no-soma exists', but adding parameters like this is always delicate, because they are confusing if there are a lot of them.

Thoughts?

**Comment by carshadi** [comment]
Hi @mgeplf , I should have been more specific. The SWC i'm trying to load has just an axon with the first point having parent == -1. The annotation software I am using does not currently have a way to assign neurite types to the reconstruction, including soma. The second column of the SWC file is instead used to signify branch points, end points and unidentified nodes (5, 6, and 0 respectively). 

Converting the SWC to the standardized format would be the obvious choice, but I was curious if there was a way to ignore the structure identifiers and just get the morphometrics of a "general" tree structure.

**Comment by mgeplf** [comment]
Huh, interesting - it would be the first time we've come across the second column being used to the `branch points, end points and unidentified nodes` numbering, considering one can recover that information from the tree structure.

I think it would be difficult to add support for the branch/endpoint/ system of doing things, but instead what you could do is convert the files on the fly, something like:
```
import os
import re

def convert_morph(path):
    assert path.endswith('.swc'), 'Must be SWC file'

    lines = []
    with open(path, 'r') as fd:
        for line in fd:
            line = line.strip()
            if line.startswith('#') or not line:
                continue
            id_, _, rest = re.split('\s+', line, 2)
            lines.append('{} {} {}'.format(id_, '2', rest))

    #fake soma, centered at origin, radius = 1
    lines.append('{} 1 0. 0. 0. 1. -1'.format(len(lines) + 1))

    # connect the first point to fake soma
    lines[0] = lines[0].replace('-1', str(len(lines)))

    new_name = os.path.join(os.path.dirname(path),
                            os.path.basename(path).split('.', 1)[0] + '_converted.swc')
    with open(new_name, 'w') as fd:
        fd.write('\n'.join(lines))
    return new_name

```

This is a hack, and it's not really going to work well, but at least you'd be able to some morphometrics.

**Comment by carshadi** [comment]
this is very helpful, thank you.
