### ISSUE TITLE
potential error in partition asymmetry

### ISSUE THREAD

**Issue by carshadi** [BlueBrain/NeuroM#777]
Hello, I am trying to get the partition asymmetry of this test tree (red circle indicates Soma point):
![pa_test](https://user-images.githubusercontent.com/44130022/67904245-27777980-fb44-11e9-9577-d50008b7b018.png)
I chose this morphology as it mirrors the example on the L-measure page for partition asymmetry: http://cng.gmu.edu:8080/Lm/help/Partition_asymmetry.htm

From my understanding, the returned values should be ``` [1.0, 1.0, 0.0] ``` if going by the formula:   
 ``` abs(n1 - n2) / (n1 + n2 - 2) ``` 
where ```n1``` is the number of tips on the left and ```n2``` is the number of tips on the right.  However, running ``` partition_asymmetries = nm.get('partition_asymmetry', nrn, neurite_type=nm.AXON) ``` returns the list ``` [0.66666667 0.5        0.        ] ```. I am not sure if the error is in my interpretation.

**Comment by mgeplf** [comment]
I don't see the  '- 2' in the code:
https://github.com/BlueBrain/NeuroM/blob/master/neurom/fst/_bifurcationfunc.py#L102

Maybe @lidakanari can comment.

**Comment by carshadi** [comment]
I see, that makes sense.
Thanks!

**Comment by mgeplf** [comment]
Following the docstring reference (https://www.ncbi.nlm.nih.gov/pubmed/18568015), it leads me to https://jvanpelt.nl/papers/Uylings_Network_13_2002_397-414.pdf where eq 1 has the `- 2` offset, so I don't think it's just an L-measure thing - it seems to be the `standard`.  Given that, I think the function with this name should return the `standard`, or we need to make it much more clear that this includes a slightly different interpretation.

**Comment by lidakanari** [comment]
I completely agree with @mgeplf because indeed this term refers to a specific measurement. However, because we also needed the current computation for validations I would rename this function and correct the partition asymmetry to the expected formula.

**Comment by lidakanari** [comment]
Actually I just realized that in the code we provide as reference the "standard" definition of partition taken from this paper: https://www.nature.com/articles/nrn2402. 

> '''Calculate the partition asymmetry at a bifurcation point
    as defined in https://www.ncbi.nlm.nih.gov/pubmed/18568015"

According to the petilla terminology and figure 2 (https://www.nature.com/articles/nrn2402/figures/2) the partition asymmetry does not include this "-2" that is found in other references provided in this issue. Apparently the literature is not consistent on this, but I think we should stick to the definition and references provided in the code.

**Comment by lidakanari** [comment]
What is peculiar is that this is inconsistent with the reference mentioned by @mgeplf (https://jvanpelt.nl/papers/Uylings_Network_13_2002_397-414.pdf) so I am not sure how to proceed with this one because the terminology paper does not agree with the one they cite.

**Comment by mgeplf** [comment]
In that article, it references Uylings, H. B. M. & van Pelt, J. Measures for quantifying dendritic arborizations. Netw. Comput. Neural Syst. 13, 397–414 (2002). (footnote 26), which has the -2:
![image](https://user-images.githubusercontent.com/13150119/69352521-5b464a80-0c7d-11ea-91bc-26209fd6f584.png)

**Comment by lidakanari** [comment]
Yes but in the paper we refer to (The petilla one) they define asymmetry as follows: 
![image](https://user-images.githubusercontent.com/14071443/69352767-bf690e80-0c7d-11ea-8f0e-9e46a459416b.png)
I assume that was the one we used in the code.

**Comment by mgeplf** [comment]
But the reference they make is to the Uylings et al 2002 paper, which is more focused on tree properties than the Petilla terminology one - doesn't it make sense to follow the primary source?

**Comment by lidakanari** [comment]
I am not sure what is optimal (apparently there is an inconsistency in literature for this). If we modify the measurement we should also change the reference to the original paper from the Petilla one. But as mentioned in my previous comment the "new" version was more meaningful for validations. So I would still like to keep this feature, but possibly under a different name.

**Comment by mgeplf** [comment]
> my previous comment the "new" version was more meaningful for validations

That makes sense, and why I'm pretty on the fence about what should be done.  I'd like to understand go through the Uylings (?) 1999 paper that the 2002 one references, to see if they develop the idea further.  I find it weird that they also didn't want to discriminate between the cases like you mentioned.

At the least, I think we should add a comment in the docstring saying that this differs from Uylings and L-Measure, and give the reason.

**Comment by lidakanari** [comment]
I was thinking that it is maybe meaningful to have both implementations. Could we have:
1. partition_asymmetry (as in the Uylings ref)
2. partition_asymmetry_petilla (as in the Petilla terminology paper) 

My impression is Uylings, Van Pelt et al were the first to introduce the idea and until the Petilla work this has evolved and "updated". I guess each measurement is useful for different use-cases. For example (1) will cluster all "very asymmetric" trees together and that can be meaningful for some analysis. On the other hand, some analysis might need to separate between a (10,1) and (5,1) asymmetric tree and in this case (2) would be more appropriate.

**Comment by asanin-epfl** [comment]
@lidakanari for backward compatibility I propose to keep the single function `partition_asymmetry` that would calculate as before by Petilla. With additional argument `method='uylings'` it would calculate by Uylings.

What do you think?
