### ISSUE TITLE
Pickle neuron object

### ISSUE THREAD

**Issue by arnaudon** [BlueBrain/NeuroM#779]
Hi all, 

I want to use multiprocessing (and thus pickle), and it seems impossible to pickle Neuron objects:
`TypeError: can't pickle Neuron objects`

where I just `pickle.dump(neuron)`, with `type(neuron) = <class 'neurom.core._neuron.Neuron'>`. 

Thanks for you help!

**Comment by eleftherioszisis** [comment]
Usually what we do with multiprocessing is to open the morphology from within the parallel worker instead of sending it. Therefore, you will need to pass the filepath instead of the object itself to the worker.

**Comment by arnaudon** [comment]
Yes, I did that just after I wrote this ticket, I guess it is the best (only) option, so I'll close this issue.
