### ISSUE TITLE
Github incorrectly tags NeuroM languages

### ISSUE THREAD

**Issue by wizmer** [BlueBrain/NeuroM#784]
Github says NeuroM is composed of the following languages:
    Jupyter Notebook 62.7%
    AGS Script 20.5% 
    Python 16.8% 

which makes NeuroM appears as a Jupyter Notebook package in the Github search:
https://github.com/search?q=neurom

The language detection is run with https://github.com/github/linguist
According to them, one can drop them a PR to fix that.

**Comment by asanin-epfl** [comment]
The current picture is:
AGS Script 56%
Python 42.8%
Jupyter Notebook 1.2%
