### ISSUE TITLE
'morph_stats' output: just one output for morphology files equally named but with different extensions

### ISSUE THREAD

**Issue by pedroernesto** [BlueBrain/NeuroM#786]
Recent versions of NeuroM do not include the extension of the original morphology files in their _morph-stats_ output . Example:

When running _morph_stats_ on a directory with 2 files C230300D1-rep-cor.h5 and C230300D1-rep-cor.swc:
1) the output file contains information about just one instead of two cells
2) the extension of the source file is not included

{
   "C230300D1-rep-cor": {
      "axon": {
         "max_section_branch_order": 15, 
         "total_neurite_length": 14302.22999937718, 
         "total_number_of_neurite": 1
      }, 
      "basal_dendrite": {
         "max_section_branch_order": 3, 
         "total_neurite_length": 2398.5855940959173, 
         "total_number_of_neurite": 7
      }, 
      "total_soma_radius": 12.9966
   }
}

**Comment by asanin-epfl** [comment]
Done via #909
