### ISSUE TITLE
Plotly cannot draw a single neurite

### ISSUE THREAD

**Issue by haleepfl** [BlueBrain/NeuroM#796]
When using the plotly drawing module, I would like to be able to draw a single neurite as shown in the tutorial notebook. Currently this is not possible, input and error:
```python3
fig, ax = plotly.draw(neuron.neurites[0], inline=True)
>>> AttributeError: 'Neurite' object has no attribute 'soma'
```

See also this comment: https://github.com/BlueBrain/NeuroM/issues/670#issuecomment-442819943

**Comment by wizmer** [comment]
Fixed in #797
