### ISSUE TITLE
Consider including plotly by default

### ISSUE THREAD

**Issue by haleepfl** [BlueBrain/NeuroM#798]
Currently plotly is an optional extra dependency, given there are tutorials using it and it allows interactive plots, should it be included by default to improve user experience?

**Comment by mgeplf** [comment]
It's a large dependency, and in cases where neurom is used non-interactively, it might make installation difficult.  Truth be told, in the past, the idea was to split out the plotting stuff, so there wasn't even a matplotlib dependency.

**Comment by eleftherioszisis** [comment]
I agree with Mike on this one. NeuroM is an essential tool in non-interactive pipelines. Thus, there is no need in forcing such a big dependency.

**Comment by wizmer** [comment]
>  Truth be told, in the past, the idea was to split out the plotting stuff, so there wasn't even a matplotlib dependency.
Yes. We could actually make the whole viewer part of NeuroM as an extra to get rid of the Matplotlib dependency as well.
