### ISSUE TITLE
error in 3d sphere eqn in plotly

### ISSUE THREAD

**Issue by yulint** [BlueBrain/NeuroM#830]
In NeuroM/neurom/view/plotly.py under _fill_soma_data,

The coordinates for points in the 3d sphere are given as:
       z = np.outer(np.ones(100), np.cos(phi)) + neuron.soma.center[2]
       x=(np.outer(np.cos(theta), np.sin(phi)) + neuron.soma.center[0]) * r,
       y=(np.outer(np.sin(theta), np.sin(phi)) + neuron.soma.center[1]) * r,
       z=z * r,

But the radius should multiply only the np.outer(...) in order for the soma to be placed correctly:
        x=neuron.soma.center[0] + np.outer(np.cos(theta), np.sin(phi)) * r 
        y=neuron.soma.center[1] + np.outer(np.sin(theta), np.sin(phi)) * r
        z=neuron.soma.center[2] + np.outer(np.ones(100), np.cos(phi)) * r

**Comment by wizmer** [comment]
Thanks for the notification. It feels that I have fixed this bug at least 12 times. I will make a PR for that. Thanks again !
