### ISSUE TITLE
error in segment_path_lengths fxn

### ISSUE THREAD

**Issue by yulint** [BlueBrain/NeuroM#833]
Hi, 

I think there is potentially a missing np.cumsum() around the sectionfunc.segment_lengths(section) in line 293 of neuritefunc.py:

result = [_get_pathlength(section) + sectionfunc.segment_lengths(section)
              for section in iter_sections(neurites, neurite_filter=neurite_filter)]

Cheers

PS. thanks for this package, it has made handling the swc file and writing custom functions a lot easier :)

**Comment by wizmer** [comment]
Hi, thanks for opening this issue! I have fixed the code and will close this issue.

If you like NeuroM, you might be interested by a few of the other code we recently open-sourced (I sound like an add, lol)
[MorphIO](https://github.com/bluebrain/MorphIO) a lower level IO library for reading/writing morphology files
[morph-tool](https://github.com/bluebrain/morph-tool) a "toolbox" to perform various operation on morphologies
[NeuroR](https://github.com/bluebrain/neuror) a software for the repair of experimental morphologies
