### ISSUE TITLE
Inconsistency of trunk angles computation for SWC 

### ISSUE THREAD

**Issue by lidakanari** [BlueBrain/NeuroM#836]
I noticed that the same morphology written in SWC and H5 behaves differently in a subsequent analysis:

neurom.get('trunk_angles', n1)                                                                                                                                  
array([1.22883997, 2.40792416, 1.24811592, 0.20883851, 0.04060654, 1.14886118])

neurom.get('trunk_angles', n2)
array([nan, 0.39250956, 0.24012936, 0.12505715, 0.87182467,  nan])

I attach the example files that are expected to be the same, minus numerical inconsistencies [Example.zip](https://github.com/BlueBrain/NeuroM/files/4799419/Example.zip)

**Comment by asanin-epfl** [comment]
This happened due to contour soma in .swc. Such soma appeared due to incorrect conversion to .swc. This problem is addressed in BlueBrain/MorphIO#299 and BlueBrain/morph-tool#64
