### ISSUE TITLE
Wrong loading of SWC file

### ISSUE THREAD

**Issue by lidakanari** [BlueBrain/NeuroM#837]
I have an example swc ([L2_TPC_A_30.swc.zip](https://github.com/BlueBrain/NeuroM/files/4851416/L2_TPC_A_30.swc.zip)) which is loaded as cylinder soma, while the soma is actually a contour:

```
import neurom
n = neurom.load_neuron('./L2_TPC_A_30.swc')
```
```
Neuron <soma: SomaCylinders(array([[-6.96805 , -2.656723,  0.      ,  0.      ,  1.      ,  1.      ,
        -1.      ],
       [-0.849299, -6.261855,  0.      ,  0.      ,  1.      ,  2.      ,
         1.      ],
       [ 4.545042, -5.697706,  0.      ,  0.      ,  1.      ,  3.      ,
         2.      ],
       [ 6.427235, -3.781871,  0.      ,  0.      ,  1.      ,  4.      ,
         3.      ],
       [ 6.869308, -2.902499,  0.      ,  0.      ,  1.      ,  5.      ,
         4.      ],
       [ 1.859042,  6.857763,  0.      ,  0.      ,  1.      ,  6.      ,
         5.      ],
       [ 0.      ,  7.457338,  0.      ,  0.      ,  1.      ,  7.      ,
         6.      ],
       [-4.893711,  4.922414,  0.      ,  0.      ,  1.      ,  8.      ,
         7.      ]])) <center: [-6.96805  -2.656723  0.      ], virtual radius: 0.0>, n_neurites: 7>
```

This causes the plotting to fail and I suspect it might also be related to issue #836 which causes errors in the morphological feature computation.

**Comment by mgeplf** [comment]
I was under the impression that there was no such thing as an SWC contour soma.

The header says that it was made by `Created by MorphIO v2.3.3`; was this a conversion from some other file?

**Comment by wizmer** [comment]
Yes, SWC does not have soma contours:
https://github.com/BlueBrain/MorphIO/blob/master/doc/specification.md#swc

As Mike said, this file was probably a ASC or H5 file that got converted to SWC. During this process, soma contours are converted to soma cylinders.

**Comment by asanin-epfl** [comment]
We rather should throw when reading morphologies like [L2_TPC_A_30.swc.zip](https://github.com/BlueBrain/NeuroM/files/4851416/L2_TPC_A_30.swc.zip). It should happen on MorphIO side. Closing in favor of #299
