### ISSUE TITLE
Errors in examples/soma_radius_fit

### ISSUE THREAD

**Issue by juanchopanza** [BlueBrain/NeuroM#84]
There are various errors in soma_fit. These were not caught because the filename doesn't end with `.py`. Anyway, some of these are styling issues, but others are real errors.

Pep8
====

> examples/soma_radius_fit.py:43:101: E501 line too long (114 > 100 characters)
examples/soma_radius_fit.py:68:64: W291 trailing whitespace
examples/soma_radius_fit.py:89:46: E231 missing whitespace after ','
examples/soma_radius_fit.py:92:46: E231 missing whitespace after ','
examples/soma_radius_fit.py:92:49: E203 whitespace before ':'
examples/soma_radius_fit.py:111:101: E501 line too long (101 > 100 characters)
examples/soma_radius_fit.py:112:1: W391 blank line at end of file

Pylint
====

> ************* Module neurom.view.common
I: 44, 0: Locally disabling unused-import (W0611) (locally-disabled)
************* Module soma_radius_fit
C: 43, 0: Line too long (114/100) (line-too-long)
C: 68, 0: Trailing whitespace (trailing-whitespace)
C: 89, 0: Exactly one space required after comma
    fit_data = {d: distribution_fit(soma_size,d) for d in distr_to_check}
                                             ^ (bad-whitespace)
C: 92, 0: Exactly one space required after comma
    fit_error = {distribution_error(soma_size,d) : d for d in distr_to_check}
                                             ^ (bad-whitespace)
C:111, 0: Line too long (101/100) (line-too-long)
W: 71, 4: Unused variable 'params' (unused-variable)
E:107, 8: Undefined variable 'L' (undefined-variable)
E:108, 8: Undefined variable 'sys' (undefined-variable)

To reproduce: change the filename to `examples/soma_radius_fit.py, then run `make lint`.

**Comment by juanchopanza** [comment]
@lidakanari Could you look at this one?

**Comment by lidakanari** [comment]
Yes, that's on me. I'll take a look once I have some time.

**Comment by juanchopanza** [comment]
Fixed with pull request #97
