### ISSUE TITLE
Ability to plot neuron without axon using plotly.draw()

### ISSUE THREAD

**Issue by darshanmandge** [BlueBrain/NeuroM#848]
Hi,

It would nice to have an optional argument to plot neuron without certain sections e.g. without axon using plotly.draw()
or just to plot either apical or basal dendrites, or a given list of sections.

Thanks!

**Comment by asanin-epfl** [comment]
@darshanmandge, with NeuroM v2 you can manipulate with morphology, so you request can be implemented this way:

```python
from neurom import load_neuron, NeuriteType
from neurom import viewer
import matplotlib.pyplot as plt


def drop_neurite(neuron, neurite_type):
    axon_sections = [sec for sec in neuron.root_sections if sec.type == neurite_type]
    for axon_sec in axon_sections:
        neuron.delete_section(axon_sec)


n = load_neuron('tests/data/neurolucida/bio_neuron-000.asc')
drop_neurite(n, NeuriteType.axon)

fig, _ = viewer.draw(n)
plt.show()
```

Additionally you can create new sections. Please consult with @arnaudon for more info.

**Comment by arnaudon** [comment]
This seems the easiest solution indeed, thanks aleksei!

**Comment by darshanmandge** [comment]
Thanks for this workaround @asanin-epfl !

**Comment by asanin-epfl** [comment]
I'm happy to help, sorry for the late response.

**Comment by asanin-epfl** [comment]
@darshanmandge @arnaudon with #912 merged it becomes simpler. You need to filter out all axons via `neurite_type`.

```python
import neurom.viewer
import matplotlib.pyplot as plt
from neurom.core.types import tree_type_checker

nrn = neurom.load_neuron('tests/data/h5/v1/Neuron.h5')
neurom.viewer.draw(nrn, neurite_type=(neurom.SOMA, neurom.BASAL_DENDRITE, neurom.APICAL_DENDRITE))
plt.show()
```
