### ISSUE TITLE
Allow NeuroM to load cells without a soma

### ISSUE THREAD

**Issue by patilurie** [BlueBrain/NeuroM#856]
Hi,
I receive a lot of neuronal morphologies (.swc) which I need to verify for possible errors and convert to .asc. 
I use NeuroM for checking morphologies and webservice (Converter) for conversions in batch. As the morphology providers use Vaa3D which doesn't support soma reconstruction yet, I very often get the soma error (invalid soma) resulting in blocking the error verification (and file conversion). The problem is that I still need to communicate the errors to the morphologies' provider. Would it be possible to get the error report even in case of erroneous soma?

**Comment by wizmer** [comment]
@mgeplf I'd like your input on this. 
Should I change NeuroM so that it can load files without a soma or should we wait for NeuroM v2 which already handles them ?

**Comment by mgeplf** [comment]
v2 is dependent on the MorphIO windows wheels, iirc.

On which machines are you @patilurie running your conversions/checks?  If it's a unix-like environment, maybe @wizmer can have you use the neuron-v2 with MorphIO.

**Comment by patilurie** [comment]
@mgeplf I work on a Mac.

**Comment by wizmer** [comment]
In this case @patilurie you can try to update NeuroM to v2 with the following command:
```bash
pip install --pre neurom
```

You should end up with a NeuroM version 2.X.X and it should be able to load neurons without somas.

**Comment by patilurie** [comment]
Great! Thanks so much for your help @wizmer !

**Comment by asanin-epfl** [comment]
Solved via #900 for NeuroM v2
