### ISSUE TITLE
plot_dendrogram function cannot handle "custom" NeuriteType

### ISSUE THREAD

**Issue by evancresswell** [BlueBrain/NeuroM#882]
I am trying to plot the dendrogram of a non-neuronal cell: http://neuromorpho.org/neuron_info.jsp?neuron_name=S1_1_1

using the following code snippet:
`   
    from neurom import load_neuron
    from neurom import viewer
    n = load_neuron(mypath+filename)

    fig= plt.figure(figsize=(6,6))
    ax = fig.add_subplot(111)
    viewer.plot_dendrogram(ax, n, show_diameters=True)
    plt.show()
`

Resulting in the following error:

`
  File "/...path.../site-packages/neurom/view/view.py", line 349, in _get_dendrogram_shapes
    color = TREE_COLOR[dendrogram.neurite_type]
KeyError: <NeuriteType.custom: 5>
`

The error seems to be a simple matter of defining a "custom" neurite color type. Is it possible to fix this minor issue?

Thanks for you time.

**Comment by asanin-epfl** [comment]
Hi! @evancresswell please try the latest NeuroM 2.0.1

**Comment by asanin-epfl** [comment]
will be fixed in #902

**Comment by asanin-epfl** [comment]
@evancresswell please verify https://pypi.org/project/neurom/2.0.3/

**Comment by evancresswell** [comment]
It works. Thanks for your time.

Best,
Evan
