### ISSUE TITLE
RFE: Move away from using deprecated nose for testing

### ISSUE THREAD

**Issue by sanjayankur31** [BlueBrain/NeuroM#887]
# Feature
nose is deprecated, so it'll be good to move to another testing tool, perhaps py.test.

# Motivation
nose is deprecated upstream (the last commit was in 2016.) and is also being deprecated in Fedora.

https://github.com/nose-devs/nose/commits/master

It is still in use here, though

https://github.com/BlueBrain/NeuroM/blob/master/requirements_dev.txt#L32

The nose website says:

https://nose.readthedocs.io/en/latest/

"Nose has been in maintenance mode for the past several years and will likely cease without a new person/team to take over maintainership. New projects should consider using Nose2, py.test, or just plain unittest/unittest2."

Deprecation of nose in Fedora: https://fedoraproject.org/wiki/Changes/DeprecateNose

Alternatives
py.test or nose2 (but nose2 doesn't seem to be at par with nose or py.test)

# Additional context

This came up while working on including NeuroM in Fedora as part of the [NeuroFedora](neuro.fedoraproject.org) initiative:

https://pagure.io/neuro-sig/NeuroFedora/issue/193

**Comment by mgeplf** [comment]
@asanin-epfl I think Werner had good luck w/ https://github.com/pytest-dev/nose2pytest
after applying some transforms:

https://github.com/BlueBrain/BluePyOpt/blob/c3fe5c3c53f07d946031974794faf365243f9d7a/misc/pytest_migration/convert_pytest.sh

Hopefully something similar would make work here.

**Comment by asanin-epfl** [comment]
Thank you! I think there is no need for the script, if using the latest master of nose2ytest. Some minor adjustments still have to be done.
