### ISSUE TITLE
Coverage has not been uploaded lately:

### ISSUE THREAD

**Issue by mgeplf** [BlueBrain/NeuroM#891]
It looks like the last time was quite a while ago (2 years):
https://app.codecov.io/gh/BlueBrain/NeuroM/

Which means the badge is out of date.

**Comment by asanin-epfl** [comment]
Can I conclude from #720 that codecov actually was abandoned in favor of tox coverage, and we rather need to find a way to make a coverage badge that uses tox reports?

**Comment by tomdele** [comment]
Yeah I am trying to find something

**Comment by tomdele** [comment]
Done : 
https://github.com/BlueBrain/NeuroM/pull/895

**Comment by tomdele** [comment]
https://app.codecov.io/gh/BlueBrain/NeuroM 
looks good for the master and the branches
