### ISSUE TITLE
MatplotlibDeprecationWarning

### ISSUE THREAD

**Issue by antonelepfl** [BlueBrain/NeuroM#945]
Hi I'm having an issue:

When trying to run this notebook https://github.com/BlueBrain/MOOC-neurons-and-synapses-2017/blob/2021_release/NMCPortal/Final%20graded%20assignment.ipynb

In cell:
```
neurom.viewer.draw(neurom.load_neuron('morphology/dend-C310897B-P3_axon-C220498B-P3_cor_-_Clone_1.asc'));
```

Output:
```
/usr/local/lib/python3.8/dist-packages/neurom/view/common.py:108: MatplotlibDeprecationWarning: Passing non-integers as three-element position specification is deprecated since 3.3 and will be removed two minor releases later.
  ax = fig.add_subplot(subplot, **params)
```

I'm using NeuronM 2.3.0

Relates to https://github.com/BlueBrain/MOOC-neurons-and-synapses-2017/issues/72

**Comment by asanin-epfl** [comment]
So, you want to get rid of the warning? Does the code work?

**Comment by stefanoantonel** [comment]
The code does work.
It would be better not to have a warning

**Comment by asanin-epfl** [comment]
The new release https://github.com/BlueBrain/NeuroM/releases/tag/v2.3.1 should solve it. Please verify.

**Comment by antonelepfl** [comment]
Yes that fixed the warning. Thank you Aleksei
