### ISSUE TITLE
Dendrogram with synapses from morph-tool to neurom

### ISSUE THREAD

**Issue by asanin-epfl** [BlueBrain/NeuroM#951]
@arnaudon @adrien-berchet @eleftherioszisis  What do you think about moving https://github.com/BlueBrain/morph-tool/blob/master/morph_tool/dendrogram.py to NeuroM? It allows to draw synapses on dendrograms. Also now I'm working on a functionality that would allow to draw morphologies with synapses. I plan to create it in morph-tool but my general thought that such functionality might be often useful for scientists in NeuroM.

Please share your thoughts.

**Comment by jdcourcol** [comment]
neurom does not know about circuit, so it is not a great place.
May be a dedicated package that bridges morphology and synapses from circuit ?

**Comment by arnaudon** [comment]
I never used that tool, but from a quick look, it seems the synapse data is in a dataframe? Then what is the plot doing, dots on each synapse? What's in this dataframe, just a list of x,y,z position? if it's only that, synapses could be thought of as markers (such as apical point, cut leaves, etc...) and a generic plotting function for marker could do the job? I have started developing a marker API with some plots for that, maybe we can sync here.

**Comment by asanin-epfl** [comment]
> it seems the synapse data is in a dataframe?

Yes

> Then what is the plot doing, dots on each synapse?

No

> What's in this dataframe, just a list of x,y,z position?

No

>  generic plotting function for marker could do the job?

No

Input dataframe is expected to have fields like `afferent_section_id`, `afferent_segment_id`, and a calculation is carried to place synapses according to those fields.

Thank you for your feedback. I'm closing the issue. NeuroM won't be used for keeping this functionality.

**Comment by asanin-epfl** [comment]
> May be a dedicated package that bridges morphology and synapses from circuit ?

Lets use morph-tool for now as it is already a kind of swiss-knife tool for morphologies.
