### ISSUE TITLE
Fix Warning message

### ISSUE THREAD

**Issue by stefanoantonel** [BlueBrain/NeuroM#953]
We are getting:
```
Warning: with a 3 points soma, neurites must be connected to the first soma point:
ballandstick.swc:5:warning
```
When running the notebook:
```
https://github.com/BlueBrain/MOOC-neurons-and-synapses-2017/tree/use-jupyterlab3/ConstrModels/TutBallStickOpt/ballandstickopt.ipynb
```

![Screenshot 2021-07-19 at 11 35 32](https://user-images.githubusercontent.com/4954312/126139201-8d5b7a64-f7e9-4c50-8b4b-7c33d62fa93e.png)

Can we remove / hide that warning? What would be the 'proper' way to fix this?

**Comment by asanin-epfl** [comment]
I assume you are using a typical 'ball-and-stick.swc'.
```
1 1 0.0 0.0 0.0 10.0 -1
2 1 0.0 -10.0 0.0 10.0 1
3 1 0.0 10.0 0.0 10.0 2
4 3 0.0 10.0 0.0 2.0 3
5 3 0.0 100.0 0.0 2.0 4
```

The warning is due to line:
```
4 3 0.0 10.0 0.0 2.0 3
```
It must be
```
4 3 0.0 10.0 0.0 2.0 1
```
in order to get rid of the warning.

The warning is issued because the neurite is connected to the last soma point but must be to the first soma point. I don't remember the reasons for that.

**Comment by stefanoantonel** [comment]
@wvangeit Do you know if there was some reason to have it that way in the file?
Can we modify it without any problem?

**Comment by wvangeit** [comment]
There was no specific reason i think, but no reason at that point for it 'not' to be this way either.
You could try to run the notebook with a modified version, but there is a chance neuron might interpret it differently though.

**Comment by asanin-epfl** [comment]
@stefanoantonel if you get different results then you can use this morphology instead:
```
1 1 0.0 0.0 0.0 10.0 -1
2 3 0.0 10.0 0.0 2.0 1
3 3 0.0 100.0 0.0 2.0 2
```
This is the same morphology but in the shorter form. NEURON simulation must interpret it the same way as the original.

**Comment by stefanoantonel** [comment]
I ran the notebook with
`4 3 0.0 10.0 0.0 2.0 1`
And I get basically the same plots for that notebook.
So we should be fine right?

**Comment by wvangeit** [comment]
What does 'basically' mean? ;-)

**Comment by stefanoantonel** [comment]
Well here are the screenshots
[plots_new_swc.zip](https://github.com/BlueBrain/NeuroM/files/6855583/plots_new_swc.zip)

**Comment by wvangeit** [comment]
Ok, looks good

**Comment by stefanoantonel** [comment]
Then we can close this.
Thank you all!
