### ISSUE TITLE
Type of Neuron.root_sections != Neuron.sections

### ISSUE THREAD

**Issue by adrien-berchet** [BlueBrain/NeuroM#971]
`Neuron.sections` returns a list of `neurom.core.neuron.Section` objects while `Neuron.root_sections` returns a list of `morphio._morphio.mut.Section` objects, which is quite disturbing. I am wondering if we should not override the `root_sections` method to return `neurom.core.neuron.Section` objects, I think it would be more consistent. WDYT @eleftherioszisis ?

(moved https://github.com/BlueBrain/MorphIO/issues/334 here since it more related to `NeuroM`)

**Comment by arnaudon** [comment]
ah ok, I vaguely remember needing to do something like that a long time ago. But you are right, there is no need really. Eventually, one can load with morphio, and convert to neurom using Neuron class I think.

**Comment by eleftherioszisis** [comment]
I am not convinced that having methods named `morphio_` would bring anything to the table. If someone would like to extract morphometrics and mutate the morphology why not use exclusively the neurom interface? Otherwise, one could use directly morphio.

**Comment by mgeplf** [comment]
I think we'll be looking at this for the 'v4' version of NeuroM (which will also change the Axon-on-Dendrite handling).

In my opinion: NeuroM should only work with immutable morphologies; any changes to a morphology can be accomplished by converting it into a `MorphIO::mut::Morphology`, and if further analysis is needed, it can be loaded by NeuroM

> One can still access the protected morphio object from neurom, right? 

Yes, I think we'd have a `Morphology.to_morphio()` method, or something like it.

**Comment by arnaudon** [comment]
Tbh, given this never ending struggle between morphio/neurom, I would deprecate neurom, and put all the feature extraction stuff of neurom in morphio, so it's all consistent. I don't know the origin of having to similar codes handling morphologies, but as far as I can see, it was a pretty bad move haha

**Comment by adrien-berchet** [comment]
I agrre with that, IMO `NeuroM` should only contain analysis functions that should just be applied to `MorphIO` objects (that's what I talked about for the GSoC project). But ofc it's quite a big work.

**Comment by mgeplf** [comment]
They have different targets:
* MorphIO is for loading and saving morphs, that's it.  It shouldn't do any sort of processing, because there are too many assumptions about how that is done; its scope is purposefully very narrow.  It's also primarily a c++ project, and adding all the morphometrics in c++ would be quite difficult, and not useful for most of the MorphIO consumers.
* NeuroM is about morphometrics, and extracting data from morphologies; it's mentioned explicitly in the Markram et al 2015 Cell paper's supplementary material, so I'm not sure we can deprecate it.

**Comment by mgeplf** [comment]
@adrien-berchet: I think we're close to on the same page; I agree with the `which is quite disturbing` sentence you wrote at the start of the thread, and that's what we should aim towards, imo.

Basically, the fact that `NeuroM` uses `MorphIO` is an implementation detail, that shouldn't be something the user needs to know about.  I thik we can provide `from_morphio()` and `to_morphio()` methods, but that's the maximum of the public API that is `MorphIO` aware, and that a library user can rely on.

Anyways, we're actively looking at this now, and will get back to you. (Note: I'm also keeping the iterator points you mentioned wrt MorphIO in the back of my head - it hasn't been forgotten :))

**Comment by adrien-berchet** [comment]
Ok, look good! Let's keep in touch about this.
Thanks :)
