### ISSUE TITLE
Morphology level radial distance features default on using tree root as origin

### ISSUE THREAD

**Issue by eleftherioszisis** [BlueBrain/NeuroM#982]
Radial distance features at the morphology level use the start of neurites as their origin.

However, the radial distance at the morphology level is usually calculated from the soma, not the neurite root.

The current convention of radial distances is also conflicting with the calculation of radial distance features using subtrees. For example, if an axon on dendrite is processed, the distal axon part will have its radial distances calculated from the axon root, not the basal one.

My proposal for NeuroM v4 is:

1. Set the soma center as the default origin for radial distance features at the morphology level
2. Set the neurite root as the default origin for radial distance features at the neurite level (current behavior)

@lidakanari , @arnaudon

**Comment by arnaudon** [comment]
+1!

**Comment by lidakanari** [comment]
+1 from me
