### ISSUE TITLE
`volume_density` is not calculated correctly at the morphology level

### ISSUE THREAD

**Issue by eleftherioszisis** [BlueBrain/NeuroM#995]
The volume density feature is calculated by dividing the sum of the morphology volume over the volume of the convex hull that is calculated from the segment points.

https://github.com/BlueBrain/NeuroM/blob/c570a2faa18f4e417fcdb743f6487beee0c60c3e/neurom/features/neurite.py#L449-L467

This feature is currently _implemented as a neurite feature_.

When the following is called:
```python
neurom.features.get("volume_density", morphology)
```
the feature logic applies the volume density feature to each neurite separately and sums the results.

However, this calculation **is not additive at the neurite level**, because a convex hull from the entire collection of points needs to be made. The total volume of the neurites over the morphology's convex hull is not the same as the sum of each neurites's volume over its respective convex hull.

@lidakanari @arnaudon @adrien-berchet

**Comment by lidakanari** [comment]
I completely agree, this is not the correct calculation. By adding the densities of individual neurites we assume that they are located within the _same exact_ convex hull. However, that is hardly the case, and indeed a convex hull needs to be computed for the full morphology to extract this feature at the _morphology_ level.
