### ISSUE TITLE
Inappropriate `warnings.simplefilter`

### ISSUE THREAD

**Issue by Stannislav** [BlueBrain/NeuroM#997]
in `neurom.utils.warn_deprecated` `warnings.simplefilter` is used to enforce that a deprecation warning is shown:
https://github.com/BlueBrain/NeuroM/blob/c570a2faa18f4e417fcdb743f6487beee0c60c3e/neurom/utils.py#L40-L44

This is problematic for several reasons
* It's not the business of a library to configure how the warnings are shown
* There is no way for the library user to easily disable those warnings
* By calling `warnings.simplefilter` `neurom` modifies the global state and has the side-effect of permanently setting ` warnings.simplefilter('default', DeprecationWarning)`. E.g
  ```py
  import warnings
  import neurom as nm
  
  print("before:", warnings.filters)
  nm.load_neuron(some_path)  # this triggers the warning `neurom.io.utils.load_neuron` is deprecated
  print("after:", warnings.filters)
  ```
  output:
  ```
  before: []
  after: [('default', None, <class 'DeprecationWarning'>, None, 0), ('always', None, <class 'DeprecationWarning'>, None, 0)]
  ```

I would strongly advocate for removing the two `warnings.simplefilter` lines.

P.S.: since `warnings.warn` is wrapped into `warn_deprecated` setting `stacklevel=3` should be considered.

**Comment by eleftherioszisis** [comment]
I agree that the lib should not set globals when imported and run. We could make this behavior exclusive to the cli.

@mgeplf thoughts?

**Comment by mgeplf** [comment]
Was writing a response; fully agree that
1) libraries shouldn't output things without at least a way to control them
2) the current behavior changing global state is broken

We still need to be able to display deprecation warnings though, at least once, but they should be controllable.

We also need to deprecate the functions we promise to deprecate...

**Comment by Stannislav** [comment]
So what speaks against dropping `warnings.simplefilter` and just writing
```py
warnings.warn("I'm deprecated", DeprecationWarning) 
```
AFAIK that's how it's commonly done to deprecate stuff. I'm sure one can find a lot of examples in popular libraries:
* [PyTorch](https://github.com/pytorch/pytorch/blob/9f541aa3aca768e7fbfa4a9d648b554f22b261f7/torch/distributed/elastic/metrics/api.py#L153)
* [Flask](https://github.com/pallets/flask/blob/edac7e3a560d93ac9f13bf162e677413b03a27e1/src/flask/helpers.py#L452-L458)
* [Airflow](https://github.com/apache/airflow/blob/8505d2f0a4524313e3eff7a4f16b9a9439c7a79f/airflow/contrib/operators/gcp_sql_operator.py#L35-L39)

**Comment by mgeplf** [comment]
I'm guessing that the simpler method wasn't used because that code dates back to 2016 (8fa549a99e52780338d52e0e037d07bff7e45859), and it wasn't warning enough.  Not sure.

Those examples aren't decorators, and are inline; I think it's best if we keep the current model. Probabl something like https://wiki.python.org/moin/PythonDecoratorLibrary#Smart_deprecation_warnings_.28with_valid_filenames.2C_line_numbers.2C_etc..29 works.

**Comment by eleftherioszisis** [comment]
The main issue with warnings is that they are by default hidden (see https://bugs.python.org/issue24294). Therefore, using the deprecated components interactively will not show any deprecation warnings to inform the user.

**Comment by eleftherioszisis** [comment]
I removed my edit above, as I realized that the problem is not reverting back to the default, rather setting default when there was a different pre-existing configuration. So to make the warnings respect the existing configuration we can change that part using the `catch_warnings` context manage:
```python

with warnings.catch_warnings():
    warnings.simplefilter("always", DeprecationWarning)
    warnings.warn(msg, category=DeprecatioWarning, stacklevel=3)
```

**Comment by Stannislav** [comment]
@eleftherioszisis I think this solution only addresses one of the two points. It's still impossible to turn off this warning if one wishes to.

My particular usecase, which led me to writing this issue: I have a morphology processing pipeline that loads hundreds of morphologies. I'm aware of the deprecation. It will be deal with later. Nonetheless, as a consequence my stderr gets flooded with warnings that I don't want to see, but also can't disable at all.

I think one could also have the situation that someone uses a 3rd party library that itself useses NeuroM. Then the only way to remove the warning would be to wait for the maintainer of the 3rd party library to upgrade it.

At the end of the issue you linked someone was wondering if this hasn't been solved by [PEP-565](https://peps.python.org/pep-0565/). I just ran a bit of testing (`py39`)

```py
# x.py
import warnings

def f():
    warnings.warn("The function f is deprecated", DeprecationWarning, stacklevel=2)
```
```py
# y.py
import x

def g():
    x.f()
```
```py
# run.py
import sys

import x


def main():
    x.f()
    return 0


if __name__ == "__main__":
    sys.exit(main())
```
```
$ python run.py 
/Users/sschmidt/Desktop/xx-warnings/run.py:7: DeprecationWarning: The function f is deprecated
  x.f()
```
```
$ python
>>> import y
>>> y.g()
>>> import x
>>> x.f()
<stdin>:1: DeprecationWarning: The function f is deprecated
```
Looks like the warning shows both when running a script and when using directly in a REPL. Wouldn't this be enough?

**Comment by eleftherioszisis** [comment]
I am not sure I follow. Here we are not discussing about the application level of neurom (e.g. morph-checker, morph-stats), where the `__main__` can be used. Instead, we want the deprecation warnings to be visible when people import the modules from the package, which are not executable by themselves.

A solution that would avoid making any changes to the warnings configuration, would be to create a neurom-specific deprecation warning that subclasses `UserWarning`, instead of `DeprecationWarning`. By default user warnings are visible. (See latest changes: https://github.com/BlueBrain/NeuroM/pull/1002/files)

**Comment by adrien-berchet** [comment]
What would happen if `NeuroMDeprecationWarning` inherits from both `UserWarning` and `DeprecationWarning`? I never tried it.

**Comment by Stannislav** [comment]
> I am not sure I follow. Here we are not discussing about the application level of neurom (e.g. morph-check, morph-stats), where the __main__ can be used. Instead, we want the deprecation warnings to be visible when people import the modules from the package, which are not executable by themselves.

@eleftherioszisis sorry, I probably misunderstood. You mentioned interactive use above, so I assumed you meant the REPL. So you're more concerned about the `y.g()` example above the warning not showing? I suppose there are several approaches for handling this. The paradigm I'm familiar with is that it's the maintainers of the package `y` who catch and fix this warning. They write unit tests and the warning shows up there. They might configure their CI so that it fails on deprecation warnings.

Anyway, I hope I understand the issue correctly. For sure not trying to dictate how you guys should solve this, just trying to give some useful input :)

**Comment by eleftherioszisis** [comment]
> sorry, I probably misunderstood. You mentioned interactive use above, so I assumed you meant the REPL. So you're more concerned about the y.g() example above the warning not showing? 
No worries, it's my fault for not explaining what is the purpose of these warnings. NeuroM is frequently used interactively, so we want users to get the deprecation warnings so that they switch to the new API.

What do you think about the latest changes https://github.com/BlueBrain/NeuroM/pull/1002/files where I introduced a neurom-specific warning which derives from UserWarning? This way there is no need for configuration, so it can be disabled if warnings are set before running neurom or with the `catch_warnings` context manager, and it is visible by default.

**Comment by eleftherioszisis** [comment]
@adrien-berchet , adding `DeprecationWarning` by multiple inheritance renders the warning silent, which is not what we want.

**Comment by adrien-berchet** [comment]
> @adrien-berchet , adding `DeprecationWarning` by multiple inheritance renders the warning silent, which is not what we want.

Yeah ok, I was just wondering if it would make appear where either `UserWarning` or `DeprecationWarning` is allowed or if it would make disappear in both cases. Unfortunately it's the 2nd option :)

**Comment by Stannislav** [comment]
@eleftherioszisis 
> What do you think about the latest changes https://github.com/BlueBrain/NeuroM/pull/1002/files where I introduced a neurom-specific warning which derives from UserWarning?

I added a review :)
