### ISSUE TITLE
`principal_direction_extents` are biased by duplicate points

### ISSUE THREAD

**Issue by eleftherioszisis** [BlueBrain/NeuroM#998]
The principal direction extents are calculated via the eigenvectors of the points covariance matrix.

https://github.com/BlueBrain/NeuroM/blob/c570a2faa18f4e417fcdb743f6487beee0c60c3e/neurom/morphmath.py#L450

Duplicate points bias the direction of the covariance ellipsoid because they are present in the calculation multiple times. The points that are provided by morphio include duplicates.

https://github.com/BlueBrain/NeuroM/blob/c570a2faa18f4e417fcdb743f6487beee0c60c3e/neurom/features/neurite.py#L495-L498

The correct behavior would be to perform the PCA on the unique instead of the raw points returned by the neurite.

FYI @lidakanari @adrien-berchet @lidakanari

**Comment by adrien-berchet** [comment]
Nice catch again!
